### ISSUE TITLE
Reading non-ociv1 image configs is lossy

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#1]
Right now the tool assumes that image configurations can be decoded as OCI image-spec v1 Image objects.  If the source image is anything else, we lose information this way.

**Comment by nalind** [comment]
We should be able to read `github.com/docker/docker/image.Image` configuration blobs now.  There's some information in manifests that decode as `github.com/containers/image/image.manifestSchema1` in images like kubernetes/pause where we don't have a config blob, and we might have to try fishing around in the manifest for them.

**Comment by rhatdan** [comment]
Is this issue still present?

**Comment by nalind** [comment]
We handle images that include config blobs (version 2, schema 2), but we still don't support digging around in (version 2, schema 1) images.

**Comment by nalind** [comment]
As of #118, we should be handling v2 schema 1 images, so I think we can finally close this one.
