### ISSUE TITLE
Delete container got error "identifier is not a layer"

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#104]
Not sure how it occurred, it should be happened occasionally.

```
[root@fedora buildah]# ./buildah containers 
CONTAINER ID IMAGE ID     IMAGE NAME CONTAINER NAME
aaeed31f4ddd b812babf7f65 redis      redis-working-container-2
a27d2cc74487 a37f13666262 testing/nginx nginx-working-container
e840e91f1cc7 a37f13666262 testing/nginx nginx-working-container-2
41addd8528fc a37f13666262 testing/nginx nginx

[root@fedora buildah]# ./buildah delete aaeed31f4ddd
error removing container "redis-working-container-2": error deleting build container: identifier is not a layer
ERRO[0000] error deleting build container: identifier is not a layer 
```

**Comment by rhatdan** [comment]
@gouyang Could you see if you could create this again with the current code.

**Comment by gouyang** [comment]
Didn't see the issue with the latest code in the last week.

**Comment by kbaegis** [comment]
buildah version 1.0 (image-spec 1.0.0, runtime-spec 1.0.0)

After COMMIT phase of a repeated build on btrfs host.

**Comment by rhatdan** [comment]
Did you use btrfs back end or overlay?

**Comment by TomSweeneyRedHat** [comment]
@kbaegis do you have an answer to @rhatdan 's question?

**Comment by kbaegis** [comment]
> build on btrfs host.

I haven't seen this recently. 

One thing I have seen, however, is that I can't seem to use buildah on an OSX host. It seems to try to use an aufs driver which I don't think MacOS likes.

**Comment by rhatdan** [comment]
Have you tried to force the driver to vfs?  I have no idea what drivres OSX would support.

**Comment by rhatdan** [comment]
I am going to close this issue as it seems to not happen any longer.
