### ISSUE TITLE
How to inspect an image or container

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#105]
`buildah config` can modify the configuration values which will be saved to an image, how to inspect these values from an image or a container?

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [buildah] Add a way to inspect working containers](https://trello.com/c/g5hLYG4M/501-3-buildah-add-a-way-to-inspect-working-containers)

**Comment by nalind** [comment]
Okay, `buildah inspect` should be available now, per #109.

**Comment by gouyang** [comment]
@nalind `docker inspect` can inspect an image,  do you think `buildah inspect` also need to support inspecting an image?

**Comment by gouyang** [comment]
Figure out how it work `./buildah inspect --type image`
