### ISSUE TITLE
Add buildah tag like Docker tag

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#106]
There is no way to tag an existing image to other name, how about to add a command `buildah tag` to do it?

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) [buildah] Add a way to add names to images in local storage](https://trello.com/c/sbv2ARez/502-3-buildah-add-a-way-to-add-names-to-images-in-local-storage)

**Comment by rhatdan** [comment]
https://github.com/projectatomic/buildah/issues/110 satisfies this issue.
