### ISSUE TITLE
Add buildah mounts to list all mounted container's filesystem

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#107]
After `buildah mount CONTAINER-NAME-OR-ID`, and do some other actions . It's inconvenient to get the mounted container's filesystem again unless to scroll up the screen or  do `buildah mount CONTAINER-NAME-OR-ID` again. Suggest to add `buildah mounts` to list container name and mounted filesystem.

**Comment by rhatdan** [comment]
Should we just add the output to buildah containers?

**Comment by TomSweeneyRedHat** [comment]
I think adding that output to buildah containers would be messy at best.  I'm not a fan of using the mount command as suggested as I wouldn't want to overload that command.  Had we talked about a "buildah inspect" command?  That feels like a better place for this functionality.  FWIW, here's the current output, the mount point is huge and would mess up the output from the buildah container command.

[root@localhost ~]# buildah from ${1:-fedora}
fedora-working-container
[root@localhost ~]# buildah containers
CONTAINER ID IMAGE ID     IMAGE NAME CONTAINER NAME
d049fac3f655 881a38ea176c docker.io/library/hellofromcontainer:latest hellofromcontainer-working-container
10b5c94d56e0 5201f8972ab6 fedora     fedora-working-container
[root@localhost ~]# buildah mount fedora-working-container
/var/lib/containers/storage/overlay2/460c6453bb1b09e4c88576b4f0a0b7de193d3b6b0a8c2e1cf4bf4e7d39ac1abe/merged

**Comment by nalind** [comment]
Could we output the list of mounted containers and their mountpoints when `mount` isn't given a container name?  It'd sort of parallel how the regular `mount` command works (but that only goes so far, since we don't accept a mount point or mount options).

**Comment by rhatdan** [comment]
Since https://github.com/projectatomic/buildah/issues/124 was merged we can close this issue
