### ISSUE TITLE
buildah bud/from --registry usage

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#108]
What's the value of `--registry` should be, the help says `prefix to prepend to the image name in order to pull the image (default: "docker://")`. In cri-o project, look at crio.conf, there is key/value `default_transport = "docker://"`,  `docker://` is named as default_transport.

I think the registry means something like `docker.io` or `registry.access.redhat.com`. I given a test on it, but it failed the test.

1. Don't write the registry in Dockerfile, only use `rhel7/rhel`, it not work.
```
[root@fedora buildah]# ./buildah bud --registry registry.access.redhat.com .
STEP 1: FROM rhel7/rhel
ERRO[0000] error building: error creating build container: error pulling image "rhel7/rhel": error parsing image name "registry.access.redhat.comrhel7/rhel": Invalid image name "registry.access.redhat.comrhel7/rhel", expected colon-separated transport:reference
```

2. Write registry in the Dockerfile, it works.
```
# ./buildah bud .
STEP 1: FROM registry.access.redhat.com/rhel7/rhel
STEP 2: RUN echo "test pull progress" 
test pull progress
````

**Comment by rhatdan** [comment]
@nalind Any comment on this one?

**Comment by rhatdan** [comment]
Since we removed support I am going to close this issue.
