### ISSUE TITLE
Need to support adding signatures when committing or pushing

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#132]
Similar in some ways to #96, we need to be able to add signatures to images when writing them.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat I think could use something like this for OpenShift?

**Comment by TomSweeneyRedHat** [comment]
Closing this as we're tracking in Trello at: https://trello.com/c/CsSZ1z8W/827-buildah-support-adding-signatures-when-committing-or-pushing
