### ISSUE TITLE
Differences between buildah and containers/build?

### ISSUE THREAD

**Issue by cdrage** [projectatomic/buildah#159]
Take this as light criticism, but these are two very similar projects, what's the difference between using `buildah` and `acbuild` (https://github.com/containers/build) (which is also OCI compliant?). Both are written in Go and look to achieve the same goal :1st_place_medal:

**Comment by rhatdan** [comment]
We have not looked at acbuild.  Our goal was to take advantage of containers/storage and containers/image and share content with skopeo and cri-o.  Also to not only support Dockerfile format, but to allow users to simply pull an  image, mount it to a mount point write content into the mount point, and then commit the image.

ctr=($buildah from fedora)
mnt=($buildah mount $ctr)
dnf install --installroot /mnt httpd
buildah commit $ctr

I would be willing to work with others on combining the efforts, but these are core requirements of what we want to build.

We also want to then take this low level tool and make it work well with ansible-container and OpenShift S2I and ImageFactory.
