### ISSUE TITLE
Spurious SEGVs in buildah commit

### ISSUE THREAD

**Issue by edsantiago** [projectatomic/buildah#169]
This is on RHEL7 using devicemapper, so it may be an unsupported configuration.

    # container=$(buildah --storage-driver devicemapper from fedora)
    # while [ \! -s /tmp/buildah-crash.log ]; do buildah --storage-driver devicemapper commit $container containers-storage:myimage >/tmp/buildah-crash.log 2>&1;sleep 2;ls -l /tmp/buildah-crash.log;done
    [may take a while. Or may fail on third attempt.]

See attached logs.

    # uname -a
    Linux esm-rhel7-d12-5 3.10.0-687.el7.x86_64 #1 SMP Mon Jun 26 15:34:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
    # git rev-parse HEAD
    d9a77b38fc705be50bf7ff2fbb98a5bfdf1563ff
    # rpm -qa|egrep 'golang|skopeo'|sort
    golang-1.8.3-1.el7.x86_64
    golang-bin-1.8.3-1.el7.x86_64
    golang-github-cpuguy83-go-md2man-1.0.4-4.el7.x86_64
    golang-src-1.8.3-1.el7.noarch
    skopeo-0.1.20-1.1.gite802625.el7.x86_64
    skopeo-containers-0.1.20-1.1.gite802625.el7.x86_64

[buildah-crash-2.txt](https://github.com/projectatomic/buildah/files/1106678/buildah-crash-2.txt)
[buildah-crash-3.txt](https://github.com/projectatomic/buildah/files/1106679/buildah-crash-3.txt)

**Comment by rhatdan** [comment]
@nalind @rhvgoyal Should we just drop devicemapper support altogether and wait for the lvm plugin?

**Comment by rhvgoyal** [comment]
@rhatdan, lvm support is not here yet. And even when it arrives it will take a while for it to stablize. devicemapper has been around for a while and still being actively used. So without lvm being ready as replacement, I don't think dropping devicemapper is a very good idea.

If there is an issue, I think we should fix that issue instead.

**Comment by TomSweeneyRedHat** [comment]
@edsantiago if you get a space minute or three, can you confirm that this is still an issue?

**Comment by rhatdan** [comment]
@edsantiago Are you still seeing this issue with current buildah?

**Comment by edsantiago** [comment]
I'm really sorry for the delay. I haven't been spending time with buildah. I hope to remedy that.

Right now, with buildah-0.11 and 0.15 on RHEL7.5, my reproducer doesn't work at all:
```
# container=$(buildah --storage-driver devicemapper from fedora)
devmapper: Unknown option overlay.override_kernel_check
devmapper: Unknown option overlay.override_kernel_check
```
Commenting out the `override_kernel_check` entry from `/etc/containers/storage.conf` (from skopeo-containers-0.1.28-1.git0270e56) yields:
```
Error determining manifest MIME type for docker://registry.access.redhat.com/fedora:latest: unknown: Not Found
```
...at which point I choose to enjoy my Sunday, and get back to this during the work week...

**Comment by rhatdan** [comment]
I don't believe we have this issue anylonger.
