### ISSUE TITLE
add support to copying files from container

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/buildah#177]
Hi, I'm working on adding support for buildah in Ansible (Container): https://github.com/ansible/ansible/pull/26170

It seems like we may also need to copy files from container to host or another container. How difficult would it be to implement? Do you think that sufficient workaround could be to mount a directory instead?

**Comment by rhatdan** [comment]
You could simple mount the directory, We are implementing most of the upstream docker cli in kpod, so this might be a solution as well.

kpod copy.

We have buildah copy, which copies into the container.

**Comment by rhatdan** [comment]
mnt=$(builder mount CONTAINERID)
cp $mnt/PATHTOSRCE /PATHTODEST
buildah umount $mnt

**Comment by rhatdan** [comment]
Wrote a quick blog on this.
http://danwalsh.livejournal.com/76656.html

**Comment by TomasTomecek** [comment]
Dan, thanks for your comments. In the meantime I implemented via doing `cat` in the container and piping the output into file on host: https://github.com/ansible/ansible/pull/26170/files#diff-9119cb69870060cdff9c271b8c397222R115
