### ISSUE TITLE
add a way to disable PTY allocation

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/buildah#179]
One of the commands Ansible invokes on target system is `/bin/sh -c '/usr/bin/python && sleep 0'` which is used to determine whether `python` executable is present on the target. Unfortunately, if the pty is allocated, the REPL is invoked which causes the process to fail.

Would it be possible to add an option to disable PTY allocation? I am okay creating the patch myself: unfortunately I haven't figured out the way how it's possible to change the runtime spec.

**Comment by nalind** [comment]
In the `RunOptions` structure that we pass to `builder.Run()`, changing the `Terminal` field from its default of `buildah.DefaultTerminal` to `buildah.WithoutTerminal` should do it.  We'd need to wire that up to a boolean CLI flag or two in `cmd/buildah/run.go`.

**Comment by TomasTomecek** [comment]
@nalind thanks for response; will try to open a PR tomorrow
