### ISSUE TITLE
Use overlay2 as the default storage driver

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#180]
When I start crio daemon, I met an error:

```
"/var/lib/containers/storage" contains several valid graphdrivers: overlay2, overlay; Please cleanup or explicitly choose storage driver (-s <DRIVER>)"
```

By default, there is no `overlay` under `/var/lib/containers/storage`, but `buildah` is using `overlay` as the default storage-driver, so after run some `buildah` commands, I could meet the above error.

Of course I can specify `storage_driver` in crio.conf, but how about change the default value of `--storage-driver` to `overlay2` in `buildah`?

**Comment by rhatdan** [comment]
THis is because the cri-o has not updated to the latest container/storage yet.  We hope to have this done by early next week,

**Comment by gouyang** [comment]
crio is using overlay now.

**Comment by rhatdan** [comment]
Yes we hope to get a new packaged version of CRI-O out soon.
