### ISSUE TITLE
Getting buildah commit docker-formatted images to local docker storage

### ISSUE THREAD

**Issue by clcollins** [projectatomic/buildah#184]
Apologies if I've overlooked something or (more likely) have a shaky understanding of the different formats, transports and storage locations.

Is there a way to get buildah-made, docker-formatted images (ie: buildah commit -f docker $container my_image) from buildah image storage to storage available for use by the docker daemon without pushing to a remote registry?

I am unclear on when to use buildah commit vs. buildah export, and how to move those images to other places.  

I also investigated skopeo as a potential solution, but was unsure how to (or if I could) reference buildah images using the transports that skopeo uses.

Any guidance is appreciated, thanks!

**Comment by rhatdan** [comment]
Does 
`buildah push my_image `

Work?

**Comment by clcollins** [comment]
Hi @rhatdan:

```
buildah push my_image
ERRO[0000] source and destination image IDs must be specified 
```
I would have thought that would work too.  The man page and --help output have destination as an optional parameter (or in brackets anyway).

So I tried a few variants with a destination image.

```
buildah push my_image my_image
ERRO[0000] Invalid image name "my_image", expected colon-separated transport:reference 
```
I'm not clear on how to reference the local docker storage on my laptop in the transport.  I tried a few variations, with different messages:

```
buildah push my_image docker://my_image
Getting image source signatures
ERRO[0023] error pushing image "my_image" to "docker://my_image": error copying layers and metadata: Error checking for blob sha256:d3aeceeb0289bf97c2474366cfcdaf66e29b409d45d6ed91be3335f16915f1b0 at destination: not authorized to read from destination repository library/my_image 
```
```
buildah push my_image docker://localhost/my_image:latest
Getting image source signatures
ERRO[0022] error pushing image "my_image" to "docker://localhost/my_image:latest": error copying layers and metadata: Error checking for blob sha256:d3aeceeb0289bf97c2474366cfcdaf66e29b409d45d6ed91be3335f16915f1b0 at destination: pinging docker registry returned: Get https://localhost/v2/: dial tcp [::1]:443: getsockopt: connection refused 
```
The last makes sense, I guess.  I'm not listening via TCP on my own laptop.  Is there a way to push to the local storage by file, or to the daemon by socket?  Or is it intended to be used via TCP and the Docker REST api?

Am I just using the wrong transport for what I'm trying to do?

Thanks for your help!

**Comment by nalind** [comment]
The `docker://` transport talks to registries.  You should have success using `docker-daemon:image-name:tag` as a destination, though.

**Comment by clcollins** [comment]
@nalind: That worked perfectly!  I had not known the docker-daemon transport existed.  

Thanks for the assistance, all!

**Comment by nalind** [comment]
That's a good point - we don't list it as an example in the buildah-push(1) man page, and there isn't much else describing where we can write images.

**Comment by rhatdan** [comment]
Yes we should add it to the man page.  Also we should add it to help.  I was talking to @14rycole about this point.  BTW Can you do some of this in buildah commit?

**Comment by nalind** [comment]
Yeah, commit can still write to any of the locations to which push can write.
