### ISSUE TITLE
buildah bud file name expansion in Dockerfile fails

### ISSUE THREAD

**Issue by clcollins** [projectatomic/buildah#188]
I ran into an error building an image from Dockerfile with `buildah bud`, when buildah ran across a filename expansion in the file, eg: `ADD dir/* /dest`

I can reproduce it with this example:

```
cat << EOF >> Dockerfile
FROM alpine:latest
ADD test/* /
EOF

mkdir test && touch test/file1 test/file2
```
...running `buildah bud -f Dockerfile .` results in an error:

```
STEP 2: ADD test/* /
ERRO[0001] error building: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:add Args:[test/* /] Flags:[] Attrs:map[] Message:ADD test/* / Original:ADD test/* /}: error reading "/tmp/buildah-test/test/*": stat /tmp/buildah-test/test/*: no such file or directory
```
...where `docker build -f Dockerfile .` succeeds.

Other info:
```
$ buildah --version
buildah version 0.1 (image-spec 1.0.0-rc6-dev, runtime-spec 1.0.0-rc5)
$ docker -v
Docker version 1.12.6, build ae7d637/1.12.6
$ cat /etc/redhat-release
Fedora release 25 (Twenty Five)
```

**Comment by rhatdan** [comment]
@clcollins Could you try this pull request to see if it fixes your issue?

**Comment by clcollins** [comment]
@rhatdan Your pull request works with both the test case above, and with the real-life build I discovered the issue with, using `buildah bud` and a Dockerfile.  Thanks!

**Comment by rhatdan** [comment]
I am close on tests, but the glob tests in the Dockerfile is failing.

**Comment by rhatdan** [comment]
This is fixed upstream and will be in the next release of buildah.
