### ISSUE TITLE
Unclear error message when running any buildah command

### ISSUE THREAD

**Issue by tylerauerbeck** [projectatomic/buildah#193]
I feel this may already be resolved as part of #168 , but need assistance in figuring out what my issue may be in the mean time. I'm attempting to run buildah in a docker container with some assistance from #158 . However unlike the folks there, I'm unable to run any buildah commands at all without receiving the following error:

```
ERRO[0000] driver not supported
driver not supported
```
Is there any flag or debugging I can enable to get further information on this? I'm unable to figure out which driver this may be referencing. I've attached the Dockerfile I'm using for reference.
[Dockerfile.txt](https://github.com/projectatomic/buildah/files/1151986/Dockerfile.txt)

**Comment by TomSweeneyRedHat** [comment]
Can you attach to the container and dig around in journalctl there?  Any info in that?

**Comment by TomSweeneyRedHat** [comment]
FWIW, I tried this on Fedora 26 Beta (really need to upgrade) and it looked like Buildah came up for me.  Please let me know if I misunderstood what you were trying to do.

# cat Dockerfile
FROM fedora:26
RUN dnf -y install make golang bats btrfs-progs-devel device-mapper-devel glib2-devel gpgme-devel libassuan-devel ostree-devel git bzip2 go-md2man runc skopeo-containers
RUN mkdir /root/buildah && git clone https://github.com/projectatomic/buildah /root/buildah/src/github.com/projectatomic/buildah -b auto && cd /root/buildah && export GOPATH=/root/buildah && cd /root/buildah/src/github.com/projectatomic/buildah && make && make install

[root@localhost ~]# docker build -t buildah_container .
Sending build context to Docker daemon 19.18 MB
Step 1/3 : FROM fedora:26
Trying to pull repository registry.fedoraproject.org/fedora ... 
sha256:19466a04bc089fc31fa4ddc4d9d73bc63a5320400f103f1ec0033b149d65f998: Pulling from registry.fedoraproject.org/fedora
ad70fa9aa187: Pull complete 
Digest: sha256:19466a04bc089fc31fa4ddc4d9d73bc63a5320400f103f1ec0033b149d65f998
Status: Downloaded newer image for registry.fedoraproject.org/fedora:26
 ---> 7c100629c0cb
Step 2/3 : RUN dnf -y install make golang bats btrfs-progs-devel device-mapper-devel glib2-devel gpgme-devel libassuan-devel ostree-devel git bzip2 go-md2man runc skopeo-containers
 ---> Running in 6a1391c923f0
Last metadata expiration check: 0:00:01 ago on Mon Jul 17 11:57:37 2017.
Dependencies resolved.
================================================================================
 Package                   Arch   Version                         Repository
                                                                           Size
================================================================================
Installing:
 bats                      noarch 0.4.0-5.20160219git0360811.fc26 fedora   23 k
{Removed a ton of install output for brevity sake}
                                          
  systemd-devel.x86_64 233-6.fc26                                               

Complete!
 ---> a50ba83691a8
Removing intermediate container 6a1391c923f0
Step 3/3 : RUN mkdir /root/buildah && git clone https://github.com/projectatomic/buildah /root/buildah/src/github.com/projectatomic/buildah -b auto && cd /root/buildah && export GOPATH=/root/buildah && cd /root/buildah/src/github.com/projectatomic/buildah && make && make install
 ---> Running in 128a40e85799
Cloning into '/root/buildah/src/github.com/projectatomic/buildah'...
go build -ldflags '-X main.gitCommit=98ca810 -X main.buildInfo=1500292757' -o buildah -tags "  " ./cmd/buildah
go build -ldflags '-X main.gitCommit=98ca810 -X main.buildInfo=1500292757' -o imgtype -tags "  " ./tests/imgtype.go
make -C docs
make[1]: Entering directory '/root/buildah/src/github.com/projectatomic/buildah/docs'
go-md2man -in buildah.md -out buildah.1
go-md2man -in buildah-commit.md -out buildah-commit.1
go-md2man -in buildah-export.md -out buildah-export.1
go-md2man -in buildah-config.md -out buildah-config.1
go-md2man -in buildah-images.md -out buildah-images.1
go-md2man -in buildah-umount.md -out buildah-umount.1
go-md2man -in buildah-rmi.md -out buildah-rmi.1
go-md2man -in buildah-from.md -out buildah-from.1
go-md2man -in buildah-copy.md -out buildah-copy.1
go-md2man -in buildah-push.md -out buildah-push.1
go-md2man -in buildah-bud.md -out buildah-bud.1
go-md2man -in buildah-mount.md -out buildah-mount.1
go-md2man -in buildah-run.md -out buildah-run.1
go-md2man -in buildah-inspect.md -out buildah-inspect.1
go-md2man -in buildah-tag.md -out buildah-tag.1
go-md2man -in buildah-rm.md -out buildah-rm.1
go-md2man -in buildah-add.md -out buildah-add.1
go-md2man -in buildah-version.md -out buildah-version.1
go-md2man -in buildah-containers.md -out buildah-containers.1
make[1]: Leaving directory '/root/buildah/src/github.com/projectatomic/buildah/docs'
install -D -m0755 buildah //usr/local/bin/buildah
make -C docs install
make[1]: Entering directory '/root/buildah/src/github.com/projectatomic/buildah/docs'
install -d //usr/local/share/man/man1
install -m 0644 buildah*.1 //usr/local/share/man/man1
make[1]: Leaving directory '/root/buildah/src/github.com/projectatomic/buildah/docs'
 ---> 94cc134f53c2
Removing intermediate container 128a40e85799
Successfully built 94cc134f53c2

[root@localhost ~]# docker images
REPOSITORY                          TAG                 IMAGE ID            CREATED             SIZE
buildah_container                   latest              94cc134f53c2        8 minutes ago       889 MB
registry.fedoraproject.org/fedora   26                  7c100629c0cb        11 days ago         231 MB
nginx_small                         latest              39d746c711d4        2 weeks ago         527 MB
registry.fedoraproject.org/fedora   latest              e27989d07619        2 weeks ago         232 MB

[root@localhost ~]# docker run -d -t --name=my_buildah_container buildah_container:latest /bin/bash
f544df573cd5c17547451eff87e1c00a753685d703e55e2894fb671d442b0807

**Comment by rhatdan** [comment]
Do you have an /etc/containers/storage.conf installed?  Did you volume mount in /var/lib/containers into the container?

**Comment by rhatdan** [comment]
@tylerauerbeck Do you have an /etc/containers/storage.conf installed? Did you volume mount in /var/lib/containers into the container?

**Comment by gouyang** [comment]
I could see this error on RHEL7.3,  the binary was built from source.
Run any buildah commands will get this error. 
No /var/lib/containers mounted, with or without /etc/containers/storage.conf got same result.

```
# ./buildah --debug images
DEBU[0000] [graphdriver] trying provided driver "overlay" 
DEBU[0000] [graphdriver] trying provided driver "overlay" 
ERRO[0000] driver not supported
driver not supported    
```

**Comment by rhatdan** [comment]
Try to change the storage.conf driver to devicemapper,  This is probably complaining about support of overlay until RHEL7.4.

**Comment by gouyang** [comment]
Tested that if it's `devicemapper` in /etc/containers/storage.conf on RHEL7.3, the problem is gone.

**Comment by rhatdan** [comment]
If you could get ahold of the RHEL7.4 kernel overlay should work. If not we have a bug. I think the containers/storage is checking for a certain flag in the kernel to see if SELinux and Overlay will work together and that is what is blocking overlay.

**Comment by tylerauerbeck** [comment]
@rhatdan @gouyang @TomSweeneyRedHat Hey everybody -- sorry life got a little busy and I had to come back around to this one, so now I'm bringing this one back from the dead. I'm now testing this in the following manner.

I've got my local vm: CentOS 7.4 (CentOS Linux release 7.4.1708 (Core))-- freshly installed with docker-ce 17.09

Before running anything else, I have verified that it is using the overlay storage driver. There is no storage.conf that is in place (not that I can find in the system or any of the expected locations)

So first I run: `docker run -d -t --name=buildah buildah:latest` . Without doing any binds and not adding any privileged or additional cap-adds -- we crash and burn with the error:

`ERRO[0001] error building: error creating build container: error pulling image "docker.io/library/alpine:latest": Error writing blob: ApplyLayer exit status 1 stdout:  stderr: Error creating mount namespace before pivot: operation not permitted`

After scoping out some of the new suggestions that were made in #158 -- I attempted to mount /var/lib/containers. So I run the following : `docker run -d -t -v /var/lib/containers:/var/lib/containers --name=buildah buildah:latest`, which results in the same error as above. 

I also try running `docker run -d -t -v /var/lib/containers:/var/lib/containers:Z --name=buildah buildah:latest`. This also isn't successful, but with a slightly different error

`ERRO[0000] error building: error creating build container: error creating container: Error processing tar file(exit status 1): Error creating mount namespace before pivot: operation not permitted
`
From there I moved on and then mounted /var/lib/containers and then used --cap-add=SYS_ADMIN by running the following : `docker run -d -t --cap-add=SYS_ADMIN -v /var/lib/containers:/var/lib/containers:Z --name=buildah buildah:latest` . We have success! But I want to make sure I'm not just opening up access to everything for no reason. So I tried rolling this back a bit. 

I then run this using just --cap-add=SYS_ADMIN. Again, success. Obviously this time though none of what I build in the container actually is rolled back down to the VM filesystem (at least from what I'm seeing).

So the question now is: is there a benefit of not mounting /var/lib/containers into the container? And what are the risks of running this with SYS_ADMIN versus making it a privileged container?

What I'm trying to accomplish (like I assume many others are) is to just have a container build docker images and then push them to a registry. I'd like to do that while exposing as little privilege to these containers as possible so I'd like to understand what is being exposed by going down this path.

Again, sorry for the delay and silence. Let me know if there's anything else I can provide.

**Comment by rhatdan** [comment]
Currently SYS_ADMIN Is required.  Which lowers your security a little, but you are still protected by SELinux. to some extent.   I have not done a full examination of what you could attack using SYS_ADMIN privs and what SELinux would continue to block.  One of the biggest things that you can do with SYS_ADMIN is to be able to mount, (Which is why buildah requires it).  You can also create additional namespaces.  If I was going to attack the host I would first try to remount the kernel file systems, read/write.  And mount the SELinux file system.

Bottom line this setup would be more secure then using the docker socket directly, since the docker socket allows breakout without any logging support.  If a determined hacker was attempting to break out of a container with SYS_ADMIN privs, the SELinux logs would go crazy.

As far as mounting /var/lib/containers into the the container, this would allow prevent you from running overlay on overlay, which could have issues.  You probably could run your entire container as --read-only which would give you some additional security.  

docker run --read-only -d -t -v /var/lib/containers:/var/lib/containers:Z --name=buildah buildah:latest

Note you might have to add  --tmpfs /run.

**Comment by rhatdan** [comment]
@rhvgoyal @nalind WDYT?

**Comment by rhatdan** [comment]
Ok this chain seems to have died.  We will continue to work on getting buildah to run within usernamespace to see that we can do a unprivileged build.

**Comment by tylerauerbeck** [comment]
thanks @rhatdan I'll keep an eye out and will continue to test this out once that becomes available
