### ISSUE TITLE
Needs to support creating multiple layers

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#2]
Right now, we only generate a single additional layer that holds all of the difference between what we're doing and the source image.  We're not strictly limited to doing that, though, and it'd be useful to be able to break up a series of changes that are being made into multiple layers, so that the changes could at least conceivably be shared with other images that build off of the same base image.

**Comment by rhatdan** [comment]
Now that we have buildah commit, is this enough?

**Comment by nalind** [comment]
That doesn't really satisfy the case - if we commit a working container more than once, the layers we create for the new images each contain the full set of changes relative to the image that we started with, not the previous commit.

**Comment by jawnsy** [comment]
What if we do:

`buildah commit` (returns commit id `abcd1234`)

and then

`buildah from abcd1234`

Then we're a lot more explicit about the layers we're creating? It would also allow me to create a single unnamed image to re-use as the base image for two new images, for example (in the same way that Docker would reuse its internal cache subject to ??? magic rules of some sort).

**Comment by nalind** [comment]
Yes, that would effectively be what we want, but the overhead of dumping out the layers can be severe, particularly if it has to be done N times.  Though you've reminded me that this would be more useful for something like the _build-using-dockerfile_ command than it would be in other cases.

**Comment by rhatdan** [comment]
We want to add a --rm flag, 
image=$(buildah commit --rm abc123 [foobar]) # This will attempt to umount the container image if it was mounted, if it succeeds in saving the image but fails in removing the container, it should just report the failure with a hint to the user what to do.

Next step would be 
ctr=$(buildah from $image)

**Comment by rhatdan** [comment]
Eventually need a way to easily add a layer

buildah layer?

**Comment by rhatdan** [comment]
@nalind What do you think of the comment to add the --rm flag
Should we output the image name in such a way that a new container could be created with a buildah from?
image=$(buildah commit --rm abc123 [foobar]) 
 ctr=$(buildah from $image)

**Comment by TomSweeneyRedHat** [comment]
Closing this issue as it's been moved to Trello at:  https://trello.com/c/oOKhcxqX
