### ISSUE TITLE
How to pronounce `buildah`?

### ISSUE THREAD

**Issue by caruccio** [projectatomic/buildah#206]
Not being a native english speaker, I'm struggling to explain people the origin of the name of this project. It would be nice to have an .wav|.mp3|.ogg audio file with the correct pronounce for `buildah`. Event better if coming from @rhatdan itself, the inspiration of it.

**Comment by TomSweeneyRedHat** [comment]
Excellent suggestion, hopefully we'll be able to twist Dan's arm to do this.  FWIW, I'd say it's pronounced like "bill-dah".  It's a very New England pronunciation, especially inside of the route 128/95 highway that's circles Boston, MA about 15 miles from the city.

**Comment by caruccio** [comment]
You can always threaten him with `setenforce 0 selinux` ;)

**Comment by rhatdan** [comment]
I will put something together on Monday.

**Comment by rhatdan** [comment]
https://www.youtube.com/embed/YVk5NgSiUw8
