### ISSUE TITLE
driver not supported

### ISSUE THREAD

**Issue by rothgar** [projectatomic/buildah#213]
I compiled buildah on fedora 26 and brought the binary over to rhel 7.3.

I had to install ostree on rhel but after that I get the the following error message

```
./buildah containers                                                                                                                                                                           
ERRO[0000] driver not supported                                                                                                                                                                                      
driver not supported
```
I'm assuming it's because I'm using overlay storage driver. Here's the relevant docker info

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 222
Server Version: 17.05.0-ce
Storage Driver: overlay
 Backing Filesystem: extfs
 Supports d_type: true
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-514.16.1.el7.x86_64
...
```

Is there a list of supported drivers or similar `buildah info` command?

**Comment by rothgar** [comment]
My theory was wrong. I tried again on a system with devicemapper and get the same error.

```
$ docker info
Containers: 0                                                                                                                                                                                                        
 Running: 0
 Paused: 0
 Stopped: 0
Images: 1
Server Version: 1.12.0
Storage Driver: devicemapper
 Pool Name: docker-253:0-3425945-pool
 Pool Blocksize: 65.54 kB
 Base Device Size: 10.74 GB
 Backing Filesystem: xfs
 Data file: /dev/loop0
 Metadata file: /dev/loop1
 Data Space Used: 232.8 MB
 Data Space Total: 107.4 GB
 Data Space Available: 65.91 GB
 Metadata Space Used: 679.9 kB
 Metadata Space Total: 2.147 GB
 Metadata Space Available: 2.147 GB
 Thin Pool Minimum Free Space: 10.74 GB
 Udev Sync Supported: true
 Deferred Removal Enabled: false
 Deferred Deletion Enabled: false
 Deferred Deleted Device Count: 0
 Data loop file: /var/lib/docker/devicemapper/devicemapper/data
 WARNING: Usage of loopback devices is strongly discouraged for production use. Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
 Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
 Library Version: 1.02.135-RHEL7 (2016-11-16)
Logging Driver: journald
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: null host bridge overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: seccomp
Kernel Version: 3.10.0-514.26.2.el7.x86_64
```

**Comment by rhatdan** [comment]
Why not compile and build it on RHEL?

**Comment by nalind** [comment]
I'm not sure what correlation there is between the configuration dockerd is using and what buildah's using.  Can you run `buildah --debug containers` to see what it's doing?  Do you have a `/etc/containers/storage.conf` file?

**Comment by rothgar** [comment]
@rhatdan I get errors when building on RHEL which I didn't care to debug. I thought the go binary would be more or less portable but it appears it still needs packages and configuration on the host.

@nalind 
```
sudo ./buildah --debug containers                                
DEBU[0000] [graphdriver] trying provided driver "overlay"                                                                                             
DEBU[0000] [graphdriver] trying provided driver "overlay"                                                                                                           
ERRO[0000] driver not supported                                                      
driver not supported 
```
I do not have a /etc/containers/storage.conf file

**Comment by gouyang** [comment]
Tested that if it's `devicemapper` in /etc/containers/storage.conf on RHEL7.3, the problem is gone.

**Comment by pineshshah** [comment]
Not sure if this issue got resolved.
Since i have setup buildah on Centos.
`$buildah version`
`>Version:       0.3
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    b7e9966
Built:         Wed Jul 26 05:44:10 2017
OS/Arch:       linux/amd64`

I am still getting the driver not supported

**Comment by rhatdan** [comment]
Adding devicemapper to /etc/containers/storage.conf should work.  You need a 7.4 kernel for the overlay driver to work.  There is a check in the containers/storage to make sure the kernel supports SELinux and Overlay, which is what I think you are hitting.

**Comment by pineshshah** [comment]
Thanks @rhatdan I had tried adding the /etc/containers/storage.conf with `STORAGE_DRIVER="devicemapper"` although it didn't work. So i just simply exported `STORAGE_DRIVER="devicemapper"` in the console and then finally it started working.

**Comment by rothgar** [comment]
I was able to switch to devicemapper and add this to /etc/containers/storage.conf
```
[storage]
driver = "devicemapper"
runroot = "/var/run/containers/storage"
graphroot = "/var/lib/containers/storage"
```
I also switched my docker engine to use devicemapper. I no longer get the error when running `buildah images`.

I also verified I could run `buildah from centos` and `buildah images` to see the image in the local storage. Thanks for the help.

**Comment by rothgar** [comment]
I just realized the buildah storage and docker storage are completely separate configurations so there's no reason for me to change my docker storage driver.

Is there a place in my home directory I can store the storage.conf file so I don't need to rely in it being in /etc/containers?

**Comment by rhatdan** [comment]
Nope, we don't do that now.  But we should not change storage.conf going forward.  Newer versions of buildah should come with that file from the rpm.

**Comment by rothgar** [comment]
Needing to install an rpm defeats the purpose of having a statically compiled binary. Many of the other tools I use live in my ~/bin directory and are configured from ~/.config
Packaging `buildah` in a container defeats the use case (for me) because I want to be able to build containers without needing to prepare a system (give me a portable binary) and without root (don't require SYS_ADMIN)
Is there a reason building a tar + json with `buildah` can't meet those requirements?

**Comment by rhatdan** [comment]
buildah right now does mount, which requires SYS_ADMIN.  We are getting closer, and you could create a conformant OCI or DOcker image with just tar and a json. 
We potentially want to look into using rpm-ostree backend which will actually handle UID!= your uid for rpm content.

Changing to  use a local config would be the easy part.
