### ISSUE TITLE
CHANGELOG.md doesn't exist and releases are not tagged

### ISSUE THREAD

**Issue by it-praktyk** [projectatomic/buildah#214]
Few days ago I saw [twit](https://twitter.com/fedora/status/887747619363078144) by [Fedora Project](https://twitter.com/fedora) what directs to the [Dan Walsh's Blog article](http://danwalsh.livejournal.com/76837.html) 'New version of buildah 0.2 released to Fedora.'.

Can you start providing change log for Buildah (e.g. as the CHANGELOG.md file) and start tagging releases or even releasing them on GitHub too?

Thank you in advance.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/buildah/pull/273
A little slow but @it-praktyk PTAL

**Comment by it-praktyk** [comment]
OK, I'll look on that under a weekend.

**Comment by it-praktyk** [comment]
Thank you for the initial version of the CHANGELOG.md file.

Can you consider changing the way how a changelog is organized? 

The best what I know is the [CHANGELOG.md for Vagrant](https://github.com/hashicorp/vagrant/blob/master/CHANGELOG.md).

**Comment by rhatdan** [comment]
Please open a pull request to make the changes

**Comment by TomSweeneyRedHat** [comment]
@it-praktyk this issue has been open for a while and we've a CHANGELOG.md.  If you'd like to see a different format, please open up a PR.  We'd love the contribution!
