### ISSUE TITLE
How to get container ID

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#215]
I'm writing some testing cases and I want to specify image ID and container ID in some case. 
There is no document about how to get one image ID or container ID, I've tried below and It works for image but not for container. Any suggestion?

```
[root@fedora buildah]# ./buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
76cca0563a1f         docker.io/library/nginx:latest                           Jul 26, 2017 07:47     102.5 MB
9378a3010a43         docker.io/library/fedora:latest                          Jul 26, 2017 07:53     219.9 MB
[root@fedora buildah]# ./buildah images -q nginx
76cca0563a1f28f2b3fd56c63462346f39827b4f539a16d27992f04eaf5c608f
[root@fedora buildah]# ./buildah containers
CONTAINER ID  BUILDER  IMAGE ID     IMAGE NAME                       CONTAINER NAME
490dedf14215     *     76cca0563a1f docker.io/library/nginx:latest   nginx-working-container
2a92e7e8625f     *     76cca0563a1f docker.io/library/nginx:latest   nginx-working-container-2
8a6906f39ce6     *     9378a3010a43 docker.io/library/fedora:latest  fedora-working-container
[root@fedora buildah]# ./buildah containers -q fedora
490dedf14215d42a376a1892212dd5985a4cf97baf9916f483b8bc52a7ef8637
2a92e7e8625f35e9722b93bb88168cc88e6d91d1e9aafe0ecc04fe4b37fabd0d
8a6906f39ce6fc0930f00d09a0df27e205a790e77552b5893a0680c8a879ada8
```

**Comment by TomSweeneyRedHat** [comment]
Do you create the container yourself?  If so, you could do this:
ctrid=($buildah from fedora)

and then the ctrid variable could be used like:

buildah mount $ctrid

Note: the value in $ctrid would be the name of the container, not the id.  You can use either the id or the name of the container for buildah commands.

**Comment by TomSweeneyRedHat** [comment]
Just a note, my last comment had a typo that's since been corrected for the assignment command.

**Comment by rhatdan** [comment]
The images behavior is not documented.  Not sure why it works.
The easist way to do what you want would be 

buildah containers | grep fedora | awk '{ print $1 }'

Not sure if we would want to add the new behaviour.

**Comment by gouyang** [comment]
The method works for images maybe it's due to images has implemented the filter, just like docker images does.

I will use the pipelines to get the containers ID as suggested above. Close the issue.
