### ISSUE TITLE
buildah error with fedora-minimal image

### ISSUE THREAD

**Issue by jberkus** [projectatomic/buildah#228]
On a new spin-up of Fedora 26:
[root@ip-172-31-23-250 ~]# buildah --version
buildah version 0.1 (image-spec 1.0.0-rc5, runtime-spec 1.0.0-rc5)

[root@ip-172-31-23-250 ~]# cnt=$(buildah from registry.fedoraproject.org/fedora-minimal)
Getting image source signatures
Copying blob sha256:899ab03d9a13ff4a8f69b49c58a8839302a7cd0bdac89511c53576c268171749
 40.87 MiB / 40.87 MiB [=======================================================]
Copying config sha256:15bc1f81701b0f19cacf67b361fe8be3b71b2dac850c1a20b4cd5764c3c788f3
 0 B / 1.20 KiB [--------------------------------------------------------------]
Writing manifest to image destination
Storing signatures
[root@ip-172-31-23-250 ~]# $mountpoint=$(buildah mount $cnt)
-bash: =/var/lib/containers/storage/overlay/479125f1ad897b29ef794ae9142bf11851f5c5b01913e79bbfa0b47c6d933651/merged: No such file or directory

**Comment by gouyang** [comment]
> root@ip-172-31-23-250 ~]# $mountpoint=$(buildah mount $cnt)

You need to remove `$` before `mountpoint`.

**Comment by rhatdan** [comment]
Bug in your script...

**Comment by jberkus** [comment]
Feh.
