### ISSUE TITLE
implement command to check size of containers

### ISSUE THREAD

**Issue by jberkus** [projectatomic/buildah#232]
One of the reasons to use buildah is to make smaller containers.  However, we currently don't have a command in buildah to show the size of the container image.  Adding one would help us promote buildah as a way to create smaller containers.

**Comment by rhatdan** [comment]
SHould this just be a field in `buildah images`

**Comment by ripcurld0** [comment]
@jberkus unless you didn't commit the current container, you can't tell its size.
Thus to see the size of the containers you have to do `buildah commit CONTAINER IMAGE` and then `buildah images | grep IMAGE`.

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this as I believe #ripculd0 is right, the 'buildah images' command now shows the image size as of the merge of #155.    Example output below.  @jberkus if this doesn't address your concern, please reopen this issue.

```
# buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
b4b7b5a0bcb7         registry.fedoraproject.org/f26/httpd:latest              Sep 21, 2017 20:16     7.499 KB
4a42f64743f1         registry.fedoraproject.org/fedora-minimal:latest         Nov 10, 2017 12:14     1.785 KB
b908b128a5f6         docker.io/library/alpine:latest                          Dec 1, 2017 18:48      3.954 MB
```

**Comment by jberkus** [comment]
LGTM, thanks.
