### ISSUE TITLE
Buildah does not create config for containers

### ISSUE THREAD

**Issue by 14rcole** [projectatomic/buildah#239]
When buildah loads a container, it does not create a config.json file in $ROOT/[driver]-containers/[container-id]/userdata.  cri-o and kpod use this file to load containers into the container store

**Comment by rhatdan** [comment]
@nalind @mrunalp The question here is how do we get kpod/crio and buildah to potentially share containers.  Do we create a config.json with some defaults for buildah?

**Comment by nalind** [comment]
We don't maintain a bundle for `runc`, since we'd also need to regenerate it whenever `buildah config` was run.  Instead, we just generate one in a temporary directory every time we need to run `runc`.

**Comment by rhatdan** [comment]
So should kpod realize this and treat this as a container without a runc config?

**Comment by 14rcole** [comment]
Alternatively, is there a way to get the path to the temporary buildah directory from the buildah.json?  Also, where are the temporary directories?  I have two buildah containers running on my machine but I can't seem to find the temporary directories associated with them

**Comment by nalind** [comment]
The container's `BundlePath()` method should return the directory where the file is located, at least while it's running.

**Comment by rhatdan** [comment]
Will that work for kpod/crio containers as well?

**Comment by nalind** [comment]
To clarify, `BundlePath()` is a method of `src/github.com/kubernetes-incubator/cri-o/oci.Container`.

**Comment by 14rcole** [comment]
If the config.json needs to be accessed before the oci Container is created, there a way to determine the bundle path?

**Comment by rhatdan** [comment]
@14rcole Don't remember what this was for.  Did you want this functionality so that 
buildah inspect $CTRID 
would work?  Or does this cause issues with kpod ps and kpod inspect?

**Comment by 14rcole** [comment]
This caused issues with kpod ps and kpod inspect.  Kpod can't inspect running buildah containers because they don't contain that file with some of the necessary information.

**Comment by rhatdan** [comment]
@baude PTAL

**Comment by TomSweeneyRedHat** [comment]
Closing this as we've  a Trello card to make Buildah/Podman play nicely together which includes listing.  https://trello.com/c/0eUqT0uG
