### ISSUE TITLE
[ENH] Add support for multistaged Dockerfiles

### ISSUE THREAD

**Issue by paoloantinori** [projectatomic/buildah#242]
https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by ripcurld0** [comment]
@rhatdan @TomSweeneyRedHat should we support this in `buildah bud`?

**Comment by rhatdan** [comment]
Yes, we plan to add this feature in the future.
@nalind Correct?

**Comment by nalind** [comment]
@rhatdan Yup.  It'll take some work in the imagebuilder library, which we use to "drive" the bud command, first.

**Comment by TomSweeneyRedHat** [comment]
Closing as this is a duplicate of #440.
