### ISSUE TITLE
Define default directory for certificates

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#246]
The current certificate work does not have a default directory.  Determine if one can/should be specified and then document it if so.

**Comment by TomSweeneyRedHat** [comment]
PR in progress at https://github.com/containers/image/pull/388

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 given https://github.com/containers/image/pull/411 can we close this issue?

**Comment by TomSweeneyRedHat** [comment]
I think we may need some changes to doc/man pages in Buildah before closing though.

**Comment by umohnani8** [comment]
No not yet, I need to vendor in containers/image and update the docs.
