### ISSUE TITLE
buildah can't push a buildah built image to a docker registry 

### ISSUE THREAD

**Issue by ipbabble** [projectatomic/buildah#249]
So I performed the first-new-image how-to described in the Atomic Buildah pages. I wanted to be able to do a demo where I do not have docker installed at all. So just buildah from and then make some changes do a buildah commit and then do a skopeo copy or buildah push to a local registry. 

I also had to pull down a docker registry container from docker hub and run it using buildah run. So I had a running docker registry.

When I tried skopeo copy or buildah push to the localhost:5000 based registry it pushed back with a n error checking the blob. Looking at the docker registry output it said that the blob was unknown to registry etc. It's reaching the registry but can't push the image in.  I tried tagging with localhost:5000 like you have to do with docker but the push still didn't work.

I then installed docker and made sure my docker registry (run from buildah) was actually working. It was: 1) I docker pulled fedora and then tagged and pushed that to the registry and it was successful. 2) I docker pushed my first-new-image to docker-daemon:first-new-image:latest. I ran docker images and saw it in there. I then I tagged and pushed the image to localhost:5000 and it was successful.

So it's just buildah push and skopeo copy that are not working correctly. Is there a missing step? perhaps some tagging semanitcs I need to perform?

Or is this a bug?

**Comment by TomSweeneyRedHat** [comment]
The fix for this is part of https://github.com/projectatomic/buildah/pull/187.  We'll keep this open until that submit goes in and we can verify.  However this is a known issue at the moment.

**Comment by TomSweeneyRedHat** [comment]
Actually it looks like it was an issue with tls-verify that was causing the problem.  Testing shows that PR #250 has fixed the problem.

**Comment by TomSweeneyRedHat** [comment]
Fixed by #250, closing
