### ISSUE TITLE
If creds not passed in with values, use cached logins

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#253]
For the buildah commands such as push, from and commit that have a creds param for the username:password to the registry, if the creds are not provided on the command line, then use creds from either docker or kpod if avaliable.  kpod will be referenced first.

**Comment by TomSweeneyRedHat** [comment]
@umohnani8 fixed this a little before the new year.  Buildah now uses either credentials from 'podman login' or 'docker login'.  It looks for the credentials in that order.  Closing this issue as I was just able to successfully test it.

**Comment by devurandom** [comment]
In case anyone else stumbles upon this: This needs libpod / podman version 1.1.2 to work. Version 1.0.1 seems to have a broken `podman login` that is at least not interoperable with `buildah push`.
