### ISSUE TITLE
Commit has misleading error when creds are required but not supplied

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#254]
Guohua Ouyang reports the below.  He used a private repository and neglected to include the creds command and appropriate un/pwd.  He received a 401 error and might better have been specified as "authentication failed" or some such.

[root@fedora tasks]# buildah commit nginx docker://docker.io/gouyang/nginx
Getting image source signatures
Skipping fetch of repeat blob sha256:ee1a8002360e897670d7edcc6bfde440f064aa014793e7e7a5dc049a01459299
Skipping fetch of repeat blob sha256:12c9ee9bfbc78f3c69092d8aed395fc85db739c90fb8f128c7896c1a03102fdb
Skipping fetch of repeat blob sha256:8481764ad3d61d907eceeaad333bb20b0da6c28c4420e6cfc712aee24f82b5ae
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
 0 B / 32 B [------------------------------------------------------------------]
ERRO[0023] error committing container "nginx" to "docker://docker.io/gouyang/nginx": error copying layers and metadata: Error writing blob: Error initiating layer upload to /v2/gouyang/nginx/blobs/uploads/, status 401

[root@fedora tasks]# buildah commit --creds gouyang:xxxxxx nginx docker://docker.io/gouyang/nginx
Getting image source signatures
Skipping fetch of repeat blob sha256:ee1a8002360e897670d7edcc6bfde440f064aa014793e7e7a5dc049a01459299
Skipping fetch of repeat blob sha256:12c9ee9bfbc78f3c69092d8aed395fc85db739c90fb8f128c7896c1a03102fdb
Skipping fetch of repeat blob sha256:8481764ad3d61d907eceeaad333bb20b0da6c28c4420e6cfc712aee24f82b5ae
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
 32 B / 32 B [=================================================================]
Copying config sha256:c47d98715367c9037b1aedd237e2ffe4c3b909864761c002951a16aece749f89
 4.87 KiB / 4.87 KiB [=========================================================]
Writing manifest to image destination
Storing signatures

**Comment by ripcurld0** [comment]
calling #dibs

**Comment by rhatdan** [comment]
Its yours.

**Comment by TomSweeneyRedHat** [comment]
Tried to assign this to ripculd0, but he's not showing on the list.  Did my whitelist not take this morning or do we need to do something else to get him on the list of potential assignees?

**Comment by rhatdan** [comment]
Did you do that on this Repo?

**Comment by TomSweeneyRedHat** [comment]
I did the whitelist on his true/false combined commit earlier this morn.

**Comment by ripcurld0** [comment]
Should we merge https://github.com/containers/image/pull/390?
If not I can solve it in a different way.

@TomSweeneyRedHat @rhatdan what do you say?

**Comment by rhatdan** [comment]
Lets get 390 merged.

**Comment by ripcurld0** [comment]
Closing.
#385 and #393 were merged and are solving this problem.

```
# buildah commit nginx docker://docker.io/gouyang/nginx
Getting image source signatures
Copying blob sha256:e7bb522d92ff6d4e5b2087409b0fc783c2e3b06acf87bee739ee47d90bf02e96
 0 B / 21.44 MiB [----------------------------------------------------------] 1s
denied: requested access to the resource is denied
unauthorized: authentication required
```
