### ISSUE TITLE
buildah commit --creds username, should prompt for password with no echo.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/buildah#256]
It was suggested yesterday by @TheSteve0

```
buildah push --creds username foobar docker:dan/foobar
Password:
```
@TomSweeneyRedHat @nalind WDYT?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan sounds reasonable to me.  I'll need to dig a bit to figure out how to pull that off, but should be doable.  I would suggest though that if we do this for Buildah, we also change skopeo and kpod to have similar functionality.

**Comment by rhatdan** [comment]
Sounds reasonable to me.

**Comment by rhatdan** [comment]
@runcom @mitrmac WDYT

The only potential issue would be is it ever legal to have a Username without a password.

**Comment by runcom** [comment]
> The only potential issue would be is it ever legal to have a Username without a password.

I believe for token based login (krb maybe?) we left the possibility to give just an username

**Comment by runcom** [comment]
In skopeo, for instance, we allow `--creds USERNAME[:PASSWORD]` for the above reason https://github.com/projectatomic/skopeo/blob/master/cmd/skopeo/copy.go#L94

**Comment by rhatdan** [comment]
Would the tool know that it was supposed to use kerberos before prompting for the password?

**Comment by runcom** [comment]
> Would the tool know that it was supposed to use kerberos before prompting for the password?

nope, you just leave password empty (krb is just an example, it's not implemented in docker/skopeo/or anything else right now)

**Comment by rhatdan** [comment]
OK, this would be a cool feature to add.  I would love to get kerberos support into containers/image...

Potential options would be to add a flag to prompt for password `--password`, or default to prompting if the user did not specify password, which could be overriden by typing
```
--creds dwalsh:
```
(Indicates no password)
```
--creds dwalsh
Password:
```

Usually in the kerberos case the tool would do some kind of negotiation with the remote end to figure out the type of authentication wanted/supported.  Using kerberos/ssh public key would be the two I would want to implement.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @umohnani8 has done this in her kpod login code, can we just grab it from there and use it

**Comment by TomSweeneyRedHat** [comment]
Yep, saw that fly through.  Need to bubble this up higher.

**Comment by TomSweeneyRedHat** [comment]
Closing this issue and have created a trello card for the kerberos thought.
