### ISSUE TITLE
Buildah build breaking due to Logrus API change

### ISSUE THREAD

**Issue by Silvanoc** [projectatomic/buildah#257]
Buildah cannot be built because the Logrus API has been changed with [commit e66f229](https://github.com/sirupsen/logrus/pull/604/commits/e66f22976feaed4e0a6ab43bc2b9226be8b0b979) (merged July 28th). That change removed "IsTerminal", being used in [line 197 of run.go](https://github.com/projectatomic/buildah/blob/9327431e97084da0b0d7dae42e54ad438496e234/run.go#L197).

I'm wondering how Travis-CI could build successfully a couple of days ago... Any dependencies caching going on? If so, then the caches probably have a version of Logrus API prior to July 28th.

**Comment by Silvanoc** [comment]
Using a logrus commit previous to the API change works like a charm.

**Comment by TomSweeneyRedHat** [comment]
@Silvanoc Thanks for the heads up.  Can you tell me what variant of Linux you were trying to build Buildah on or had you tried doing a PR and Travis was not happy?

**Comment by rhatdan** [comment]
We are having a hard time updating buildah to the latest Logrus because of some of the packages we vendor in. But this is just one of the issues that would need to be fixed.
@nalind Has some pull requests out to fix the vendoring issues.

I opened this WIP a while back.
https://github.com/projectatomic/buildah/pull/237

**Comment by Silvanoc** [comment]
I've been just trying to build the [current master (commit 9327431)](https://github.com/projectatomic/buildah/commit/9327431e97084da0b0d7dae42e54ad438496e234) locally.

After having a look at #237 I have to agree with @rhatdan that this is probably just one of the vendoring issues.

**Comment by rhatdan** [comment]
Logrus finally vendored.
