### ISSUE TITLE
"target os mismatch with current os linux" on Debian with latest runc

### ISSUE THREAD

**Issue by Silvanoc** [projectatomic/buildah#258]
I'm getting the "target os mismatch with current os linux" error message when trying to run "build-in-docker".

I've already seen issues #205 and #220 and ensured that none of them apply.

Issue #205 doesn't apply because I'm running buildah on Debian Stretch (9).

Issue #220 doesn't apply because I've tried with a couple of pretty new runc versions: 1.0.0rc3 built from code, 1.0.0rc4 downloaded as a binary from the releases, 1.0.0rc4 built from code of [current runc master](https://github.com/opencontainers/runc/commit/aea4f21eec795d9f5b7c7d514f568c08d58b8e58) (commit aea4f21).

Or am I using a too new version of runc?

BTW, what is being called release 1.0.0 in Fedora 26? There is no release 1.0.0 at the time of writing, only release candidates...

**Comment by rhatdan** [comment]
You need  a newer version of RUNC At least rc5.

runc --version
runc version spec: 1.0.0-rc5

koji latest-pkg f26-updates runc
Build                                     Tag                   Built by
----------------------------------------  --------------------  ----------------
runc-1.0.1-1.gitc5ec254.fc26              f26-updates           dwalsh

**Comment by Silvanoc** [comment]
RC5? There is no such an official release candidate...

Where can I get the source code from? Remember that I'm running on Debian, so I cannot use koji.

**Comment by rhatdan** [comment]
@mrunalp Could you comment on this?

**Comment by mrunalp** [comment]
The latest runc compiled from master should work unless buildah is using an older generate library. cc: @nalind

**Comment by Silvanoc** [comment]
I'm really confused with the versions being reported by @rhatdan ...

If I'm reading it right, your runc version reports support for the OCI-runtime specification version 1.0.0-rc5. Since the OCI-runtime specification version 1.0.0 was already released and the current runc master supports it already, it would be a hint for an old runc version.

But on the other side the last line looks like if you were using runc version 1.0.1 from git commit c5ec254. runc version 1.0.1 doesn't exist, but [commit c5ec254](https://github.com/opencontainers/runc/commit/c5ec254) does exist and is 1+1/2 months older than the one I'm using.

**Comment by rhatdan** [comment]
Ignore the rpm packaging version, The packager jumped the gun on the release.  It is runc 1.0 RC5. Not 1.0 final release.

**Comment by Silvanoc** [comment]
Unless you have access to a fork providing what should become RC5 through a PR or something like that, I think that there's something wrong with the versions being provided, since there is no RC5 yet.

**Comment by rhatdan** [comment]
The next version in Fedora 26 and others will be runc-1.0.0-10.rc4.gitaea4f21.fc26

**Comment by Silvanoc** [comment]
It worked with that version! Thank you for your support! 👍
