### ISSUE TITLE
Unable to install Buildah dependencies on Debian

### ISSUE THREAD

**Issue by ashleyjsands** [projectatomic/buildah#262]
When I'm following the Ubuntu/Debian installation instructions in the README:
```
  apt-get -y install software-properties-common
  add-apt-repository -y ppa:alexlarsson/flatpak
  add-apt-repository -y ppa:gophers/archive
  apt-add-repository -y ppa:projectatomic/ppa
  apt-get -y -qq update
  apt-get -y install bats btrfs-tools git libapparmor-dev libdevmapper-dev libglib2.0-dev libgpgme11-dev libostree-dev libseccomp-dev libselinux1-dev skopeo-containers go-md2man
  apt-get -y install golang-1.8
```
I get this error:
```
W: Failed to fetch http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/gophers/archive/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

W: Failed to fetch http://ppa.launchpad.net/projectatomic/ppa/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

I've attached part of the command output when I was installing the dependencies inside of a docker container.
[BuildahFailLog.txt](https://github.com/projectatomic/buildah/files/1309686/BuildahFailLog.txt)

I am trying to install this on Debian 8, but I've also tried Debian 9.

**Comment by lsm5** [comment]
The PPA has packages for Ubuntu zesty and xenial, and IIUC Debian ain't compatible with Ubuntu PPAs. Could you please try this on Ubuntu versions instead?

**Comment by ashleyjsands** [comment]
Unfortunately I am attempting to install Buildah on the Jenkins slave image (https://hub.docker.com/r/jenkinsci/slave/), which is running on Debian.

Maybe its best if the README instructions didn't say "Ubuntu/Debian" and only specified Ubuntu.

**Comment by lsm5** [comment]
@ashleyjsands yup, https://github.com/projectatomic/buildah/pull/264
