### ISSUE TITLE
buildah run should allow setting the hostname

### ISSUE THREAD

**Issue by mildred** [projectatomic/buildah#265]
Starting from a debian:stable-slim image, I want to install the `inn2` package using standard `apt-get update` and `apt-get install -y` commands but I get the following error when the post install script is run:

```
Setting up inn2 (2.6.1-2) ...
innconfval: hostname does not resolve or domain not set in inn.conf
```

I believe setting the hostname to something that resolves to an IP address would make it work. The hostname is `mrsdalloway` and I cannot change it using something like

```
+ buildah --storage-driver btrfs run debian-working-container-2 -- hostname localhost
hostname: you must be root to change the host name
```

In the code there is already some logic to change the hostname:

https://github.com/projectatomic/buildah/blob/c8a887f51213aeea1cc54d7897064641d029a449/cmd/buildah/run.go#L81-L84

However, the command line flag is not declared and it is not possible to change the hostname. It looks like it would be easy to add the cli flag. In the meantime, are there other options to change the hostname with current buildah versions?

**Comment by rhatdan** [comment]
Fixed in buildah 0.5.
