### ISSUE TITLE
Buildah commands

### ISSUE THREAD

**Issue by pratapnanda** [projectatomic/buildah#274]
Hi

I am new to buildah tool, and recently doing some R&D on Buildah

i want to deploy an application on container using buildah.
Can I achieve below objectives using buildah and how.
- volume - How to Mount external volume such as AWS EBS/EFS/S3 to buildah container
- setting resources - e.g. CPU, Memory etc
- how to scale up and down buildah container
- How can I check buildah container logs (like docker logs)

**Comment by rhatdan** [comment]
Buildah is used to build container images not really for running them in production.  You might want to look at the kpod/cri-o effort https://github.com/kubernetes-incubator/cri-o.

We will be building soop kpod run and kpod exec, which is what you want I believe, if you want something higher level, I would look at OpenShift and Kubernetes.

**Comment by jrobeson** [comment]
@rhatdan : is that sort of thing recommended for folks using or one two containers on single machines? When i hear anything kubernetes related it sure sounds like overkill for many simple use cases. Is that not the case for the mentioned project?  

I bet there are quite a few folks like me who just want a simple non-docker way to manage a few containers for local dev environments and just a few (or one) production servers via simple tooling like ansible.

**Comment by jrobeson** [comment]
As an addendum, it's really hard to separate the intended audiences of container tooling for folks with simple needs like myself.

**Comment by rhatdan** [comment]
kpod/buildah will eventually be the tool for you.  kpod although it is currently part of CRI-O does not require kubernetes.  Our goal with it is to give you the entire docker experience on a single node, minus the orchestration bits.

**Comment by jrobeson** [comment]
@rhatdan: I'll keep an eye on it. thanks!

**Comment by rhatdan** [comment]
We have now created github.com:projectatomic/libpod which containers the kpod tool.

**Comment by ripcurld0** [comment]
I'm closing this as this is out of the project's scope.
As @rhatdan said feel free to use either [libpod](http://github.com/projectatomic/libpod) or [cri-o](https://github.com/kubernetes-incubator/cri-o) for that.
