### ISSUE TITLE
'buildah bud .' is creating 3 images instead of 1

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#279]
On an updated Fedora 26 host, I'd a Dockerfile with these contents:
```
# cat Dockerfile
FROM alpine
CMD ls -alF /
```
I then ran 'buildah bud .' and when I looked at the list of images, there were three images.  One for alpine as expected, but two others sharing the same ImageID.

```
# buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
e3df61726985         docker.io/library/alpine:latest                          Sep 13, 2017 14:32     3.784 MB
4c8a459ec624                                                                  Sep 13, 2017 14:32     1.131 KB
4c8a459ec624         <none>                                                   Sep 13, 2017 14:32     1.131 KB
```

This may be an issue with container/image rather than Buildah, starting here.

**Comment by rhatdan** [comment]
@nalind WDYT

**Comment by nalind** [comment]
Thanks for the reproducer.  It turns out we're printing the IDs of unnamed images twice: once with an empty name, and again with a `<none>` placeholder.

**Comment by rhatdan** [comment]
Looks like this is fixed.
