### ISSUE TITLE
No rule to make target 'runc'. for Ubuntu 16.04

### ISSUE THREAD

**Issue by ashleyjsands** [projectatomic/buildah#286]
When I attempt to build Buildah in a Ubuntu 16.04 image using the instructions in the README, I get a make error:
make: *** No rule to make target 'runc'.  Stop.

I've attached the Dockerfile that I'm trying to build and the output from building that Dockerfile to this issue.
[output.txt](https://github.com/projectatomic/buildah/files/1367585/output.txt)
[Dockerfile.txt](https://github.com/projectatomic/buildah/files/1367584/Dockerfile.txt)

**Comment by rhatdan** [comment]
runc is not part of buildah.  You need to get this elsewhere.

**Comment by nalind** [comment]
The Dockerfile include RUN instructions for the `cd` and `export` commands, which won't produce the expected result, as each instruction in the Dockerfile is run on its own inside of a shell that's started in the location most recently specified using the WORKDIR command, with an environment that is freshly set up according to the image's configuration.  The `make` command is being run from a different location.  You could replace
```
RUN mkdir ~/buildah
RUN cd ~/buildah
RUN export GOPATH=`pwd`
RUN git clone https://github.com/projectatomic/buildah ./src/github.com/projectatomic/buildah
RUN cd ./src/github.com/projectatomic/buildah
RUN PATH=/usr/lib/go-1.8/bin:$PATH make runc all TAGS="apparmor seccomp"
RUN make install
```
with
```
RUN mkdir ~/buildah ; \
    cd ~/buildah ; \
    export GOPATH=`pwd` ; \
    git clone https://github.com/projectatomic/buildah ./src/github.com/projectatomic/buildah ; \
    cd ./src/github.com/projectatomic/buildah ; \
    PATH=/usr/lib/go-1.8/bin:$PATH make runc all TAGS="apparmor seccomp" ; \
    make install
```
and the build would complete.
The ENTRYPOINT (`ENTRYPOINT ["buildah --help"]`) also needs a bit of tweaking, as "buildah --help" isn't the name of a binary file that we install.  I suggest setting it to "buildah" and specifying "--help" as a CMD value.

**Comment by ashleyjsands** [comment]
Thanks @nalind. You've pointed out my exact problem. I didn't know that Docker ran each RUN instruction in its own shell. Thanks again.
