### ISSUE TITLE
How to run Buildah without docker/root privileges

### ISSUE THREAD

**Issue by ashleyjsands** [projectatomic/buildah#287]
My goal is to build a Jenkins Slave ubuntu image that uses buildah to build docker images without needing root privileges to access Docker on the host. Is this possible with Buildah at the moment?

I have successfully installed Buildah on an Ubuntu image, ran it as a container with /var/lib/containers/storage and /var/run/containers/storage bind mounted and then as root, I run a command like `buildah bud -f Dockerfile` I get  an ambiguous error:
```
operation not permitted
operation not permitted
```

When I run the same command not as a root user, the error is:
```
error opening "/var/lib/containers/storage/storage.lock": permission denied
error opening "/var/lib/containers/storage/storage.lock": permission denied
```

From my poor understand of docker and containers, it seems to me that in order to use buildah inside of a container, I still need privileges to certain container directories on the host. Is it possible to run buildah inside of a container without any privileges to anything on the host?

**Comment by rhatdan** [comment]
Buildah does not use docker. It is meant as a replacement for docker build, totally independent of the daemon.  We have not worked to get buildah to work without requiring root, yet.  There are potentially two routes to do this, one is to use user namespace, but even with that we still have to deal with the need to mount.  (Which is not allowed even in a User Namespace).  Another potential is to use file systems that do not need to be mounted, and eliminate the need to mount.  But we are still finishing off the basic functionality at this point.

**Comment by ashleyjsands** [comment]
Thanks @rhatdan for the detailed response. This perfectly answers my question.
