### ISSUE TITLE
Get tests for #294 running in CI

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#314]
Our current CI setup forces us to skip the test for labeling that we're adding in #294.  This is a note so that we don't forget to either get it running or make that functionality the storage library's problem.

**Comment by rhatdan** [comment]
Basically we need to get the SELinux tests to happen outside of the container and on the host.

**Comment by TomSweeneyRedHat** [comment]
Closing as this is being tracked in trello at https://trello.com/c/Nd2JNk4B/828-buildah-run-get-selinux-testing-running
