### ISSUE TITLE
Buildah needs to be able to use containers pulled using kpod/cri-o.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/buildah#326]
kpod pull centos
buildah from centos
open /var/lib/containers/storage/overlay-containers/7c8a3e5865a0881b1a7c246e32b7373b81d7a87124ccfe7e359b3da1b4a1475d/userdata/buildah.json: no such file or directory

**Comment by rhatdan** [comment]
@umohnani8 can you look at this.

**Comment by umohnani8** [comment]
I can replicate the issue also. It also fails when the image is not pulled prior to the command.

sudo buildah from alpine
Getting image source signatures
Copying blob sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
 1.90 MiB / 1.90 MiB [======================================================] 0s
Copying config sha256:053cde6e8953ebd834df8f6382e68be83adb39bfc063e40b0fc61b4b333938f1
 1.48 KiB / 1.48 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
open /var/lib/containers/storage/overlay-containers/2660a727006587ee9ea5bfeb28d9b5f21032a1c037661db62a83fce9ab513ecf/userdata/buildah.json: no such file or directory

**Comment by TomSweeneyRedHat** [comment]
Hmm, working for me on an updated Fedora 26 after changing the "driver" to "overlay" in /etc/containers/storage.conf.  
```
# buildah from alpine
Getting image source signatures
Copying blob sha256:b56ae66c29370df48e7377c8f9baa744a3958058a766793f821dadcb144a4647
 1.90 MiB / 1.90 MiB [======================================================] 0s
Copying config sha256:053cde6e8953ebd834df8f6382e68be83adb39bfc063e40b0fc61b4b333938f1
 1.48 KiB / 1.48 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
alpine-working-container
# buildah version
Version:       0.6
Go Version:    go1.8.4
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    7a3bc6e
Built:         Thu Nov 16 15:10:09 2017
OS/Arch:       linux/amd64
```

**Comment by rhatdan** [comment]
I have a PR for this, the issue happens when you create a container using kpod or cri-o, we need to ignore these containers for now, and eventually build understanding into buildah to be able to reserve their SELinux labels.

**Comment by rhatdan** [comment]
https://github.com/projectatomic/buildah/pull/327 should fix this issue.

**Comment by nalind** [comment]
Closing by #327.
