### ISSUE TITLE
bud: Failed to connect to bus: No such file or directory

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#329]
Docker build with below Dockerfile is fine, buildah bud with below Dockerfile failed.

The last few lines are
```
Failed to connect to bus: No such file or directory
BDB1539 Build signature doesn't match environment
failed loading RPMDB
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
error building: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTTAG=f26container FGC=f26 FBR=f26] Command:run Args:[dnf -y update && dnf clean all] Flags:[] Attrs:map[] Message:RUN dnf -y update && dnf clean all Original:RUN dnf -y update && dnf clean all}: exit status 1
```

```
# cat Dockerfile 
FROM fedora
MAINTAINER http://fedoraproject.org/wiki/Cloud

RUN dnf -y update && dnf clean all
RUN dnf -y install nginx && dnf clean all
RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html

EXPOSE 80

CMD [ "/usr/sbin/nginx" ]
```

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Is this the SELinux issue we just found?

@gouyang could you try with `setenforce 0`

You need an updated container-selinux if this succeeds.
container-selinux-2.33.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan this has the looks of that container-selinux issue.  @gouyang which versions of Buildah and Fedora were you running on?

**Comment by TomSweeneyRedHat** [comment]
FWIW, I tested this with Fedora 27 and Buildah 0.4 and this ran without an issue.  However on Buildah 0.7 I ran into the container-selinux issue.  However the footprint was slightly different than what I see here.

**Comment by TomSweeneyRedHat** [comment]
Should have included the error that I was seeing:

```
STEP 2: MAINTAINER http://fedoraproject.org/wiki/Cloud
STEP 3: RUN dnf -y update && dnf clean all
Can not read configuration: /etc/dnf/dnf.conf , ignoring
Config error: Permission denied: '/var/log/dnf.log'
error building: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTTAG=f27container FGC=f27 FBR=f27] Command:run Args:[dnf -y update && dnf clean all] Flags:[] Attrs:map[] Message:RUN dnf -y update && dnf clean all Original:RUN dnf -y update && dnf clean all}: exit status 1
```

@gouyang were you running Buildah 0.5 or 0.7?

**Comment by rhatdan** [comment]
buildah 0.7 has SELinux support whereas 0.4 did not.

**Comment by rhatdan** [comment]
If you have container-selinux-2.33 you should be fine.  You will need to restorecon -R -v /var/lib/containers or rm -rf /var/lib/containers.

BTW Give karma to the buildah/container-selinux release if it works for you.

**Comment by gouyang** [comment]
Run buildah 0.4 on Fedora 27 even with selinux enable is okay.

Run buildha 0.7 built from master on Fedora 26 with selinux disable is not okay, after install container-selinux-2.33 from updates-testing repo, it works finally.

**Comment by TomSweeneyRedHat** [comment]
@gouyang Thanks for the info and the extra testing!
