### ISSUE TITLE
Default in `--storage-opt` brakes changing storrage driver

### ISSUE THREAD

**Issue by mskarbek** [projectatomic/buildah#344]
I'd like to change `overlay` to `zfs` as my storage driver but in my current version (0.5-2.gitf7dc659.fc27) buildah sets default value to `storage-opt` and doesn't allow resetting that to an empty string (https://github.com/projectatomic/buildah/blob/f7dc659/cmd/buildah/common.go#L33) - that breaks choosing different storage driver.
```
# buildah --storage-driver zfs --storage-opt '' images
Unknown option overlay.override_kernel_check
Unknown option overlay.override_kernel_check
```

**Comment by mskarbek** [comment]
Apparently I'm not able to read documentation properly. Closing.

**Comment by TomSweeneyRedHat** [comment]
@mskarbek sorry for not getting to this sooner, but am glad to hear you figured it out!
