### ISSUE TITLE
hospitable README

### ISSUE THREAD

**Issue by vbatts** [projectatomic/buildah#347]
could the buildah README.md have some copy paste example on running it, rather than so much build instructions?
it would seem much more useful to people searching for it and just giving it a 10second review
like, at first glance i would be 10x more likely to use/try a project if the README showed how it makes my life easier but having 5 pastes of compile instructions is a deterrent

**Comment by nalind** [comment]
As it gets easier to find binary packages, this'll probably be more relevant to people who are interested in trying it out.
