### ISSUE TITLE
runc issues with Buildah when running a registry on Fedora 27

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#353]
When running a registry with Buildah on Fedora 27, runc errors are popping up.  It appears we need a new version of runc on Fedora 27 as there is no issue if you clone/build runc, but installed versions including the latest update don't appear to work.

Email from @rossturk follows forwarded by @ipbabble 

Hey Ross,

Thanks for the testing.  I'll touch base with Dan next week to see what's what with the runc versions.  I think we may need to have a new one built for Fedora.

Very much appreciate the testing and the reports.  I'm going to log this as an issue against Buildah on the GitHub site so we won't lose track of it.

t

On 12/08/2017 05:55 PM, Ross Turk wrote:
>
> No worries on the hiccup! I hope I am not wasting time and this has some diagnostic value.
>
> I altered your second command to reinstall buildah after the first command:
>
> # dnf -y remove runc
> # dnf -y install runc buildah --enablerepo updates-testing
>
> Afterwards I got the same error. My runc version is:
>
> runc version 1.0.0-rc4+dev
> commit: 97b8bfe7fdea74d5e49b657013455a888328f04e
> spec: 1.0.0
>
> Cheers,
> Ross
>
>
>> On Dec 8, 2017, at 1:51 PM, Tom Sweeney <tsweeney@redhat.com> wrote:
>>
>> Hi Ross,
>>
>> Thanks for the note and sorry for the hiccup.  runc has caused a few from time to time.
>>
>> If you've the time to play a little bit, could you do:
>>
>> # dnf -y remove runc
>>
>> and then try
>>
>> # dnf -y install runc --enablerepo updates-testing
>>
>> and let me know if Buildah is happy after that and/or what version runc sits at.
>>
>> Thanks!
>>
>> t
>>
>> On 12/08/2017 04:13 PM, Ross Turk wrote:
>>> That’s really odd! Just to be more specific about my environment, I’m running on a completely fresh Fedora 27 Cloud Base - ran those four dnf/buildah commands immediately following the VM creation.
>>>
>>> Cheers,
>>> Ross
>>>
>>>
>>>> On Dec 8, 2017, at 12:30 PM, William Henry <whenry@redhat.com> wrote:
>>>>
>>>> Ross confirmed that it worked with another package. I have not seen the issue. But it is worth bringing up.
>>>>
>>>> For the record my working commit # is the same as his broken commit version:
>>>>
>>>> $ runc -v
>>>> runc version 1.0.0-rc4+dev
>>>> commit: 01831c088179672b0a6af47954a626b3a886fcd8
>>>> spec: 1.0.0
>>>>
>>>> ¯\_(ツ)_/¯
>>>>
>>>> Willaim
>>>>
>>>>
>>>> William Henry
>>>> Senior Consulting Software Engineer
>>>> Red Hat
>>>> Colorado, USA.
>>>>
>>>> On Fri, Dec 8, 2017 at 1:25 PM, Ross Turk <rturk@redhat.com> wrote:
>>>>
>>>>
>>>>     Hey folks - I ran into an issue walking through William’s new buildah tutorial that he thought I should make you aware of.
>>>>
>>>>     From a fresh Fedora 27 host, I ran these commands:
>>>>
>>>>     # dnf -y update # and reboot
>>>>     # dnf -y install buildah
>>>>     # registry=$(buildah from registry)
>>>>     # buildah --debug run $registry
>>>>
>>>>     I get the following output:
>>>>
>>>>     DEBU[0000] error running runc [/entrypoint.sh /etc/docker/registry/config.yml]: exit status 139
>>>>     DEBU[0000] error running [] in container "registry-working-container": exit status 139
>>>>
>>>>     I was able to chroot into the mounted container and successfully run entrypoint.sh manually, so I began to suspect runc. If I call runc -v it gives me this:
>>>>
>>>>     runc version 1.0.0-rc4+dev
>>>>     commit: 01831c088179672b0a6af47954a626b3a886fcd8
>>>>     spec: 1.0.0
>>>>
>>>>     If I build runc from current GitHub master, buildah run $registry works. A ha! The version of runc that works is:
>>>>
>>>>     runc version 1.0.0-rc4+dev
>>>>     commit: 1d3ab6d668952a23498256dd385bec37f8f9fa04
>>>>     spec: 1.0.0
>>>>
>>>>     I think the tutorial is about to go live, if it’s not already. I wonder - will people run into this issue with the runc packages currently in f27?
>>>>
>>>>     Cheers,
>>>>     Ross
>>>>
>>>>     --
>>>>     Ross Turk
>>>>     Portfolio Evangelism, Red Hat
>>>>     @rossturk
>>>>
>>>>
>>>
>>> --
>>> Ross Turk
>>> Portfolio Evangelism, Red Hat
>>> @rossturk
>>>
>>
>
> --
> Ross Turk
> Portfolio Evangelism, Red Hat
> @rossturk
>

**Comment by rhatdan** [comment]
Rebuilding latest runc from upstream.

runc-1.0.0-13.rc4.git1d3ab6d

**Comment by rhatdan** [comment]
Please test and update Karma

**Comment by rhatdan** [comment]
https://bodhi.fedoraproject.org/updates/FEDORA-2017-3676a27a48
