### ISSUE TITLE
buildah run works with symbolic image names but not hex

### ISSUE THREAD

**Issue by anarcat** [projectatomic/buildah#356]
This works:

    root@curie:~# buildah from docker.io/anarcat/debian-airsonic:latest
    debian-airsonic-working-container-2

But this doesn't:

    root@curie:~# buildah from e87186c3d14
    error pulling image "docker.io/library/e87186c3d14:latest": Error initializing image from source docker://e87186c3d14:latest: errors:
    denied: requested access to the resource is denied
    unauthorized: authentication required

It looks like buildah is trying to fetch the container instead of looking in the local image storage, which has the image:

```
root@curie:~# buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
9ad0f3c4a8cd         docker.io/library/debian:stretch                         Nov 4, 2017 05:26      95.46 MB
e87186c3d14e         docker.io/anarcat/debian-airsonic:latest                 Nov 4, 2017 05:26      1.442 KB
2a90789e080d         docker.io/projectatomic/atomicapp:latest                 Oct 6, 2016 20:28      278.4 MB
```

**Comment by TomSweeneyRedHat** [comment]
@anarcat which version of Buildah?  I think this is fixed in 0.9, a very recent release on Fedora.

**Comment by anarcat** [comment]
this is from most recent git:

```
$ git describe --tags
v0.8-23-ge44fce4
```

... which, i believe, includes the 0.9 changes, regardless what what describe says.

**Comment by TomSweeneyRedHat** [comment]
@anarcat well drats, so much for the quick update fix.  I'll try playing with it this afternoon.

**Comment by TomSweeneyRedHat** [comment]
@anarcat.  I see the problem.  I'd this issue mixed up with the same issue that we just fixed for buildah push.  This from issue might be cured with #187, but I've not tested that yet.  Need to do so.  I also have a thought about a possible shorter term fix, will look at that in the morn.  Will keep you posted.

**Comment by TomSweeneyRedHat** [comment]
I did not mean to close this.

**Comment by rhatdan** [comment]
@nalind WDYT?

**Comment by nalind** [comment]
It's not fixed in the current iteration of #187, so if we have a fix that can be merged before that, it would be a good idea.

**Comment by TomSweeneyRedHat** [comment]
Fixed with the #360.  Not in a kit yet, but can be retrieved via a GitHub clone.
```
# buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
63406bcaf11e         docker.io/tomsweeneyredhat/testing:first                 Jul 12, 2017 16:57     255.4 MB
# buildah from 63406bcaf11e
testing-working-container-2
```

**Comment by TomSweeneyRedHat** [comment]
@anarcat please reopen if you find differently and thank you for the issue report!

**Comment by rhatdan** [comment]
Getting near time we build a buildah 1.10?

**Comment by TomSweeneyRedHat** [comment]
I think we should hold until #365 is fixed, then yes as we've had a number of good improvements.
