### ISSUE TITLE
support Buildahfile [good_first_pr]

### ISSUE THREAD

**Issue by goern** [projectatomic/buildah#358]
Start using Buildahfile rather than Dockerfile when executing `buildah bud`. Adding `build-using-buildahfile` is just consequent...

**Comment by rhatdan** [comment]
What exactly is a buildahfile?  Not sure we want to confuse the market. Dockerfile is a standard syntax.  The only other syntax I want to use for building container images is the "bash shell" format.

**Comment by ripcurld0** [comment]
ping @goern can you address @rhatdan question, please?
😃

**Comment by rhatdan** [comment]
I think we can close this issue.
