### ISSUE TITLE
Lets add @rh-atomic-bot support so we can enforce tests pass before merging. 

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/buildah#36]
@jlebon @cgwalters How can we setup buildah to use rh-atomic-bot?

**Comment by jlebon** [comment]
You can open PR against https://github.com/jlebon/redhat-ci as described in the README. Specify in the PR whether you just want automated PR testing, or if you also want the merge bot (i.e. the `r+` functionality).

**Comment by jlebon** [comment]
Let's try this out in https://github.com/projectatomic/buildah/pull/37.

**Comment by nalind** [comment]
Looks good, closing.
