### ISSUE TITLE
`buildah from` error - does not resolve to an image ID

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#365]
When run a number of different 'buildah from' commands I'm seeing the below error on each one.  The from commands all seem to complete OK, but each has the error. 

```
# container=$(buildah from fedora)
ERRO[0000] reference "[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]docker.io/library/fedora:latest" does not resolve to an image ID 
Getting image source signatures
Copying blob sha256:a8ee583972c2295bb76704d4defe5116d5e4dd7ba3767aaa2cc8fcf71088ee06
 82.80 MiB / 82.80 MiB [===================================================] 12s
Copying config sha256:422dc563ca3260ad9ef5c47a1c246f5065d7f177ce51f4dd208efd82967ff182
 2.29 KiB / 2.29 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
echo $container
fedora-working-container
```

**Comment by rhatdan** [comment]
Yes @nalind has a PR up for containers/image to stop blabing at Errorf when this happens and move it down to Debugf. 
https://github.com/containers/image/pull/393

Looks like it is merged, will update the buildah to use latest containers/image.

**Comment by nalind** [comment]
#366 should include that change here.

**Comment by TomSweeneyRedHat** [comment]
Just ran the Baseline tests against the latest/greatest and no more errors.  Looks good!
