### ISSUE TITLE
Support build from context tar.gz file

### ISSUE THREAD

**Issue by smarterclayton** [projectatomic/buildah#373]
For the OpenShift build proxy support I made a few changes to imagebuilder to support a getting build context from a tar.gz file instead of a directory (to preserve exact permissions).

I'd like buildah to support a source tar.gz file (either via `-` as the build context like Docker or as a direct path to the file), and then leverage the latest changes in imagebuilder in https://github.com/openshift/imagebuilder/pull/53 to avoid having to double unpack the context for ADD / COPY.  That'll open the door for a prototype of buildah being invoked from that path.

**Comment by TomSweeneyRedHat** [comment]
Closing this as we've moved it to the Trello card https://trello.com/c/RwX66ls7
