### ISSUE TITLE
Failure to build image in 0.10-2

### ISSUE THREAD

**Issue by smarterclayton** [projectatomic/buildah#374]
CentOS 7.4

```
$ runc --version
runc version 1.0.0-rc4+dev
commit: a031838b23e9990f67a3b4c0e89bf3d935d1298b-dirty
spec: 1.0.0
$ buildah version
Version:       0.10
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    129fb10
Built:         Tue Dec 26 12:37:51 2017
OS/Arch:       linux/amd64
```

Attempted to build https://github.com/openshift/release projects/origin-release/base with buildah bud, got this repeatable failure when trying to commit

```
STEP 5: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]@151c26a38f49601ec2cc77514f47d79a0166f1512b93cd64a5d667e6a29b1d4a
error building: error copying layer and metadata: error committing new image "containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage]@151c26a38f49601ec2cc77514f47d79a0166f1512b93cd64a5d667e6a29b1d4a": error determining uncompressed digest for blob "sha256:e9c4879b5b6b53531b4585f3c5d0bb54784b77560612a1c186eb7af94d9a14dc"
```

Other containers were able to commit.  What debugging info can I provide (is 100% reproducible)

**Comment by nalind** [comment]
Can you attach the full output from 'buildah images' followed by 'buildah --debug bud ...'?  That'll tell us whether blob `sha256:e9c4879b5b6b53531b4585f3c5d0bb54784b77560612a1c186eb7af94d9a14dc` was downloaded and stored by buildah, or by something else that ran before it.
If it is a layer that was pulled down by a different package which was built using older versions of the storage or image libraries, that information may have not been recorded.  In that case, it'd be worth checking if removing the local copy of the `centos:7` image and re-trying, forcing buildah to pull down the "from" image, allows it to succeed.

**Comment by smarterclayton** [comment]
Just remove from /var/run/containers/storage and
/var/lib/containers/storage be cleaned up?

**Comment by nalind** [comment]
If no container filesystems are mounted up, that's fine.  Alternately, something like `buildah containers -q | xargs buildah rm` followed by `buildah images -q | xargs buildah rmi` would also work.

**Comment by rhatdan** [comment]
We've added flags -a to `podman rm -a` and `podman rmi -a`, we should add similar to buildah, since this is a common enough command sequence.
@TomSweeneyRedHat Could you take a quick look at doing this?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan will do

**Comment by rhatdan** [comment]
These patches were added
