### ISSUE TITLE
No way to constrain buildah execution to cgroups, existing network namespaces?

### ISSUE THREAD

**Issue by smarterclayton** [projectatomic/buildah#376]
I was unable to find this (it might be there), but it appears that there is no way to run a buildah command against an existing network namespace or existing cgroup, which is a blocker for use with OpenShift (note that we'd likely also need more fine grained control over execution for other namespaces as well, and #375 is the other direction we might go).

What limits are there to supporting that, how much change is involved, and what are the gaps?

**Comment by rhatdan** [comment]
It would seem that most of this could be done simply by adding the options --cgroup and --NAMESPACE handling that we have in podman

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[buildah] Add --cgroup-parent and namespace options](https://trello.com/c/mq05gPYd/749-buildah-add-cgroup-parent-and-namespace-options)

**Comment by TomSweeneyRedHat** [comment]
Closing this issue here as we've a card in trello to track it (see @nalind's prior comment)
