### ISSUE TITLE
Management of symlinks is messy

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#4]
We provide options for creating symbolic links to a container's root filesystem as a convenience, but we don't do anything to prevent the location of a particular link from being specified as a link location for multiple containers.  In the best case, that means we get EEXIST errors preventing mount operations from succeeding, and it's all downhill from there.  We really need to design out how this should work, and that may lead to dropping it.

**Comment by rhatdan** [comment]
Yes I think we should drop it.  Much better would be to provide a mount point for the container and then be able to manipulate the mount point?

**Comment by nalind** [comment]
Should be closed by #26.
