### ISSUE TITLE
Miss cert-dir and creds option for `buildah bud`

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#403]
It looks that if the command is operating with a registry, it have options `authfile`, `cert-dir`, `creds` and `tls-verify`. So I think `cert-dir` and `creds` options need to add to `buildah bud` as well.

**Comment by ripcurld0** [comment]
Hi @gouyang I am not sure what are the differences among these options so I am going to ping @TomSweeneyRedHat @nalind

Thanks.

**Comment by TomSweeneyRedHat** [comment]
FWIW, cert-dir let's you specify where the certificates that you want to use live and --creds let's you put  in the username/password to use for authentication.  

`docker build` doesn't have these options, but neither does 'docker pull/push' while the Buildah equivalents do.  So I think I'll see if I can add these too, but may run into issues making it happen.  The processing for the bud code is a little funkier than the from/push code in Buildah.  

@nalind @rhatdat holler if I shouldn't try adding --creds and --cert-dir to buildah/podman bud/build.

**Comment by TomSweeneyRedHat** [comment]
@gouyang fixed with #419.  Please reopen if you find otherwise and thanks for the problem report.
