### ISSUE TITLE
Dockerfile support for add --chown is missing.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/buildah#407]
We have it for the `buildah copy` command, but the syntax checker for Docker file fails.

```
cat Dockerfile
from fedora
copy --chown 3267:3267 dan.tar
```

```
 buildah bud -f Dockerfile .
STEP 1: FROM fedora
STEP 2: copy --chown 3267:3267 dan.tar
error building: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin DISTTAG=f27container FGC=f27 FBR=f27] Command:copy Args:[3267:3267 dan.tar] Flags:[--chown] Attrs:map[] Message:COPY --chown 3267:3267 dan.tar Original:copy --chown 3267:3267 dan.tar}: no files found matching "/root/3267:3267": no such file or directory
```

**Comment by ripcurld0** [comment]
@rhatdan 
Looking at the code, this is not directly related to `buildah`. In order to have this working, `imagebuilder` needs to support that.

I guess we should move this ticket to [openshift/imagebuilder](https://github.com/openshift/imagebuilder)

**Comment by rhatdan** [comment]
Yes to fix this we need to get a patch into imagebuilder.

**Comment by TomSweeneyRedHat** [comment]
Closing as we've created a Trello card to track tihis at: https://trello.com/c/O2IMRqDB

**Comment by rhatdan** [comment]
@ripcurld @TomSweeneyRedHat Any movement on imagebuilder with this support?

**Comment by rhatdan** [comment]
Tom we are still missing this functionality.  Could you take a look at this, I think this needs work in imagebuilder.

**Comment by rhatdan** [comment]
https://github.com/openshift/imagebuilder/issues/77

**Comment by rhatdan** [comment]
Stil not resolved in imagebuilder.

**Comment by TomSweeneyRedHat** [comment]
Yeah this bubbled down below my radar.  I'll try to pop it back up and look into it again.

**Comment by rhatdan** [comment]
We now have support.  Thanks @TomSweeneyRedHat
