### ISSUE TITLE
incorrect return code when buildah rmi fails

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#409]
The return code should be 1.

```
[root@bootp-73-3-165 ~]# buildah from busybox
busybox-working-container
[root@bootp-73-3-165 ~]# buildah rmi busybox
Could not remove image "busybox" (must force) - container "ec808443580e9eef8e9ef1a69a63a2186d7c6cdb323f3e7adc0a8d0fd55038a6" is using its reference image: image is in use by a container
[root@bootp-73-3-165 ~]# echo $?
0
```

**Comment by gouyang** [comment]
Another example

```
# buildah rmi test
could not get image "test": identifier is not an image
[root@bootp-73-3-165 ~]# echo $?
0
```

**Comment by ripcurld0** [comment]
@rhatdan @TomSweeneyRedHat @nalind did we specify when `buildah rm\i` should return error code 1 and when error code 0?

**Comment by rhatdan** [comment]
No these should exit with a non-zero exit code. @ripcurld0 do you want to handle this?  You might want to look at podman to see how it handles it.

**Comment by ripcurld0** [comment]
@rhatdan sure!

**Comment by ripcurld0** [comment]
Hey @gouyang 
PR #412 was [merged](https://github.com/projectatomic/buildah/commit/fc819944f3d60bfe4bcd1e011cdda193532636ef) and should fix this issue.

Do you mind running more tests to make sure this was resolved successfully?

I am closing this ticket but feel free to comment or provide feedback. 👍
