### ISSUE TITLE
add "--format" to buildah containers

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#424]
There is option `--format` in `buildah images`, but not one for `buildah containers`, I think it should be added.  I also was thinking about `--filter`, but I'm not sure does it worth to add it.

**Comment by umohnani8** [comment]
@rhatdan @TomSweeneyRedHat any specific filter params?

**Comment by rhatdan** [comment]
I would guess the same filters we added to podman ps --filters

**Comment by umohnani8** [comment]
Fixed in #437
