### ISSUE TITLE
`buildah images --format` does not override `--quiet`

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#425]
The usage say `--format value            pretty-print images using a Go template. will override --quiet`, but it does not override `--quiet`.

```
# buildah images  --format "{{.Name}} {{.Size}}"  
docker.io/library/redis:alpine 26.14 MB
docker.io/library/redis:v1 26.14 MB
docker.io/library/redis:v2 26.14 MB
docker.io/library/nginx:latest 107 MB

# buildah images -q --format "{{.Name}} {{.Size}}"  
f9d5de0795395db6c50cb1ac82ebed1bd8eb3eefcebb1aa724e01239594e937b
5b0d59026729b68570d99bc4f3f7c31a2e4f2a5736435641565d93e7c25bd2c3
f0fae769c7d603f23079c2bf2e0f440dc7e1820525c253a0461728984acb93df
9c96fdf15af5e75a711de88fd8480ce767f977070d9ee44734cf75838f31004d
```

**Comment by rhatdan** [comment]
Should we have these conflict?

**Comment by ripcurld0** [comment]
We can return a conflict error or write in the usage message that `quiet` overrides the `format` option.

**Comment by umohnani8** [comment]
Fixed in #426

**Comment by gouyang** [comment]
The usage should be updated as well.

**Comment by TomSweeneyRedHat** [comment]
Hi @gouyang 

The usage for format is:
```
		cli.StringFlag{
			Name:  "format",
			Usage: "pretty-print images using a Go template. will override --quiet",
},
```
which I think covers what you're looking for or am I misundertanding?

**Comment by umohnani8** [comment]
Yeah I forgot to remove the "will override --quiet" since we changed to error out if both quiet and format are set. This is being fixed in https://github.com/projectatomic/buildah/pull/437.
