### ISSUE TITLE
"target os mismatch with current os linux" on Oracle Linux 7.4

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#435]
When attempting `buildah run` on Oracle Linux 7.4 with Oracle Linux 7-slim image, receive the error message `target os mismatch with current os linux`

Looks similar to #258, but runc version is newer than that recommended in the #258 thread as a fix.

Oracle image is from here:
https://hub.docker.com/_/oraclelinux/

**Steps to reproduce the issue:**
container=$(buildah from docker-daemon:oraclelinux:7-slim)
buildah run ${container} -- ls -l

**Describe the results you received:**
Error message `target os mismatch with current os linux`

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.9-1.git04ea079.el7.x86_64
runc-1.0.0-12.1.gitf8ce01d.el7.x86_64
```

**Output of `buildah version`:**

```
buildah version 0.9 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
Red Hat Enterprise Linux Server release 7.4 (Maipo)
Oracle Linux Server release 7.4
```

**Comment by rhatdan** [comment]
I think this is still a version of runc issue.  The RHEL package we are now building for runc is 
 runc-1.0.0-26.rc4.dev.git9f9c962.el7

We are also getting close to shipping 
buildah-0.11-1.git6bad262.el7

Could you attempt to build runc from upstream to see if this fixes the issue.

**Comment by pixdrift** [comment]
Apologies Dan,

Took the runc package up to `runc-1.0.0-23.rc4.dev.git1d3ab6d.el7.x86_64` from the same CentOS extras repo and it has resolved the issue.

**Comment by rhatdan** [comment]
Excellent.

**Comment by pixdrift** [comment]
Sorry to reopen, but was thinking about this when deploying again today.

Should the RPM spec be bumped to require a higher version of runc to resolve for those installing via RPM? If so, do we have an indication of what this should be updated to?

Current runc requires in the spec is:
`Requires:       runc >= 1.0.0-6`

It's currently blocked by the runc RPM in CentOS extras because current stable is (.23 I am using is an RC):
`runc-1.0.0-12.1.gitf8ce01d.el7.x86_64.rpm`

Which from testing above doesn't work... but something that should be tracked for when the runc package is released/updated?

**Comment by rhatdan** [comment]
That is something that should be opened as a bugzilla against the package.

**Comment by pixdrift** [comment]
Will do.

**Comment by ripcurld0** [comment]
@pixdrift closing this as this is not an issue related directly to this repository.
Reopen if I am wrong.

Thanks so much!
