### ISSUE TITLE
incorrect file ownership in mount directory after add --chown

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#436]
1. create a container and mount it
```
# buildah from nginx
nginx-working-container
# buildah mount nginx-working-container
```
2. add a file to the container and chown with a user which exist in container, but not exist in host.
it display the user's uid,  I think it's acceptable.
```
# buildah add --chown nginx:nginx nginx-working-container Makefile /home
# ls /var/lib/containers/storage/overlay/40a1db3e5add6e272a213a603b02226eb4a7a15cc641042993f53039db6f57f4/merged/home -l
total 4
-rw-r--r--. 1 101 101 1862 Jan 31 02:58 Makefile
```
3. add a file to the container and chown with a user exists in both the host and the container.
The chown user is `bin:bin`, but it displays as `daemon:daemon`. It's because the uid of `bin` is 2 in the container, but the user of uid 2 is `daemon` on host.

```
# buildah add --chown bin:bin nginx-working-container Vagrantfile /home
# ls /var/lib/containers/storage/overlay/40a1db3e5add6e272a213a603b02226eb4a7a15cc641042993f53039db6f57f4/merged/home -l
total 12
-rw-r--r--. 1    101    101 1862 Jan 31 02:58 Makefile
-rw-r--r--. 1 daemon daemon 4690 Jan 16 05:19 Vagrantfile
```

I hit the problem when I'm trying to write ansible scripts to test the `buildah add --chown`. The tests got failed because of this problem and it confused me a whole day.

the scripts looks like:
```
- name: buildah add with option chown
  command: buildah add --chown bin:bin nginx-working-container Vagrantfile /home

- name: mount the container
  command: buildah mount nginx-working-container
  register: mnt

- name: check file owner after add with option chown
  stat: path={{ mnt.stdout }}/home/Vagrantfile
  register: st
  failed_when: '"bin" not in st.stdout'
```

Not sure whether it's an issue, please close it if it's not.

**Comment by bertinatto** [comment]
Hi @gouyang. I think the `stat` command is parsing the `/etc/passwd` file from the host. I guess it'd be more reliable to execute it from inside the container. Maybe you could use `buildah run` for that? Example:

```
sudo ./buildah copy --chown bin:bin nginx-working-container commit.go /
sudo ./buildah run  nginx-working-container -- ls -lh /commit.go
-rw-rw-r--. 1 bin bin 11K Dec 25 18:22 /commit.go
```

**Comment by gouyang** [comment]
@bertinatto thanks for the tips, I was doing it as below:

```
- name: check user after add with option chown
  raw: buildah run --tty nginxc stat -c %U /home/hello
  register: ast
  failed_when: '"bin" not in ast.stdout'
```

**Comment by TomSweeneyRedHat** [comment]
I'll let @nalind correct me, but I do believe @bertinatto is correct about the stat parsing on the host's side.   @gouyang I think but I'm not sure that solves the issue.  Do you agree?

**Comment by gouyang** [comment]
Please ignore the ansible script, the main issue is that the file owner is `bin` in container, and it becomes `daemon` when visit on the host after mount the container. This is the problem I was to report, do you think it's an issue?

**Comment by bertinatto** [comment]
@gouyang, from my perspective it's not an issue, but I'll let the other guys decide.

**Comment by rhatdan** [comment]
All I care is the file from inside of the container has the correct UID based on the name in the /etc/passwd file.  If the /etc/passwd on the host and in the container differ then the usernames might be different. Is this what is happening?

**Comment by gouyang** [comment]
@rhatdan yes, it's what I meant to report.

**Comment by rhatdan** [comment]
So we are in agreement that it works correctly?  Reopen if you don't agree/
