### ISSUE TITLE
Dockerfile MAINTAINER keyword not being added to labels

### ISSUE THREAD

**Issue by ipbabble** [projectatomic/buildah#448]
**Description**
Using buildah bud on a Dockerfile, the generated json file does not have the label maintainer set when a MAINTAINER keyword used in Dockerfile

**Steps to reproduce the issue:**
1.  run buildah bud -t myimage .   (on a Dockerfile with the MAINTAINER keyword)  
2.  run podman inspect --type image  myimage  <image name form step one>
3.  check if Label is set to container "maintainer" : "something" or null.

**Describe the results you received:**
"Labels": null,

**Describe the results you expected:**
Should be something like 

"Labels": {
                "maintainer": "ipbabble <ipbabble@gmail.com>"
            },

**Output of `rpm -q buildah` or `apt list buildah`:**
Built from HEAD
```
(paste your output here)
```

**Output of `buildah version`:**

```
# buildah -v 
buildah version 0.8 (image-spec 1.0.0, runtime-spec 1.0.0)

podman version 0.1

```

**Output of `cat /etc/*release`:**

```
Fedora release 27 (Twenty Seven)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 4.13.9-300.fc27.x86_64 #1 SMP Mon Oct 23 13:41:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by nalind** [comment]
The maintainer is expected to be stored in the _Author_ field in the image's metadata rather than as a label, but we weren't setting it.
