### ISSUE TITLE
Install latest go-md2man

### ISSUE THREAD

**Issue by umohnani8** [projectatomic/buildah#449]
Currently the latest go-md2man is causing our tests to break. Reverted to a previous commit for now to get rid of this error.
@rhatdan opened an issue with upstream md2man cpuguy83/go-md2man#34.
Once this is fixed, we should move back to using latest md2man.

**Comment by TomSweeneyRedHat** [comment]
Closing this issue.  Tracking in Trello at: https://trello.com/c/jNCxjO5F/823-1-b-p-install-latest-go-md2man
