### ISSUE TITLE
Buildah bud ignores Dockerfile non-keywords by default 

### ISSUE THREAD

**Issue by ipbabble** [projectatomic/buildah#451]
**Description**

A Dockerfile with lines containing syntax errors - lines starting with non-keywords - does not cause an error and halt the build. Instead it skips the offending line.

Also I think a simple change of setting ignoreUnrecognizedInstructions to false is not the fix. 

i.e. that would have the same effect as commenting out:
//      if !b.ignoreUnrecognizedInstructions {
//              logrus.Debugf("+(UNIMPLEMENTED?) %#v", step)
//              return nil
//      }

But this means that the error output is too verbose because there is no check for log-level.  We probably need to have a if !debug type of check and just output a simple "Buildah Error: unknown instructions: <non-keyword>"

**Steps to reproduce the issue:**
1.  Create a Dockerfile that has commands that need to be run without the RUN keyword at the start. Or a file to be copied without the COPY keyword. 
2.  buildah bud .
3.

**Describe the results you received:**
Build finishes fast. No instructions are executed. All skipped.
I received empty images because dnf commands were not getting run.

**Describe the results you expected:**
Build error: Unknown instruction: DNF

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Built from HEAD
```

**Output of `buildah version`:**

```
buildah version 0.8 (image-spec 1.0.0, runtime-spec 1.0.0)

```

**Output of `cat /etc/*release`:**

```
Fedora release 27 (Twenty Seven)

```

**Output of `uname -a`:**

```
Linux localhost.localdomain 4.13.9-300.fc27.x86_64 #1 SMP Mon Oct 23 13:41:58 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by ipbabble** [comment]
I don't mind trying to fix this one. I just need to understand or be shown how to effectively handle log-level checking in some other part of the code. I'm going to sniff around and see if I can see how it's done elsewhere.

**Comment by ipbabble** [comment]
May want to check the log-level and change the output for simple error.

Something like 👍 func (b *Executor) UnrecognizedInstruction(step *imagebuilder.Step) error {
        if b.ignoreUnrecognizedInstructions {
                logrus.Debugf("+(UNIMPLEMENTED?) %#v", step)
                return nil
        }
        if logrus.GetLevel() == logrus.ErrorLevel {
                return errors.Errorf("Unknown instruction: %v", step.Command)
        } else if logrus.GetLevel() == logrus.DebugLevel {
                logrus.Debugf("Unknown instruction: %#v", step)
                return errors.Errorf("Unknown instruction: %#v", step)
        } else {
                return errors.Errorf("Unknown instruction: %#v", step)
        }


????
}

**Comment by rhatdan** [comment]
@ipbabble Open a separate PR
