### ISSUE TITLE
Decide what "from" --mount should return

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#5]
Normally, "from" prints the new container's name, and "mount" prints the location of the container's root filesystem, which is pretty friendly for scripting.  If we tell "from" to also mount the container, though, printing both is not as friendly.

**Comment by rhatdan** [comment]
We are not printing the mount directory.  I actually believe we should remove the ability to automatically mount the image and force the user to use

```buildah mount CID /mnt```

**Comment by TomSweeneyRedHat** [comment]
👍 the forcing of a mount thought fwiw.

**Comment by nalind** [comment]
Closing by way of #86.
