### ISSUE TITLE
buildah bud does not support SHELL keyword

### ISSUE THREAD

**Issue by duritong** [projectatomic/buildah#507]
Using buildah 0.12 I am not able to build from Dockerfiles that contain the [SHELL keyword](https://docs.docker.com/engine/reference/builder/#shell):

```
git clone https://gitlab.com/gitlab-org/omnibus-gitlab.git
cd omnibus-gitlab/docker
sudo buildah bud .
STEP 2: MAINTAINER GitLab Inc. <support@gitlab.com>
STEP 3: SHELL ["/bin/sh", "-c"],
ERRO[0011] Build error: Unknown instruction: "shell"    
error building: error building at step {Env:[PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin] Command:shell Args:[/bin/sh -c] Flags:[] Attrs:map[json:true] Message:SHELL /bin/sh -c Original:SHELL ["/bin/sh", "-c"],}: Build error: Unknown instruction: "shell" &imagebuilder.Step{Env:[]string{"PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"}, Command:"shell", Args:[]string{"/bin/sh", "-c"}, Flags:[]string{}, Attrs:map[string]bool{"json":true}, Message:"SHELL /bin/sh -c", Original:"SHELL [\"/bin/sh\", \"-c\"],"}
```

**Comment by rhatdan** [comment]
It appears that the SHELL command is mainly for Windows.  But we will look into adding it.

**Comment by rhatdan** [comment]
Tom probably need to get this into ImageFactory first.

**Comment by rhatdan** [comment]
@nalind WDYT?

**Comment by duritong** [comment]
I think if buildah likes to become the chosen tool for building container images and provides a build from Dokerfile option, it probably should support all command. Just adding that as comment with regard to "mainly for Windows", but I understood that you are looking into supporting it.

**Comment by rhatdan** [comment]
https://github.com/openshift/imagebuilder/pull/62 is merges, so we should be able to support the SHELL command now.

**Comment by rhatdan** [comment]
We now have SHELL support.
