### ISSUE TITLE
Build stage caching

### ISSUE THREAD

**Issue by BenHall** [projectatomic/buildah#523]
Is it possible to take advantage of caching layers from previous steps so they don't need to re-run?

For example, I would expect this to produce the same image but at the moment it rebuilds from scratch.

```
buildah bud .
buildah bud -t myimage .
```

**Comment by rhatdan** [comment]
We have a long range plan to allow users to specify if they want caching or not.  For the developer use case it would be a big benefit, but for the situation where you are putting buildah into an build chain, it is actually slower, and you end up with lots of layers.

**Comment by rhatdan** [comment]
We are always looking for people to help, so if someone wanted to take a stab at this...

**Comment by rhatdan** [comment]
I think we have a dup of this.  @umohnani8 Close one of them.

**Comment by umohnani8** [comment]
https://github.com/projectatomic/buildah/issues/601 is a duplicate, closing this one.
