### ISSUE TITLE
Arm builds for Ubuntu

### ISSUE THREAD

**Issue by brlbil** [projectatomic/buildah#530]
All the packages in ubuntu repository expect buildah are compiled for armh
Please add armh packages for buildah as well

Ubuntu repository
https://launchpad.net/~projectatomic/+archive/ubuntu/ppa

**Comment by lsm5** [comment]
@brlbil @rhatdan sorry about the lag, but yes, armhf will be available in a bit, all other packages in the PPA do have armhf already https://launchpad.net/~projectatomic/+archive/ubuntu/ppa/+packages

**Comment by lsm5** [comment]
v0.15 (built from master) should be available in a bit (pending publication) for all arches except powerpc. ptal and lmk.

**Comment by rhatdan** [comment]
Looks like these are built now.
