### ISSUE TITLE
buildah images 'CREATED AT' doesn't report in configured local time

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#537]
**Description**
The 'CREATED AT' date in 'buildah images' reports in UTC rather than configured local time.

**Steps to reproduce the issue:**
1. Display current date
```
# date
Tue Mar 27 09:45:46 AEDT 2018
```
2. Compare to time of recently created image in `buildah images`
```
# buildah images
IMAGE ID             IMAGE NAME                                               CREATED AT             SIZE
95cc7dba2f97         docker.io/library/buildah-ol7:latest                     Mar 26, 2018 22:28     177.4 MB
```

**Describe the results you received:**
'CREATED AT' displays date/time in UTC

**Describe the results you expected:**
'CREATED AT' displays date/time in configured local time

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.12-1.git8badcc2.el7.x86_64
```

**Output of `buildah version`:**

```
buildah version 0.12 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Comment by TomSweeneyRedHat** [comment]
@pixdrift Thanks for the problem report, we'll take a look at it.

**Comment by pixdrift** [comment]
@TomSweeneyRedHat, Curious if it was a conscious decision to use timestamps in buildah rather than relative time like in 'docker images'?

**Comment by TomSweeneyRedHat** [comment]
@pixdrif I'll have to let @nalind and @rhatdan handle that answer.  That had been set before I started on the Buildah project.

**Comment by rhatdan** [comment]
Not that I know of.  Probably just what @nalind did, would you refer it to be relative like Docker?

**Comment by pixdrift** [comment]
Not sure if that was directed at me @rhatdan, I think for consistency with 'docker images' relative would be a good default and then make the 'absolute' date as it stands currently an option/parameter?.

How about a third option that has a date format more akin to log format (YYYY-MM-DD HH:MM:SS) so parsing of 'docker images' output by other command line tools is more practical?

--daterel
--dateabs
--datelog

Death by date options? 😄

**Comment by rhatdan** [comment]
Not crazy about the options, but I think being consistent with the Docker output makes sense.  We also need to make sure that podman output matches.

**Comment by nalind** [comment]
The relative ballpark time information always felt unnecessarily vague to me, but I'm not wedded to using absolute timestamps.  Using the local timezone instead of UTC as the default when printing absolute timestamp information makes a lot of sense, though.

**Comment by taqtiqa-mark** [comment]
Maybe a step towards compliance with the OCI spec v1.0.1 [Properties:Created](https://github.com/opencontainers/image-spec/blob/v1.0.1/config.md#properties) is to use [RFS 3339, Section-5.6](https://tools.ietf.org/html/rfc3339#section-5.6) ?

**Comment by pixdrift** [comment]
@taqtiqa-mark, the spec describes the container configuration formatting, not the end user interface formatting.

From the spec:

> This section defines the application/vnd.oci.image.config.v1+json media type.

**Comment by pixdrift** [comment]
@TomSweeneyRedHat, this is resolved, thanks 👍🍻  much appreciated. I am happy to close this ticket... unless you want to keep it open for discussion on the date format? (which should probably be in a separate issue)
