### ISSUE TITLE
Add support to umount multiple mounts in single operation

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#548]
**Description**
The `buildah umount` command doesn't support the umount of multiple containers in a single operation. To maintain concistency between other buildah commands eg. `rm`, `rmi`, it would be nice to have the ability to `umount` multiple mounts in one operation.

**Steps to reproduce the issue:**
1. `# buildah mount`
`4d8ec97bb4b1 /var/lib/buildah/storage/overlay/ab856bdfaa9899c7bf2429657697ac6edf339b7335095c2383475d7f0b4080c9/diff`
`ef4c0f3b3e53 /var/lib/buildah/storage/overlay/20e940f0ef91d1c37129bfa49258a0507a73231d285ce8206441baecf4809242/diff`
  
2. `# buildah umount ef4c0f3b3e53 4d8ec97bb4b1`
`too many arguments specified`
  
3. `# buildah umount ef4c0f3b3e53`

**Describe the results you received:**
Unable to provide multiple mounts to `umount`, error `too many arguments specified` resulted.

**Describe the results you expected:**
Ability to `umount` multiple mounts consistent with behaviour of `rm` and `rmi` for containers and images.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.12-1.git8badcc2.el7.x86_64
```

**Output of `buildah version`:**

```
buildah version 0.12 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Comment by TomSweeneyRedHat** [comment]
@pixdrift I like the thought, will see if there's any hiccups to pulling it off.

**Comment by pixdrift** [comment]
Thanks @TomSweeneyRedHat 🍺

Tested in latest build and it is working great.

Happy to close this unless you are waiting for other confirmation?

**Comment by TomSweeneyRedHat** [comment]
Th @pixdrift!  Will close this out now, I left it open to give you a chance to test/confirm.
