### ISSUE TITLE
selinux issue when writing in container with 'buildah run'

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#549]
**Description**
I have come across multiple (what appear to be) SELinux issues when running `buildah run` which I am trying to narrow down. I initially had SELinux permission denied errors on an OL7 system, and have since built a clean CentOS 7 VM in an attempt to create a reproducer to post here. 

**Steps to reproduce the issue:**
1. I have created 'clean' ext4 mount for buildah specific directories to reproduce/isolate the issue, this includes creating the following directories:
`/var/lib/buildah/storage`
`/var/run/buildah/storage` (tmpfs /run/buildah/storage)

The permissions on these directories were configured to match the existing `containers` directories using `chcon --reference`
  
Specifically:  
`unconfined_u:object_r:container_var_lib_t:s0`
`unconfined_u:object_r:container_var_run_t:s0`

The buildah configuration was updated in:
`/etc/containers/storage.conf`

With the following configuration:
`runroot = /var/run/buildah/storage`
`graphroot = /var/run/buildah/storage`

2. Build an image from `scratch`

3. Attempt to run any command in the container with SELinux enabled / enforcing
`# buildah run working-container -- touch /tmp/myfile`
`touch: cannot touch '/tmp/myfile': Permission denied`
`# setenforce 0`
`# buildah run working-container -- touch /tmp/myfile`
`(works successfully)`

**Describe the results you received:**
Error writing to filesystem, AVC denial.
`type=AVC msg=audit(1522760070.369:257): avc:  denied  { write } for  pid=3851 comm="touch" name="tmp" dev="dm-5" ino=132685 scontext=system_u:system_r:svirt_lxc_net_t:s0:c263,c706 tcontext=system_u:object_r:tmp_t:s0 tclass=dir`

**Describe the results you expected:**
Successful execution of command without disabling SELinux

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.12-1.git8badcc2.el7.x86_64
```

**Output of `buildah version`:**

```
Version:       0.12
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    8badcc2
Built:         Tue Feb 13 07:35:11 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.4.1708 (Core)
```

**Output of `uname -a`:**

```
3.10.0-693.21.1.el7.x86_64 #1 SMP Wed Mar 7 19:03:37 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `rpm -q selinux-policy`:**

```
selinux-policy-3.13.1-166.el7_4.9.noarch
```

**Output of `rpm -q runc`:**

```
runc-1.0.0-27.rc5.dev.git4fc53a8.el7.centos.x86_64 (built from upstream, rc4 shows same behaviour)
```

**Output of `cat /etc/containers/storage.conf`:**

```
 storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
#runroot = "/var/run/containers/storage"
runroot = "/var/run/buildah/storage"

# Primary Read/Write location of container storage
#graphroot = "/var/lib/containers/storage"
graphroot = "/var/lib/buildah/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
Try 
semanage fcontext -a -e /var/lib/containers /var/lib/buildah
restorecon -R -v /var/lib/buildah

You changed the default labeling layout,  These commands should fix your issues.  Perhaps we should modify the man page in storage.conf to explain these commands.

**Comment by pixdrift** [comment]
Thanks for the response @rhatdan 

I didn't expect that the file context would need to be defined as buildah creates all contents below the `storage` levels. Understand if this is required for the new file creation and will keep it in mind in future.

That being said, the fcontext addition and resotorecon (although making modifications) didn't resolve the issue, but it has changed slightly:

The AVC denial now looks like this:
`type=AVC msg=audit(1522763209.848:319): avc:  denied  { write } for  pid=4596 comm="touch" name="tmp" dev="dm-5" ino=132685 scontext=system_u:system_r:svirt_lxc_net_t:s0:c263,c706 tcontext=system_u:object_r:container_share_t:s0 tclass=dir`

**Comment by rhatdan** [comment]
Is this a Centos or RHEL system?  What version of the OS and What version of container-selinux

This looks weird in that the write should be happening on the upper layer with overlay.

**Comment by rhatdan** [comment]
Looks like it is 7.4. 
rpm -q container-selinux

**Comment by pixdrift** [comment]
CentOS 7.4
`container-selinux-2.42-1.gitad8f0f7.el7.noarch`

**Comment by pixdrift** [comment]
I see the virt7-container-common-candidate repo has a newer container-selinux
`container-selinux-2.54-1.el7.noarch`

Curiously though, it looks newer than the newest tagged release in the git repo.

https://github.com/projectatomic/container-selinux/tags

**Comment by rhatdan** [comment]
If you run buildah without changing the default location does it work fine with SELinux?

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Tom do you have a handy centos box that you could try this with buildah to see if you get the same problems?

**Comment by TomSweeneyRedHat** [comment]
@rh-atomic-bot I don't, I was fighting space issues and burned the vm and the kit .

**Comment by rhatdan** [comment]
Ok maybe try it on Fedora and see if you have issues there?

**Comment by TomSweeneyRedHat** [comment]
Will do

**Comment by rhatdan** [comment]
Why not mount the new disk on /var/lib/containers/ then?  BTW I don't think the placement is the issue. I am clueless what is going on now.

When you mount a container could you put in the in 
```
mount | grep overlay
```

**Comment by pixdrift** [comment]
@rhatdan, the reason I chose /var/lib/buildah is that systems I am adding buildah to are existing shared systems and `containers` was ambiguous when others are using existing docker config on the same system, I didn't want the potential confusion.

That aside, in this test VM I created a new ext4 mount, mounted it in  `/var/lib/containers` (started fresh). Updated `/etc/containers/storage.conf` and same result:

```
# buildah run working-container -- touch /tmp/randomfile
touch: cannot touch '/tmp/randomfile': Permission denied
```

**Comment by rhatdan** [comment]
Could you do a 
buildah mount working-container
And then see what overlay says?

**Comment by pixdrift** [comment]
The 0.11 is from CentOS extras
http://mirror.centos.org/centos/7/extras/x86_64/Packages/

The 0.12 is from here (used to create above output):
https://cbs.centos.org/repos/virt7-container-common-candidate/x86_64/os/Packages/

**Comment by pixdrift** [comment]
@rhatdan, can you comment on the `SELinux: mount invalid` above. This message is returned in dmesg as result of the `buildah run` commands that attempt filesystem writes.

**Comment by rhatdan** [comment]
Those are issues with runc, and can be ignored.
Could you build buildah from git and see if it works.

**Comment by pixdrift** [comment]
Yep, will do.

**Comment by TomSweeneyRedHat** [comment]
Maybe I messed up something, but I got a different error on F27.

```
# chcon --reference /var/lib/containers/storage /var/lib/buildah/storage
# ls -alFZ !$
ls -alFZ /var/lib/buildah/storage
total 0
drwxr-xr-x. 2 root root unconfined_u:object_r:container_var_lib_t:s0  6 Apr  3 19:02 ./
drwxr-xr-x. 3 root root unconfined_u:object_r:var_lib_t:s0           21 Apr  3 19:02 ../

# chcon --reference /run/buildah /var/run/buildah/storage
# ls -alFZ /var/run/buildah/storage
total 4
drwxr-xr-x. 8 root root unconfined_u:object_r:var_run_t:s0 180 Apr  3 19:23 ./
drwxr-xr-x. 3 root root unconfined_u:object_r:var_run_t:s0  60 Apr  3 19:03 ../
drwx------. 2 root root unconfined_u:object_r:var_run_t:s0  40 Apr  3 19:23 mounts/
drwx------. 4 root root unconfined_u:object_r:var_run_t:s0  80 Apr  3 19:23 overlay/
drwx------. 3 root root unconfined_u:object_r:var_run_t:s0 100 Apr  3 19:23 overlay-containers/
drwx------. 2 root root unconfined_u:object_r:var_run_t:s0  60 Apr  3 19:23 overlay-images/
drwx------. 2 root root unconfined_u:object_r:var_run_t:s0 100 Apr  3 19:23 overlay-layers/
-rw-------. 1 root root unconfined_u:object_r:var_run_t:s0  64 Apr  3 19:23 storage.lock
drwx------. 2 root root unconfined_u:object_r:var_run_t:s0  40 Apr  3 19:23 tmp/

# cat /etc/containers/storage.conf
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
# runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
# graphroot = "/var/lib/containers/storage"

runroot = "/var/run/buildah/storage"
graphroot = "/var/run/buildah/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"

# buildah from scratch
working-container

# buildah run working-container -- touch /tmp/myfile
/var/run/buildah/storage/overlay/dd3e2670d45f9825b6bf1814d1cca3db69d21b603e3a453e4418a740c2e10682/merged is not an absolute path or is a symlink

# buildah version
Version:       0.15
Go Version:    go1.9.4
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    d1330a5
Built:         Tue Feb 27 08:05:39 2018
OS/Arch:       linux/amd64

(Latest Buildah from dnf install, not a git built version)
```

Will play more in the morning.

**Comment by pixdrift** [comment]
Where is buildah 0.15 coming from? This repo only shows tagged releases to 0.12. Can we get the tags/releases updated in this repo for newer versions? (happy to raise a new issue)

**Comment by pixdrift** [comment]
Have built a new package off the latest commit 5ce8009

```
# rpm -qa | grep buildah
buildah-0.15.1-1.git5ce8009.el7.x86_64
```

Small hurdle with first test.
```
# buildah run working-container -- touch /tmp/myfile
Invalid format on container you must recreate the container
```

After rebuilding the container I am happy to report it has resolved the issue:
```
# buildah run working-container -- touch /tmp/myfile
# buildah run working-container -- ls /tmp
myfile
```

**Comment by rhatdan** [comment]
Ok it looks like it is time to cut buildah-0.1.16
I wanted to wait for chain builds.  But...

**Comment by pixdrift** [comment]
@rhatdan, sounds good for all of us still clinging to 'archaic' EL7 😉

**Comment by rhatdan** [comment]
EL7 pays my salary, so keep clinging.

**Comment by TomSweeneyRedHat** [comment]
@pixdrift the Buildah v0.15 came from the Fedorar Repository. I just did a "dnf  install" on a new Fedora 27 machine, I didn't have CentOS super handy.

**Comment by pixdrift** [comment]
Cheers @TomSweeneyRedHat, was just trying to track down (as an RH outsider) the pipeline that led to it ending up in the Fedora 27 repo as the v0.15 release isn't tagged in this repo and I thought the tagging may trigger to build. I have since found the source was updated to 0.15 but not the release tags (raised issue #550 for this)

**Comment by rhatdan** [comment]
@pixdrift I updated that stuff yesterday.
