### ISSUE TITLE
'buildah commit {ctrid}' doesn't create image.

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#555]
**Description**

The `buildah commit {ctrid}` command fails with an "ImageId is required" message and should instead create an image with the name of `<None>` to emulate what other container technologies do.

**Steps to reproduce the issue:**
1.  buildah from alpine
2. buildah conifig --author="Tom Sweeney"
3.  buildah commit {containersId from `buildah containers`}

**Describe the results you received:**
```
# buildah commit a07bd79673d9
an image name must be specified
```

**Describe the results you expected:**
An image with the name `<None>` should have been created.

**Output of `buildah version`:**

```
# buildah version
Version:       0.15
Go Version:    go1.9.4
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    fb367e4
Built:         Thu Mar 29 19:59:01 2018
OS/Arch:       linux/amd64

```

**Output of `cat /etc/*release`:**

```
# cat /etc/*release
Fedora release 27 (Twenty Seven)
NAME=Fedora
VERSION="27 (Server Edition)"
ID=fedora
VERSION_ID=27
PRETTY_NAME="Fedora 27 (Server Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:27"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=27
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=27
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
Fedora release 27 (Twenty Seven)
Fedora release 27 (Twenty Seven)

```

**Output of `uname -a`:**

```
# uname -a
Linux localhost.localdomain 4.15.13-300.fc27.x86_64 #1 SMP Mon Mar 26 19:06:57 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by rhatdan** [comment]
I just tried this on docker and it works the way you describe.

podman commit also requires a tag name.

**Comment by rhatdan** [comment]
I played around with this for a few minutes and decided it is too hard, and of limited value, if any.
I think we should require an image name.
