### ISSUE TITLE
'tarball' not a supported transport for buildah push

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#557]
**Description**
The inline help for `buildah push` suggests that tarball is a valid transport for the destination, but this isn't the case. Additionally, the error message when specifying `tarball` for the destination transport is ambiguous.

**Steps to reproduce the issue:**
1. `# buildah push --help`
```
DESCRIPTION:

   Pushes an image to a specified location.

   The Image "DESTINATION" uses a "transport":"details" format.

   Supported transports:
   containers-storage, dir, docker, docker-archive, docker-daemon, oci, oci-archive, ostree, **tarball**
```

2. `#  buildah push 74a4ffb80cef tarball:/tmp/74a4ffb80cef.tar`
`error opening "/tmp/74a4ffb80cef.tar": open /tmp/74a4ffb80cef.tar: no such file or directory`

3.  `# buildah push 74a4ffb80cef tarball:/tmp/`
`error pushing image "74a4ffb80cef" to "tarball:/tmp/": error copying layers and metadata: Error initializing destination tarball:/tmp/: "tarball:" locations can only be read from, not written to`

**Describe the results you received:**
Error that the tarball doesn't already exist.
Error that tarball transport can only be read from, not written to.

**Describe the results you expected:**
Ideally, have the export write a tarball of the image to the filesystem. If this isn't desired functionality, the inline help just needs a minor adjustment and possibly the code that catches the error.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.16-1.git82529cd.el7.x86_64
```

**Output of `buildah version`:**

```
Version:       0.16
Go Version:    go1.9.2
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    82529cd
Built:         Thu Apr  5 00:40:47 2018
OS/Arch:       linux/amd64
```

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by umohnani8** [comment]
@rhatdan I don't think we support pushing to a tarball. The tarball transport was created to just read in the tar file of an exported container and save it as an image. I don't see a "destination" part for the tarball transport, @nalind please correct me if I am wrong.

**Comment by rhatdan** [comment]
We might need to fix the inline help and man page to make this more clear.

**Comment by umohnani8** [comment]
Being fixed in https://github.com/containers/image/pull/437 will vendor once it is accepted.

**Comment by pixdrift** [comment]
Rather than remove it, is there an opportunity to support it as a method of export?

I can raise that separately as an enhance request as I would find it useful.

**Comment by rhatdan** [comment]
I think podman save or podman export (Never can remember the difference) can do this now.

**Comment by pixdrift** [comment]
@rhatdan, what's the future view for the crossover between the tools? My expectation was that podman was for pod specific operations, and buildah for container operations. If I wanted to export just a container (ie. act on a container, not a pod) I would assume buildah was the tool to use?

Appreciate any/all feedback on this.

**Comment by rhatdan** [comment]
Podman is for all container/pod operations, while buildah is for building container/images.
I see eventually a lot of this code merging, as we have begun to do.

**Comment by pixdrift** [comment]
@rhatdan, thanks for the clarification.

**Comment by umohnani8** [comment]
@rhatdan podman export is used to save a container's filesystem (mounts the container and copies everything under it to a tar file) as a tar file, and the `tarball` transport is used to read in this saved container filesystem and save it as an image. I believe that is why we don't support it for pushing images. We have docker-archive and oci-archive for images, which support two different image specs (v2s2 and oci).

**Comment by pixdrift** [comment]
@umohnani8, buildah currently supports export to dir, it wouldn't be much of a jump to go from dir -> tarball?

**Comment by umohnani8** [comment]
@pixdrift a quick clarification. What exactly is your desired output with pushing images using the tarball transport. Do you expect to see the layers, manifest, and config in the tar file - something like this:
```
cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215.tar
3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353.json
cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215/layer.tar
cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215/VERSION
cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215/json
repositories
manifest.json
```

or you expect to see a tarred up filesystem, something like:
```
usr/share/man/
usr/share/misc/
var/
var/cache/
var/cache/apk/
var/cache/misc/
var/empty/
var/lib/
```

**Comment by pixdrift** [comment]
@umohnani8, no major preference, was going to say just a tar'd version of `dir` output. Unfortunately, push to dir is blowing up for me at the moment.. going to take a closer look tonight and see why.

**Comment by nalind** [comment]
@pixdrift I think what you're describing is what the `docker-archive:` target produces now, give or take the format used for the manifest and config blobs.

My personal expectation for how a `tarball:` destination would work would be that writing to a `tarball:` destination would produce something that could be consumed as `tarball:` source.  That's generally the case for transports that the image library (which does the heavy lifting for pulling and pushing images) supports as both source and destinations.  I think for now it makes sense to document that it isn't implemented as a destination type (perhaps with a pointer to `podman export`), and correct the documentation later if/when we get an implementation of it in the image library.

**Comment by umohnani8** [comment]
inline help fixed in #583

**Comment by pixdrift** [comment]
Cheers @umohnani8 👍

**Comment by pixdrift** [comment]
Sorry to re-open, but I really want to revisit this export to tarball option given that some time has passed and i've been left looking for this feature again.

The primary use case I see for it is potentially using buildah to create filesystems for qcow2 vm images, Raspberry Pi OS images etc. Essentially making this feature just a tarball of the container filesystem (all layers merged).

I guess this can be achieved by mounting the container image and creating tarball/copying from there, I assume that is the preferred approach over adding the feature to the tool?

**Comment by rhatdan** [comment]
Can you use podman save to do this?
