### ISSUE TITLE
cannot save image with empty image.ref.name

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#558]
**Description**
When attempting to use `buildah push` to `oci` or `oci-archive` an error message is displayed regarding empty `image.ref.name`.

**Steps to reproduce the issue:**
1. Follow documented method to buildah push to oci (https://github.com/projectatomic/buildah/blob/master/docs/buildah-push.md)

```
# buildah push 74a4ffb80cef oci:/tmp/imgdump
error pushing image "74a4ffb80cef" to "oci:/tmp/imgdump": error copying layers and metadata: Error initializing destination oci:/tmp/imgdump:: cannot save image with empty image.ref.name
```

2.
```
# buildah push 74a4ffb80cef oci-archive:/tmp/74a4ffb80cef
error pushing image "74a4ffb80cef" to "oci-archive:/tmp/74a4ffb80cef": error copying layers and metadata: Error initializing destination oci-archive:/tmp/74a4ffb80cef:: cannot save image with empty image.ref.name
```

**Describe the results you received:**
Error regarding empty `image.ref.name`

**Describe the results you expected:**
Export of OCI formatted image to provided directory.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.16-1.git82529cd.el7.x86_64
```

**Output of `buildah version`:**

```
buildah version 0.16 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `rpm -q runc`:**

```
runc-1.0.0-26.rc4.dev.git9f9c962.el7.x86_64
```

**Comment by pixdrift** [comment]
Attempted to set the following annotation:
`org.opencontainers.image.ref.name`

From the OCI spec here:
https://github.com/opencontainers/image-spec/blob/master/annotations.md

But it didn't resolve the issue. Is there a change in something that buildah calls?

**Comment by rhatdan** [comment]
@umohnani8 PTAL

**Comment by umohnani8** [comment]
Under `Destination` on the man page (https://github.com/projectatomic/buildah/blob/master/docs/buildah-push.md) it is stated that to push to oci the syntax must be `oci:path:tag`. The example later in the man page is misleading as it doe not have the `:tag`. Will open a PR to fix the documentation.

**Comment by pixdrift** [comment]
I think there is more that just a documentation fix here, the syntax should be checked before attempting the execution.

**Comment by pixdrift** [comment]
My concern is `image.ref.name` doesn't mean anything to the user in this context. The other argument is that the number of transports in buildah is fairly limited, and it would amount to essentially regex validation of the input in buildah before passing to the transport? Could the regex be defined as part of each of the transport definition/pluginss in buildah?

**Comment by umohnani8** [comment]
The error message for oci and oci-archive is being reworded here https://github.com/containers/image/pull/439. docker-archive and dir already return a more detailed error message.

**Comment by pixdrift** [comment]
Thanks @umohnani8
