### ISSUE TITLE
entrypoint behaviour inconsistent between 'buildah run' and 'docker run'

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#564]
**Description**
When an entrypoint is defined in docker, the parameter passed in `docker run` is interpreted as a parameter to be passed to the entrypoint script/executable. With `buildah run`, the parameter is always interpreted as a command to execute, overwriting the configured container entrypoint.

**Steps to reproduce the issue:**
1. Build an image with an entrypoint script that expects input parameters
```
cat ${scratchmnt}/root/entrypoint.sh
#!/bin/bash
echo Input: ${1}
```

2. Configure the entrypoint script as the entrypoint of the container
`buildah config --entrypoint /root/entrypoint.sh ${newcontainer}`

3. Build the container and attempt to pass a parameter to the entrypoint using `buildah run`
```
buildah run working-container myparameter
container_linux.go:348: starting container process caused "exec: \"myparameter\": executable file not found in $PATH"
```

4. Export to docker and execute the same container with `docker run` passing parameter
```
docker run buildah:entrypoc myparameter
Input: myparameter
```

**Describe the results you received:**
When executing with `buildah run` the input parameter replaces the configured entrypoint value of the container and buildah attempts to call an executable with this name.

**Describe the results you expected:**
Execute `buildah run` with a parameter and it is then passed as a parameter to the configured container entrypoint script/executable.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.16-1.git82529cd.el7.x86_64
```

**Output of `buildah version`:**

```
Version:       0.16
Go Version:    go1.9.2
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    82529cd
Built:         Thu Apr  5 00:40:47 2018
OS/Arch:       linux/amd64
```

**Comment by pixdrift** [comment]
This came up when I was looking at replicating apb-base capability using buildah, which uses parameters in the enrypoint script:
https://github.com/ansibleplaybookbundle/apb-base/blob/master/files/usr/bin/entrypoint.sh

**Comment by rhatdan** [comment]
@pixdrift Are you planning on opening a PR to fix this?

**Comment by pixdrift** [comment]
@rhatdan, no, just raising the issue and providing the reproducer.

**Comment by ripcurld** [comment]
@pixdrift @rhatdan should we label this as a bug?

**Comment by rhatdan** [comment]
Ok thanks.  I will have @TomSweeneyRedHat Look into this.

**Comment by rhatdan** [comment]
I would say this is a bug,  yes.

**Comment by pixdrift** [comment]
The penny just dropped on why this issue got the special bug treatment, Buildah is now fully supported in RHEL, and 15.1 is bundled in RHEL 7.5. Thanks to everyone involved in getting it included/supported so quickly.

**Comment by pixdrift** [comment]
I don't go.. but it looks like the issue might be here
https://github.com/projectatomic/buildah/blob/master/run.go#L331-L343

If `command` exists it is used and doesn't fall through to the container cmd/entrypoint checks which is what preserves the entrypoint if it exists.

**Comment by TomSweeneyRedHat** [comment]
@pixdrift Thanks for working on this bug, we very much appreciate the contribution.  However before working on a bug please assign it to yourself, or if already assigned, let the person assigned know that you're grabbing it.

**Comment by pixdrift** [comment]
@TomSweeneyRedHat ack

**Comment by pixdrift** [comment]
Thanks to @TomSweeneyRedHat @rhatdan @ripcurld for the assistance, much appreciated. I'll hopefully not need the bumper rails as much next time round. 👍
