### ISSUE TITLE
Error target is unknown on docker pull for image pushed with buildah

### ISSUE THREAD

**Issue by gregoryboue** [projectatomic/buildah#575]
**Description**

I build an image with *buildah bud* then i push it to a private registry with a *buildah push* command.

The image is visible on registry GUI, and i can list the tag with the endpoint : https://myregistry/v2/MY_IMAGE_NAME/tags/list.

When i try a *docker pull* command i have this message : ` Error response from daemon: target is unknown`

**Note** : It's possible to pull the image with *buildah from* but not with *docker pull*

**Steps to reproduce the issue:**
1. Build an image with *buildah bud*...
2. Push an image to a private registry (nexus3) with `buildah push --creds=${CRED} MY_IMAGE_ID docker://MY_IMAGE_NAME_AND_TAG`
3. Docker login and Pull an image from Docker version 17.03.1-ce, build c6d412e daemon : `docker pull MY_IMAGE_TAG`

**Describe the results you received:**

Error from daemon docker logs :
```
level=debug msg="Calling POST /v1.27/images/create?fromImage=MY_IMAGE_NAME_AND_TAG"
level=debug msg="hostDir: /etc/docker/certs.d/MYREGISTRY"
level=debug msg="hostDir: /etc/docker/certs.d/MYREGISTRY"
level=debug msg="Trying to pull MY_IMAGE_NAME_AND_TAG from https://MYREGISTRY v2"
level=debug msg="Calling GET /v1.30/services"
level=debug msg="Calling GET /v1.30/tasks"
level=error msg="Error trying v2 registry: target is unknown"
level=error msg="Attempting next endpoint for pull after error: target is unknown"
level=debug msg="Skipping v1 endpoint https://MYREGISTRY because v2 registry was detected"
 level=error msg="Handler for POST /v1.27/images/create returned error: target is unknown"
```

**Describe the results you expected:**
Get the image pulled.

**Output of `buildah version`:**

```
Version:       0.16
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    82529cd
Built:         Fri Apr  6 10:15:58 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.3.1611 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.3.1611 (Core) 
CentOS Linux release 7.3.1611 (Core) 
```

**Output of `uname -a`:**

```
Linux jenkins-slave-d0dlw-t2n6l 3.10.0-693.11.6.el7.x86_64 #1 SMP Thu Dec 28 14:23:39 EST 2017 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by rhatdan** [comment]
@mtrmac @umohnani8 @TomSweeneyRedHat Any ideas?

**Comment by TomSweeneyRedHat** [comment]
@gregoryboue I wasn't able to duplicate this on my test vm.  I was using Fedora 28 and Docker/Buildah versions in my output below.

A couple of tweaks to your environment to try and narrow the problem down.  Can you upgrade Docker-ce?  I used a slightly newer version. My other thought was perhaps there's something with the private registry that's going on.  Can you try testing against docker.io (Docker Hub) or quay.io and see if that works for you?

If that's still no joy for you, I'll see if I can set up a private repository outside of Docker Hub and see if it's related there.

HTH's!


```
# docker login -u tomsweeneyredhat docker.io
Password: 
Login Succeeded


# buildah bud -t tomsweeneyredhat/testing:first .
STEP 1: FROM alpine
Getting image source signatures
Copying blob sha256:ff3a5c916c92643ff77519ffa742d3ec61b7f591b6b7504599d95a4a41134e28
 1.97 MiB / 1.97 MiB [======================================================] 0s
Copying config sha256:3fd9065eaf02feaf94d68376da52541925650b81698c53c6824d92ff63f98353
 1.48 KiB / 1.48 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
STEP 2: COMMIT containers-storage:[overlay@/var/lib/containers/storage+/var/run/containers/storage:overlay.override_kernel_check=true]docker.io/tomsweeneyredhat/testing:first
Getting image source signatures
Skipping fetch of repeat blob sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215
Copying blob sha256:4f4fb700ef54461cfa02571ae0db9a0dc1e0cdb5577484a6d75e68dc38e8acc1
 32 B / 32 B [==============================================================] 0s
Copying config sha256:0ad17db006e78df7bd52727f3d96c59eb1698efeb4f7fe6165b3ff4ebb557b97
 645 B / 645 B [============================================================] 0s
Writing manifest to image destination
Storing signatures

# buildah push tomsweeneyredhat/testing:first docker.io/tomsweeneyredhat/testing:first
Getting image source signatures
Copying blob sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215
 4.20 MiB / 4.20 MiB [======================================================] 1s
Copying blob sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef
 1.00 KiB / 1.00 KiB [======================================================] 0s
Copying config sha256:0ad17db006e78df7bd52727f3d96c59eb1698efeb4f7fe6165b3ff4ebb557b97
 645 B / 645 B [============================================================] 1s
Writing manifest to image destination
Copying config sha256:0ad17db006e78df7bd52727f3d96c59eb1698efeb4f7fe6165b3ff4ebb557b97
 0 B / 645 B [--------------------------------------------------------------] 0s
Writing manifest to image destination
Storing signatures

# docker version
Client:
 Version:      17.09.0-ce
 API version:  1.32
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:42:17 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.09.0-ce
 API version:  1.32 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   afdb6d4
 Built:        Tue Sep 26 22:43:42 2017
 OS/Arch:      linux/amd64
 Experimental: false

# docker pull docker.io/tomsweeneyredhat/testing:first
first: Pulling from tomsweeneyredhat/testing
ff3a5c916c92: Pull complete 
4f4fb700ef54: Pull complete 
Digest: sha256:184a1460ad7ff5a861e572da10087c32a60adc97fdb2a6df5694df483e24daec
Status: Downloaded newer image for tomsweeneyredhat/testing:first

# buildah version
Version:       0.16
Go Version:    go1.10
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    82529cd
Built:         Wed Apr  4 10:22:20 2018
OS/Arch:       linux/amd64
```

**Comment by pixdrift** [comment]
@gregoryboue, what are you using to provide the private registry?

**Comment by gregoryboue** [comment]
Yes the  private registry chose by my company for CI environment is nexus sonatype 3

**Comment by gregoryboue** [comment]
It seems to work with portus but the image is notre display from Portus GUI

**Comment by TomSweeneyRedHat** [comment]
@gregoryboue I've not used nexus3 before myself, will see if I can dig one up to try.  In the mean time, were you able to try a newer version of Docker-ce to see if it's still reproducing?  Also if you push the image initially using Docker 1.11.0, do you get the same error when you try to pull it using Docker version 17.03.1-ce?

**Comment by gregoryboue** [comment]
@TomSweeneyRedHat 

I did the following : 

1. buildah bud...
2. buildah push MY_IMAGE
3. (docker 1.11.0) : docker pull
4. (docker 1.11.0) : docker tag
5. (docker 1.11.0) : docker push
6. (docker 17.03.1-ce) : docker pull

the docker pull works, i haven't environment with a newer version of docker-ce i will try to get one.

Thanks

**Comment by gregoryboue** [comment]
@TomSweeneyRedHat I had news elements.

When i browse the assets which correspond to the manifests image file in Nexus 3 I can see the following :

The manifest of an image pushed by docker push command looks like this : 

```
{
   "schemaVersion": 2,
   **"mediaType": "application/vnd.docker.distribution.manifest.v2+json",**
   "config": {
      "mediaType": "application/vnd.docker.container.image.v1+json",
      "size": 6410,
      "digest": "sha256:23d1c505e127930cae6d0540a6c8ecfd7f59fc1c674f86343c9b54233e47ea23"
   },
   "layers": [
      {
         "mediaType": "application/vnd.docker.image.rootfs.diff.tar.gzip",
         "size": 52608519,
         "digest": "sha256:f2b6b4884fc8b2f1fcef843f92f7c82c9c149df85ac77e5f0de7a342ae442412"
      },...
```

The manifest of an image pushed by buildah push command looks like this : 

```
{  
   "schemaVersion":2,
   "config":{  
      "mediaType":"application/vnd.oci.image.config.v1+json",
      "digest":"sha256:23d1c505e127930cae6d0540a6c8ecfd7f59fc1c674f86343c9b54233e47ea23",
      "size":6410
   },
   "layers":[  
      {  
         "mediaType":"application/vnd.oci.image.layer.v1.tar",
         "digest":"sha256:f2b6b4884fc8b2f1fcef843f92f7c82c9c149df85ac77e5f0de7a342ae442412",
         "size":52608519
      },
```

The main difference is the missing mediaType attribute at the top level of the json object, I think this is responsible for the docker pull error.

Is this helps you ?

Thanks

**Comment by mtrmac** [comment]
> The main difference is the missing mediaType attribute at the top level of the json object, I think this is responsible for the docker pull error.

Yeah, this confirms my guess:
> either the registry is returning an invalid Content-Type, or maybe the registry supports OCI, buildah has created an OCI image, and Docker does not recognize it.

the two manifests differ in that one is Docker schema2 and the other is OCI.

It would still be useful to verify what `Content-Type` header is returned when fetching the manifest, to determine whether the bug is in the registry, the client, or both.  https://github.com/moby/moby/issues/30083 suggests that the client’s behavior has supposedly been fixed since.

(See #505 for a somewhat related discussion, but focused on docker/distribution; the registry in this case is clearly behaving differently.

**Comment by gregoryboue** [comment]
@mtrmac the content-type header returned has the following value : 
**application/vnd.docker.distribution.manifest.v1+json**

It should be **application/vnd.oci.image.config.v1+json** ?

Is the problem come from Nexus registry or from buildah ?

**Comment by mtrmac** [comment]
> @mtrmac the content-type header returned has the following value :
application/vnd.docker.distribution.manifest.v1+json

That’s definitely not correct.

> It should be application/vnd.oci.image.config.v1+json

Yes.

> Is the problem come from Nexus registry or from buildah ?

For _this particular subproblem_, I’d bet on the registry; the way to tell for sure would be to see the `Content-Type` set by `buildah` when uploading the manifest.

---

It’s not just returning the correct `Content-Type`, though: if Docker asks for a manifest and specifies that it does not support OCI, and the registry only has an OCI manifest, it must on-the-fly convert it into one of the supported formats.  If the registry can’t even recognize the OCI format enough to return the right `Content-Type` (or to reject the input if `buildah` were sending an invalid `Content-Type`), it’s highly unlikely that the conversion code exists.

I think that would be something to talk about with the vendor

**Comment by mtrmac** [comment]
> > It should be application/vnd.oci.image.config.v1+json

> Yes.

For the manifest, `application/vnd.oci.image.manifest.v1+json` actually.

**Comment by gregoryboue** [comment]
@mtrmac ok I understand.

This is the request when buildah push the manifest :

```
PUT //docker-XXXXX/v2/test/build-docker/manifests/0.4-SNAPSHOT HTTP/1.1
User-Agent: Go-http-client/1.1
Content-Length: 496
Authorization: Bearer DockerToken.48158b78-72a0-3bb7-ba67-b742XXXXX24
Content-Type: application/vnd.oci.image.manifest.v1+json
Docker-Distribution-Api-Version: registry/2.0
Accept-Encoding: gzip
Connection: close
Host: docker-XXXXX
X-Forwarded-Host: docker-XXXXX
X-Forwarded-Port: 443
X-Forwarded-Proto: https
Forwarded: for=1XXXXX;host=docker-XXXXX;proto=https
X-Forwarded-For: 1XXXXX
```

And the response From Nexus : 

```
201 null HTTP/1.1
Connection: close
Date: Wed, 25 Apr 2018 11:11:28 GMT
Server: Nexus/3.6.0-02 (OSS)
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Docker-Distribution-Api-Version: registry/2.0
Last-Modified: Wed, 25 Apr 2018 11:11:28 GMT
Docker-Content-Digest: sha256:a4869aba816cb490482be506ad0eade677f7597968a6ac2df218fb95a3f3a47a
Content-Type: application/vnd.docker.distribution.manifest.v2+json
Content-Length: 496
```

So it means that the content type application/vnd.oci.image.manifest.v1+json is not managed by the registry ?

**Comment by mtrmac** [comment]
@gregoryboue Thanks for the logs.

This confirms that buildah creates an OCI manifest, the Nexus registry (presumably) accepts it, but then returns it using a Docker schema2 `Content-Type`. That ultimately needs to be fixed in Nexus, either to reject OCI input as unrecognized, or to return it correctly (maybe converting to other formats if the client does not support reading OCI).

It seems, though, that `buildah` can be forced to upload using the Docker schema2, using something like `buildah bud --format=docker`. That could be a workaround in the meantime.

**Comment by gregoryboue** [comment]
@mtrmac I opened an issue on Sonatype Nexus JIRA, and yes the --format docker solve the problem so I will use this workaround

**Comment by rhatdan** [comment]
Ok I don't see this as an issue with buildah so I am closing.  Reopen if you disagree.
