### ISSUE TITLE
README: invalid command to write lighttpd.sh 

### ISSUE THREAD

**Issue by alban** [projectatomic/buildah#579]
**Description**

The shell command with the "here document" (`cat > lighttpd.sh <<EOF`) does not work because it includes back ticks that are executed in place rather then being inserted as in in the `lighttpd.sh` file.

**Steps to reproduce the issue:**
1. Copy paste the lines from the README in a terminal

**Describe the results you received:**
```
$ cat > lighttpd.sh <<EOF
> #!/bin/bash -x
> 
> ctr1=`buildah from ${1:-fedora}`
> 
> ## Get all updates and install our minimal httpd server
> buildah run $ctr1 -- dnf update -y
> buildah run $ctr1 -- dnf install -y lighttpd
> 
> ## Include some buildtime annotations
> buildah config --annotation "com.example.build.host=$(uname -n)" $ctr1
> 
> ## Run our server and expose the port
> buildah config $ctr1 --cmd "/usr/sbin/lighttpd -D -f /etc/lighttpd/lighttpd.conf"
> buildah config $ctr1 --port 80
> 
> ## Commit this container to an image name
> buildah commit $ctr1 ${2:-$USER/lighttpd}
> EOF
mkdir /var/lib/containers/storage: permission denied
mkdir /var/lib/containers/storage: permission denied
$ grep ^ctr1 lighttpd.sh 
ctr1=
$
```
**Describe the results you expected:**

The command `buildah from ${1:-fedora}` should be inserted in `lighttpd.sh` rather than trying to execute it (and failing because I'm not root).

**Comment by pixdrift** [comment]
@alban, if you wrap the EOF in double quotes it should fix it

`cat > lighttpd.sh <<"EOF"`

Can you confirm? and I will sort out a PR tonight.

**Comment by alban** [comment]
@pixdrift yes, it worked fine with "EOF" in double quotes. Thanks!

**Comment by alban** [comment]
https://github.com/projectatomic/buildah/commit/45a4b816d730dee992616d737617e2957ff3d1d9 fixes this. It is now merged in master.
