### ISSUE TITLE
Documentation: buildah run documentation doesn't describe valid flags for --volume option

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#588]
**Description**
The documentation for `buildah run` describes a `flags` element of the `--volume` command but doesn't provide a list of flags or a method to retrieve a list.

**Steps to reproduce the issue:**
1. Browse to documentation for buildah run
[https://github.com/projectatomic/buildah/blob/master/docs/buildah-run.md](https://github.com/projectatomic/buildah/blob/master/docs/buildah-run.md)

**Describe the results you received:**
No information relating to supported `flags` for the `--volume` option

**Describe the results you expected:**
Documented list of flags, or a documented method to retrieve a list of supported flags.

**Comment by umohnani8** [comment]
That is a mistake, should be `options` not flags. Will update and add more info and an example.

**Comment by umohnani8** [comment]
Fixed in #643
