### ISSUE TITLE
buildah-config: OCI spec v1.0.1 Config:Properties and Annotations

### ISSUE THREAD

**Issue by taqtiqa-mark** [projectatomic/buildah#597]
This issue arises in the context of issues #591 and #595.

The current OCI spec (v1.0.1) leaves discretion for which of the [annotations](https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#pre-defined-annotation-keys) are exposed to the user and where.

The [Config:Properties](https://github.com/opencontainers/image-spec/blob/v1.0.1/config.md#properties) part of the spec doesn't have an annotations item, nor does it expose all the possible annotation items as config items (some do seem to map but in ways that are inconsistent, e.g. `author` (config:property) and `authors` (annotation)).

@rhatdan : What will buildah do? 

My vote: Expose the annotation items explicitly through `builah config`. Remove `buildah config --labels`

Reasons:
The end user doesn't get any functionality from knowing that `buildah config --version=0.1.2` is an annotation item that maps to **org.opencontainers.image.version**.

It does look like the [v1.0.1 spec suggests deprecating](https://github.com/opencontainers/image-spec/blob/v1.0.1/annotations.md#back-compatibility-with-label-schema) the `buildah config --labels`.

**Comment by taqtiqa-mark** [comment]
Hmm, things seem to be in the OCI v1.0.1 spec and in a state of flux/transition.....

@rhatdan and @TomSweeneyRedHat you may be able to give buildah's view on the implementation / transition details in the questions @wtking [raised](https://github.com/opencontainers/image-spec/pull/745#issuecomment-382115515).

I'll update the table in #591 with my opinion on what would be useful in the scripting scenarios I am using acbuild/buildah in.

**Comment by rhatdan** [comment]
@taqtiqa-mark @nalind recently merged in support for annotations.  Do we need anything additionaly?
