### ISSUE TITLE
`buildah bud --rm -t webserver .` fails

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#598]
**Description**

docker has this command: `docker build --rm -t webserver .` which if you replace docker with 'buildah' your receive the error:

Incorrect Usage: flag provided but not defined: -rm

If we're not going to support this, we should at least provide an error message which tells the user how to make it so.

Reported/Requested by @dustymabe

**Output of `buildah version`:**

Buildah v0.16

**Comment by rhatdan** [comment]
We should support it.

**Comment by pixdrift** [comment]
@rhatdan, if this does match default buildah behaviour, would there be benefit in having a noop for the `--rm` for the time being, and then implementing `--rm=false` when the layer caching is implemented in #601?. This would improve compatibility in the short term while the caching capability is developed.

**Comment by rhatdan** [comment]
Sure Open a PR...

**Comment by rhatdan** [comment]
I'm closing this since I believe we cover this in other issues.
