### ISSUE TITLE
buildah bud needs to support caching.

### ISSUE THREAD

**Issue by rhatdan** [projectatomic/buildah#601]
Add a flag to 
buildah bud --cache ...

This flag will cause buildah bud to act like docker build, in that every Dockerfile command will create a layer in and record the command used to layer.  Then if you run it a second time, it will check each command before actually executing it, if it matches an existing layer, then it will not be executed.  If does not match then the command will execute and all further commands will execute.

**Comment by umohnani8** [comment]
Implemented in #767
