### ISSUE TITLE
buildah version: strconv.ParseInt: parsing "": invalid syntax

### ISSUE THREAD

**Issue by taqtiqa-mark** [projectatomic/buildah#612]
**Description**

`buildah version` breaks scripts by exiting with `$? = 1` 

**Steps to reproduce the issue:**
1. Build from sources (22 April 2018)
2. `buildah version` 

**Describe the results you received:**
````bash
strconv.ParseInt: parsing "": invalid syntax
````

**Describe the results you expected:**
````bash
buildah version 0.16 (image-spec 1.0.0, runtime-spec 1.0.0)
````

**Output of `apt list buildah`:**
```
buildah/xenial 0.16-1~ubuntu16.04.2~ppa5 amd64
```

**Output of `buildah version`:**
```
strconv.ParseInt: parsing "": invalid syntax
```

**Output of `cat /etc/*release`:**

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.4 LTS"
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.4 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

```

**Output of `uname -a`:**

```
Linux hedge-p2-1320a 4.4.0-119-generic #143-Ubuntu SMP Mon Apr 2 16:08:24 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary read-write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional read-only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers (currently overlay, zfs, vfs, btrfs)
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
This is really odd.  Version is failing as it can't parse the system date at build time.  I don't have a Ubuntu vm handy, could you try:

date=$(date +%s)
echo $date

and let me know if that spits out a value other than nil or zero @taqtiqa-mark?  Thanks!

**Comment by taqtiqa-mark** [comment]
````bash
$date=$(date +%s)
$ echo $date
1524355436
````

HTH?

**Comment by taqtiqa-mark** [comment]
@pixdrift Same system.
@TomSweeneyRedHat: Maybe "Buildah version not resolvable"?

In case it helps I can add the `buildah --version` works, so maybe `buildah version` can just be a proxy for `buildah --version`, and just have one code path for this information?

Suggest issue template be adjusted from `apt list buildah` to: `apt list --installed buildah`.  In this case the result is empty:
````bash
$ apt list --installed buildah
> Listing... Done
````

**Comment by taqtiqa-mark** [comment]
OK if you think its a build error, when I get time I'll rebuild and log the output.  

Any build flags you want set?  Maybe give the whole build instruction you'd like run.

**Comment by ripcurld** [comment]
That's really awkward. How the hell was `version` set to an empty string? :confused:

**Comment by TomSweeneyRedHat** [comment]
@ripcurld, that's the $64 question. 

@tatiqa-mark I don't know if there are any build flags that will be especially helpful, but I'd be interested in seeing the output.

**Comment by TomSweeneyRedHat** [comment]
Just to thicken the plot, I finally got a chance to spin up an Ubuntu vm this morning and installed by cutting/pasting the install instructions on the https://github.com/projectatomic/buildah/blob/master/install.md and the end results were:

```
root@ubuntutas:~/buildah/src/github.com/projectatomic/buildah# buildah version
Version:       0.16
Go Version:    go1.8.7
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    b16a1ea
Built:         Tue Apr 24 07:01:44 2018
OS/Arch:       linux/amd64
root@ubuntutas:~/buildah/src/github.com/projectatomic/buildah# buildah --version
buildah version 0.16 (image-spec 1.0.0, runtime-spec 1.0.0)
root@ubuntutas:~/buildah/src/github.com/projectatomic/buildah# buildah -v
buildah version 0.16 (image-spec 1.0.0, runtime-spec 1.0.0)
```

I'm going to see what I can do with the Makefile and/or handle the error in version.go a bit better.

**Comment by pixdrift** [comment]
Reproducer here:
```
# mv /bin/date /bin/nodate
# date
-bash: date: command not found
# make all
make: date: Command not found
go build -ldflags '-X main.gitCommit=aca2a1e -X main.buildInfo=' -o buildah -tags "   selinux seccomp" ./cmd/buildah
go build -ldflags '-X main.gitCommit=aca2a1e -X main.buildInfo=' -o imgtype -tags "   selinux seccomp" ./tests/imgtype/imgtype.go
make -C docs
-- truncated --

# ./buildah version
strconv.ParseInt: parsing "": invalid syntax
```

I still believe it's due to `date` not being available at compile time. One explanation may be that it's built in a container without `date`, or for whatever reason permissions on `date` present the build user from accessing it (agree this is strange). I think the `make` should fail if it can't find date.

Thoughts @TomSweeneyRedHat @ripcurld?

**Comment by pixdrift** [comment]
@TomSweeneyRedHat, just found another potential issue with a similar fix. If the build server doesn't have git installed the following will fail, returning an empty string:
`GIT_COMMIT := $(shell git rev-parse --short HEAD)`

The `make` displays an error that git isn't available:
```
$ make all
make: git: Command not found
```

And the result is the following in `buildah version`
```
Version:       0.16
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    
Built:         Tue Apr 24 22:45:35 2018
OS/Arch:       linux/amd64
```

This doesn't generate an error or bad exit code, but it could be included in the Makefile checks too?

**Comment by TomSweeneyRedHat** [comment]
I've just posted #616.  I decided to print a warning error and set the date to the epoch.    I think this should be a rare situation and I can't see where having the version set to 12/31/1969 could be problematic for Buildah.

However if other folks think we should instead stop the compilation, I could adjust the PR.

**Comment by pixdrift** [comment]
@TomSweeneyRedHat, my only concern would be that this would inadvertently mask the error for someone building it and they wouldn't necessarily be aware that they are producing binaries that aren't 'correct'.

I don't think it's too crazy to have `date` as a build requirement.. interested in what others think.

**Comment by pixdrift** [comment]
Thanks @rhatdan 👍

**Comment by rhatdan** [comment]
This should not be able to happen, since the Makefile will blow up without the date or git command.

**Comment by taqtiqa-mark** [comment]
All seems good now:

````
$ buildah version
Version:       1.0
Go Version:    go1.8.7
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    fe204e4
Built:         Thu May 10 04:13:34 2018
OS/Arch:       linux/amd64
````
