### ISSUE TITLE
repository is defaulting to docker.io and should default to registries.conf

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#619]
**Description**

There are places in the code where the repository "docker.io" is added to an image rather than the first repository in the list of repositories in /etc/containers/registries.conf.  Find and replace docker.io in the code with the first repository found in registries.conf

This is  likely related to the issue in Podman: https://github.com/projectatomic/libpod/issues/639

** Version **
Buildah v0.16

**Comment by rhatdan** [comment]
This is fixed in latest code to produce localhost/IMAGE
