### ISSUE TITLE
buildah bud --compress functionality is needed

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#621]
**Description**
`buildah bud --compress` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by rhatdan** [comment]
@mtrmac @umohnani8 Does containers/image support this now?

**Comment by mtrmac** [comment]
… and… what does it… do?

It seems to cause the CLI client to compress the “tarball of the current directory” which is sent to the daemon for processing the build; I can’t see how that even makes sense for Docker, assuming a local connection that is (maybe it does for a remote one), and for `buildah` which does not have a daemon, I guess it should just be ignored.

**Comment by umohnani8** [comment]
@rhatdan do we need this flag since the build context is not being transmitted anywhere like in docker. I believe during planning yesterday we commented on the card asking if this flag should just be a NO-OP.
https://trello.com/c/IG96I45d/805-buildah-podman-build-compress-demo

**Comment by rhatdan** [comment]
SGTM. We will make this a NOOP just so scripts would work.  I will open a PR.

**Comment by rhatdan** [comment]
Added --compress as a noop for compatibility.
