### ISSUE TITLE
buildah bud --force-rm functionality is missing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#622]
**Description**
`buildah bud --force-rm` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by rhatdan** [comment]
Since we don't have caching this one can not be implemented yet.

**Comment by pixdrift** [comment]
Blocked by #601

**Comment by pixdrift** [comment]
With PR #639 implementing NOOP for `--rm`, the same can probably be done for this flag until caching is implemented in #601.

**Comment by umohnani8** [comment]
Implemented in https://github.com/projectatomic/buildah/pull/788
