### ISSUE TITLE
buildah bud --format format functionality missing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#623]
**Description**
`buildah bud --format format` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by rhatdan** [comment]
I don't see documentation on docker build --format???

**Comment by ripcurld** [comment]
@rhatdan is right. No `docker build --format` from what I know.

**Comment by rhatdan** [comment]
We actually have a buildah bud format that allows you specify format.

```
       --format

       Control the format for the built image's manifest and configuration data.  Recognized formats include oci (OCI image-spec v1.0, the default) and docker (version 2, using schema format 2 for the manifest).
```

**Comment by rhatdan** [comment]
So @TomSweeneyRedHat Should we close this?

**Comment by TomSweeneyRedHat** [comment]
After reviewing, yep, I'm going to close this one.  @pixdrift holler if you've other thoughts.

**Comment by pixdrift** [comment]
Correct, no `docker build --format`. Apologies if it was in the original table in #599, I can't tell what's been changed in the edit.

**Comment by TomSweeneyRedHat** [comment]
@pixdrift No worries.  This was in the table, but it was my bad.  This is something that we have added to Buildah, but is not in Docker.  I should not of created an issue but suffered a moment of dyslexia apparently.
