### ISSUE TITLE
buildah bud --label functionality missing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#626]
**Description**
`buildah bud --label` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by rhatdan** [comment]
Is this just doing the same thing as the LABEL flag in a dockerfile?

**Comment by pixdrift** [comment]
@rhatdan, seems to be. Proposal is here which describes use case:
https://github.com/moby/moby/pull/13412

I will check the docker behaviour of `Dockerfile LABEL` and `docker build --label` to see how they interact (ie. overwrite,error etc.)

**Comment by jwhonce** [comment]
https://github.com/projectatomic/buildah/pull/698
https://github.com/projectatomic/buildah/pull/716

**Comment by gregoryboue** [comment]
Hi, i'am very interested in the feature, when this functionality will be released ?

Thanks you

**Comment by olivierGATSNCF** [comment]
Hi, 
i agree, i'm very interested too. 
when do you plan to publish the next version?

**Comment by TomSweeneyRedHat** [comment]
Soon.  #721.  With luck a kit should be out in the testing repos for Fedora next week.
