### ISSUE TITLE
buildah bud --squash functionality missing

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#630]
**Description**
`buildah bud --squash` is missing and needs to be provided.  This is functionality that Docker has.

#599 is the parent issue for this issue.

**Output of `buildah version`:**

Buildah v0.16

**Comment by pixdrift** [comment]
@rhatdan, if it is the default buildah behaviour, should buildah accept the parameter and _not_ modify behaviour? otherwise scripts for docker using the parameter will fail with unknown parameter from `buildah bud`.

Good example of this behaviour in the `--rm` issue #598

**Comment by rhatdan** [comment]
Yes we can add the flag and make it a noop or make --squash=false == --cache=true.
Then make --cache and --squash conflict.  I am fine with that.

**Comment by rhatdan** [comment]
But if I had my druthers I would love to someone working on --cache=true.

**Comment by rhatdan** [comment]
I attempted to play around with this on Docker-ce and I can not get it to work.

```
# cat ~/Dockerfile
FROM alpine

CMD /bin/bash
```
Tried to build with squash and it complains.
```
# docker build --squash -f ~/Dockerfile -t squash ~/
Sending build context to Docker daemon  157.6MB
Step 1/2 : FROM alpine
 ---> 3fd9065eaf02
Step 2/2 : CMD /bin/bash
 ---> Using cache
 ---> b2aa3766f486
error squashing image: error getting tar stream to parent: layer ID 'sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215' is not a parent of the specified layer: cannot provide diff to non-parent
```
Built without squash and then tried to  use new image with squash and failed again.
```
cat ~/Dockerfile1
FROM squash1

CMD /bin/sh
```
```
# docker build --squash -f ~/Dockerfile1 -t squash2 ~/
Sending build context to Docker daemon  157.6MB
Step 1/2 : FROM squash1
 ---> b2aa3766f486
Step 2/2 : CMD /bin/sh
 ---> Using cache
 ---> 2d6236f18d96
error squashing image: error getting tar stream to parent: layer ID 'sha256:cd7100a72410606589a54b932cabd804a17f9ae5b42a1882bd56d263e02b6215' is not a parent of the specified layer: cannot provide diff to non-parent
```

**Comment by rhatdan** [comment]
We now have squash.
