### ISSUE TITLE
Request: official Docker image

### ISSUE THREAD

**Issue by AkihiroSuda** [projectatomic/buildah#634]
Could you consider uploading the official image to a registry?

I think you can use this Dockerfile which I'm using for CBI, although it results in very huge image (387MB, uncompressed): https://github.com/containerbuilding/cbi/blob/e488b2e8ea63980b355a7f51f2e170a4b7f0184b/Dockerfile.buildah

**Comment by ripcurld** [comment]
@AkihiroSuda sounds cool.
@rhatdan @TomSweeneyRedHat I would like to work on this on my spare time.
Do you mind? :smiley:

**Comment by TomSweeneyRedHat** [comment]
Go for it @ripcurld.  I think @ipbabble has played with this a bit,  Might want to touch base with him.

**Comment by ripcurld** [comment]
Cool :confetti_ball:

**Comment by pixdrift** [comment]
I have one I use for testing, just pushed it to my personal repo:
https://gitlab.com/pixdrift/buildah-scripts/blob/master/el7.buildah.minimal.sh

Built using buildah, wouldn't take much to switch it to a Dockerfile. Resulting image is 234MB due to RPM deps.

**Comment by ripcurld** [comment]
@pixdrift this is what I wanted to do... :+1: 
I guess what's left to do is to write a build pipeline that:
 (a) is triggered every release
 (b) executes [`this script`](https://gitlab.com/pixdrift/buildah-scripts/blob/master/el7.buildah.minimal.sh)
 (c) commits it to DockerHub.

**Comment by pixdrift** [comment]
@ripcurld, sounds similar to what i'm cobbling together at the moment. Assembling a pipeline to build buildah commit RPMs using a buildah container.

This container will take a buildah commit and produce an el7 x86_64 rpm. Depending on how you wanted to install buildah in the container, you could always use the resulting RPM from this process.
https://gitlab.com/pixdrift/buildah-scripts/blob/master/el7.buildah.rpmbuild.sh

**Comment by rhatdan** [comment]
SGTM

**Comment by ipbabble** [comment]
Have you looked at this?

https://www.projectatomic.io/blog/2018/03/building-buildah-container-image-for-kubernetes/

Please reach out to me at wheny @ redhat.com or check for me in the podman channel on IRC freenode

**Comment by ipbabble** [comment]
$ more ~/buildah.sh 
#! /bin/bash
rel=27
containerid=$(buildah from scratch)
scratchmnt=$(buildah mount $containerid)
dnf install --installroot $scratchmnt --release $rel buildah --setopt install_weak_deps=false -y
dnf clean all --installroot $scratchmnt --release $rel
buildah config --cmd "\-\-help" $containerid
buildah config --entrypoint /usr/bin/buildah $containerid
buildah config --author "wgh @ redhat.com" --created-by "ipbabble" --label name=buildah $containerid
buildah commit $containerid buildah

**Comment by ripcurld** [comment]
thank @ipbabble I will contact you soon. :computer:

**Comment by AkihiroSuda** [comment]
Any news? ^^

**Comment by TomSweeneyRedHat** [comment]
@AkihiroSuda as an FYI, @ipbabble has been doing some serious travelling as of late, but I think he is back soon.

**Comment by ipbabble** [comment]
Hi all I'm back. @ripcurld how far did you get?  I will push a new one up to quay.io today.

-ipbabble

**Comment by ipbabble** [comment]
I've pushed a new fedora based Buildah image:

podman pull quay.io/ipbabble/buildah

Based on fedora release 28.

**Comment by ipbabble** [comment]
I used dnf install with following options:
```
 --setopt install_weak_deps=false --nodocs
```
Then did a clean all and a autoremove 
dnf clean all --installroot $scratchmnt --release $rel
dnf autoremove --installroot $scratchmnt --release $rel

**Comment by TomSweeneyRedHat** [comment]
@AkihiroSuda I think @ipbabble has setup an image for you.  I'm going to close this issue.  Please reopen this issue or a create a new one if you've concerns.
