### ISSUE TITLE
/etc/containers/registries.conf documentation/links are lacking

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#635]
**Description**

@pixdrift pointed out that there's not a whole lot of info on /etc/containers/registries.conf that's availain in the documentation for Buildah.  A man page or other documentation should be created/referenced that explains what the contents of the file are and what the values should be.  Also a little info on how the file is used by the tools.

**Output of `buildah version`:**
Buildah v0.16

**Comment by TomSweeneyRedHat** [comment]
@pixdrift, I raised an issue based on our last bit of IRC chat.  Sorry had to step away and missed the last 10 minutes or so of that.

**Comment by pixdrift** [comment]
Cheers @TomSweeneyRedHat 👍

**Comment by rhatdan** [comment]
buildah.md has 


**registries.conf** (`/etc/containers/registries.conf`)

	registries.conf is the configuration file which specifies which registries should be consulted when completing image names which do not include a registry or domain portion.

Perhaps we should also add this to bud, from, pull, push man pages along with a reference to registries.conf(5)

**Comment by pixdrift** [comment]
To follow this up, the other piece that was missing was documentation for auth.json.

From documentation here:
https://github.com/projectatomic/buildah/blob/4743c2e7f132010a01de2d9cf96d10244fced423/docs/buildah-push.md

> **--authfile path**
> 
> Path of the authentication file. Default is ${XDG_RUNTIME_DIR}/containers/auth.json, which is set using podman login. If the authorization state is not found there, $HOME/.docker/config.json is checked, which is set using docker login.

"Path of the authentication file" is pretty ambiguous, and doesn't explain what it is the authentication file _for_. It also doesn't describe the expected format, and requires downloading podman to create it with `podman login`.

**Comment by TomSweeneyRedHat** [comment]
FYI @baude @umohnani8 @mheon

**Comment by pixdrift** [comment]
Another minor item, `atomic-registries` isn't in `Requires` for buildah (not suggesting it needs to be) so it's not guaranteed that you will have an example `/etc/containers/registries.conf` file to work from after installing the buildah rpm.

**Comment by rhatdan** [comment]
The registries.conf file is moving into skopeo-containers.  Which buildah does require.

**Comment by TomSweeneyRedHat** [comment]
The only hiccup for skopeo-containers is on ubuntu.  It's not available as a package in the two latest versions, it's a WIP.  It can be pulled from GitHub and built though, just no readily accessible rpm's there.

**Comment by rhatdan** [comment]
I think we are all set with this.  Reopen if you disagree.

**Comment by TomSweeneyRedHat** [comment]
I'm good, @pixdrift holler if the recent man page changes don't address this in your thinking.
