### ISSUE TITLE
Support url without --file parameter for bud

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#640]
**Description**

As noted by @edsantiago in https://github.com/projectatomic/libpod/issues/682, the 'buildah bud {url}' does not work unless '-f' and '.' is used ala 'buildah bud -f {url} .'   Before implementing, verify that the lack of -f and . is supported by Docker.

**Output of `buildah version`:**

Buildah v0.16

**Comment by pixdrift** [comment]
Comparison of behaviour on latest commit (2ea3e11):

Docker (works without -f)
```
# docker build https://raw.githubusercontent.com/projectatomic/buildah/master/tests/bud/run-scenarios/Dockerfile.entrypoint-run
Downloading build context from remote url: https://raw.githubusercontent.com/projectatomic/buildah/master/tests/bud/run-scenarios/Dockerfile.entrypoint-run     79 B
Sending build context to Docker daemon 2.048 kB
Step 1/3 : FROM alpine
 ---> 3fd9065eaf02
Step 2/3 : ENTRYPOINT /invalid/entrypoint
 ---> Running in 1f3b80d35262
 ---> 66e47b60da01
Removing intermediate container 1f3b80d35262
Step 3/3 : RUN echo "unique.test.string"
 ---> Running in f9e15111d267

unique.test.string
 ---> 2566e18718b7
Removing intermediate container f9e15111d267
Successfully built 2566e18718b7
```

Buildah (fails without -f)
```
# buildah bud https://raw.githubusercontent.com/projectatomic/buildah/master/tests/bud/run-scenarios/Dockerfile.entrypoint-run
error prepping temporary context directory: Error processing tar file(exit status 1): unexpected EOF
```

**Comment by pixdrift** [comment]
Narrowing this down. It looks like it falls into the tar/extract block and treats the source Dockerfile as a tar source.
```
# buildah --debug bud https://raw.githubusercontent.com/projectatomic/buildah/master/tests/bud/run-scenarios/Dockerfile.entrypoint-run                        
DEBU[0000] extracting "https://raw.githubusercontent.com/projectatomic/buildah/master/tests/bud/run-scenarios/Dockerfile.entrypoint-run" to "/tmp/buildah715107315" 
ERRO[0001] error prepping temporary context directory: Error processing tar file(exit status 1): unexpected EOF 
```

**Comment by rhatdan** [comment]
The way it is supposed to work is it pulls the Dockerfile from the web site and then creates a tmp file with the Dockerfile in it and uses it from there?

**Comment by edsantiago** [comment]
I think it's more complicated than that: docker seems to be able to pull the URL and distinguish between a tarball, a git repo, and a simple Dockerfile. See `docker-build(1)` under DESCRIPTION:
```
    When the URL to a tarball archive or to a single Dockerfile is given,
    no context is sent from the client to the Docker daemon. In this case,
    the Dockerfile at the root of the archive and the rest of the archive will
    get used as the context of the build.  When a Git repository is set as
    the URL, the repository is cloned locally and then sent as the context.
```

**Comment by rhatdan** [comment]
Ok. @pixdrift if you want to run with this one, SGTM

**Comment by pixdrift** [comment]
@rhatdan, I would.. but I am at the point that I need assistance.

Where I got to was above, with the extraction.

The code correctly detects that you provide an http(s) URL, but it then treats the source as a tarball rather than just a flat Dockerfile.
https://github.com/projectatomic/buildah/blob/1513b82eed96ff62c226a38cc9c8e25fc2911b23/imagebuildah/util.go#L74-L75

I think `downloadToDirectory` either needs a parameter to specify that the source type is compressed (eg. `extractSource=true`) or there needs to be a separate function defined, one for downloading Dockerfiles (eg. `downloadDockerfile`), the other for tarballs/images.

**Comment by rhatdan** [comment]
@pixdrift Does https://github.com/projectatomic/buildah/pull/687 solve the problem?

**Comment by pixdrift** [comment]
@rhatdan, that looks great 👍. Will push another commit for something else I have outstanding and take a look.

**Comment by rhatdan** [comment]
Ok I just tried it out locally and it looks like it works now.

**Comment by pixdrift** [comment]
Issue is resolved. Additional CI tests added to confirm functionality:
https://github.com/projectatomic/buildah/blob/master/tests/bud.bats#L569-L584
