### ISSUE TITLE
Unexpected result when pushing to docker-daemon without image tag

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#657]
When pushing a container image from buildah to a local docker daemon with `buildah push`, if a tag is not provided for the docker image, buildah returns various seemingly unrelated errors.

**Steps to reproduce the issue:**
1. Execute `buildah push` to docker-daemon with missing image tag:
`# buildah push wc22 docker-daemon:wc22`
```
Getting image source signatures
error copying layers and metadata: Error checking for blob sha256:43e653f84b79ba52711b0f726ff5a7fd1162ae9df4be76ca1de8370b8bbf9bb0 at destination: Error checking whether a blob sha256:43e653f84b79ba52711b0f726ff5a7fd1162ae9df4be76ca1de8370b8bbf9bb0 exists in docker.io/library/docker-daemon: errors:
denied: requested access to the resource is denied
error parsing HTTP 401 response body: unexpected end of JSON input: ""
```
2. Execute `buildah push` to docker-daemon with correct syntax (expected result):
`# buildah push wc22 docker-daemon:wc22:latest`
```
Getting image source signatures
Copying blob sha256:43e653f84b79ba52711b0f726ff5a7fd1162ae9df4be76ca1de8370b8bbf9bb0
 197.58 MiB / 197.58 MiB [==================================================] 4s
Copying blob sha256:27b16c1ff82af4d83dc7d34be805f01020b83f03216b9f5155257e30c5e43e65
 3.00 KiB / 3.00 KiB [======================================================] 0s
Copying config sha256:9f48682b692bce2df5efc54b791b7e38275de469a2ef754d7d40b1c2190aabe5
 1.24 KiB / 1.24 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
```

**Describe the results you received:**
Errors relating to access to resources and JSON parsing errors.

**Describe the results you expected:**
Error about docker-daemon syntax, or default behaviour that accepts the push.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-0.16-201805041154.git45772e8.el7.x86_64
```

**Output of `buildah version`:**

```
Version:       0.16
Go Version:    go1.8.3
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    45772e8
Built:         Thu May  3 06:46:45 2018
OS/Arch:       linux/amd64

```

**Comment by TomSweeneyRedHat** [comment]
This appears to be working now with @rhatdan 's #760 
```
# buildah from alpine
alpine-working-container
[root@localhost ~]# buildah push alpine docker-daemon:alpine
docker-daemon: reference alpine has neither a tag nor a digest
```
@pixdrift please reopen or create a new issue as appropriate if you find there are still problems here.
