### ISSUE TITLE
Potential symlink/directory traversal issue in user ID extraction

### ISSUE THREAD

**Issue by fweimer** [projectatomic/buildah#66]
Commit b1bb73e01c9bf0b1b75e50a2d1947b14a8174eee (“ Teach "Run" to dig user IDs out of containers”) added the `fopenContainerFile` function. It does not correctly deal with symbolic links, which could point to something outside of the container root.

**Comment by nalind** [comment]
Are you suggesting something like https://github.com/nalind/buildah-1/commit/97ca24a7b4cc2739edf8b6b12f1c87ab103a0caa?  What did we not catch with the (possibly over-restrictive) lstat-after-opening method?

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(8) [Buildah] Add "dockah build-using-dockerfile" aka "buildah bud"](https://trello.com/c/AyBXqoRY/443-8-buildah-add-dockah-build-using-dockerfile-aka-buildah-bud)

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(8) [Buildah] Add "dockah build-using-dockerfile" aka "buildah bud"](https://trello.com/c/AyBXqoRY/443-8-buildah-add-dockah-build-using-dockerfile-aka-buildah-bud)

**Comment by nalind** [comment]
@fweimer The patch with the fix I'm looking at had a conflict in it, so I've rebased it to https://github.com/nalind/buildah-1/commit/2c387528f2af7655d231a4989f67b21c90e1c385.  I'd appreciate any guidance you can offer.

**Comment by fweimer** [comment]
@nalind, when this code is run, is the file system directory tree dead and inaccessible to unprivileged processes, or has concurrent modification of the tree to be expected?

**Comment by nalind** [comment]
The filesystem tree is mounted on the host, so modification is possible for users with the necessary privileges.

**Comment by fweimer** [comment]
@nalind, in this case, the code still has a time-of-check-time-of-use race condition because after symbolic link resolution, the file system tree could change and contain symbolic links again.

You either have to use `chroot` to restrict pathname lookups (no longer needs root in current Fedora), or reimplement kernel pathname lookup using `openat` and `O_PATH`.

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[buildah] Fix potential symlink traversal problem when looking up numeric IDs for USER settings](https://trello.com/c/Go7pxsyV/480-buildah-fix-potential-symlink-traversal-problem-when-looking-up-numeric-ids-for-user-settings)

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[buildah] Fix potential symlink traversal problem when looking up numeric IDs for USER settings](https://trello.com/c/Go7pxsyV/480-buildah-fix-potential-symlink-traversal-problem-when-looking-up-numeric-ids-for-user-settings)

**Comment by rhatdan** [comment]
@nalind have you done anything else for this issue?

**Comment by rhatdan** [comment]
@nalind any update on this?

**Comment by nalind** [comment]
Alright, I'm beginning to think there's no way around having to use chroot().  https://github.com/projectatomic/buildah/compare/master...nalind:user2 contains what I'm thinking should prevent the directory traversal problem.
