### ISSUE TITLE
`buildah run` with pipe ('|') fails

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#671]
**Description**

A `buildah run` command with a pipe in it fails.  For instance:

` buildah run $whalesays /usr/games/fortune -a | cowsay`
-bash: cowsay: command not found

Prior versions the command `buildah run $whalesays` would run the commands piping the fortune to cowsay and would print a message from the Docker whale.

**Steps to reproduce the issue:**
1.  /bin/cat <<EOM >$FILE
FROM docker/whalesay:latest
RUN apt-get -y update && apt-get install -y fortunes
CMD /usr/games/fortune -a | cowsay
EOM
2. chmod +x $FILE
3. buildah bud -f Dockerfile -t whale-says
4. whalesays=$(buildah from whale-says)

The following fails:
buildah run $whalesays /usr/games/fortune -a | cowsay
buildah run $whalesays -- /usr/games/fortune -a | cowsay
buildah run $whalesays -- /usr/games/fortune -a | cowsay
buildah run $whalesays -- '/usr/games/fortune -a | cowsay'

**Describe the results you received:**
cowsay: command not found errors

**Describe the results you expected:**
A fortune with a Docker whale diagram.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
# rpm -q buildah
buildah-1.0-1.git1ab80bc.fc28.x86_64
```

**Output of `buildah version`:**

```
# buildah version
Version:       1.0
Go Version:    go1.10.1
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    1ab80bc
Built:         Mon May  7 10:01:02 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
# cat /etc/*release
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Server Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Server Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Server Edition"
VARIANT_ID=server
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**

```
 uname -a
Linux localhost.localdomain 4.16.6-302.fc28.x86_64 #1 SMP Wed May 2 00:07:06 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# cat /etc/containers/storage.conf
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by pixdrift** [comment]
Interestingly it looks shell specific, as behaviour when using `RUN` in the Docker file to execute the same command succeeds.

```
FROM docker/whalesay:latest
RUN apt-get -y update && apt-get install -y fortunes
CMD /usr/games/fortune -a | cowsay
RUN /usr/games/fortune -a | cowsay
```

```
STEP 3: CMD /usr/games/fortune -a | cowsay
STEP 4: RUN /usr/games/fortune -a | cowsay
 ________________________________________ 
/ Physician: One upon whom we set our    \
| hopes when ill and our dogs when well. |
|                                        |
\ -- Ambrose Bierce                      /
 ---------------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   

```

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, that's no good.  I think what ends up happening is the commands on the left of the pipe causes the container to run fortune (which succeeds by itself) and then pipes that result to the command 'cowsay' on the host itself which doesn't exist.

```
# buildah run $whalesays -- /usr/games/fortune -a | cowsay
-bash: cowsay: command not found

# buildah run $whalesays /bin/bash
root@mrsdalloway:/cowsay# /usr/games/fortune -a | cowsay
 _______________________________________ 
/ The primary requisite for any new tax \
| law is for it to exempt enough voters |
\ to win the next election.             /
 --------------------------------------- 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   



```

**Comment by TomSweeneyRedHat** [comment]
@ipbabble to the rescue!
```
# buildah run $whalesays bash -c '/usr/games/fortune -a | cowsay'
 ____________________________________ 
< The Korean War must have been fun. >
 ------------------------------------ 
    \
     \
      \     
                    ##        .            
              ## ## ##       ==            
           ## ## ## ##      ===            
       /""""""""""""""""___/ ===        
  ~~~ {~~ ~~~~ ~~~ ~~~~ ~~ ~ /  ===- ~~~   
       \______ o          __/            
        \    \        __/             
          \____\______/   
```

**Comment by TomSweeneyRedHat** [comment]
Going to leave this open, but mark it as a documentation issue.

**Comment by ipbabble** [comment]
@nalind explained it to me last night as I hit the issue with my new docker-compatibility-demo.sh 

So @nalind for the win.   

It is worth pointing this out when doing demos  and it might be worth putting in a tutorial. Because a Dockerfile RUN statement doesn't always just copy over to a buildah run command.

I have to go over the Tutorials anyway because of the buildah run cmd and entrypoint change. There are several canges to be made. Also I probably need to do the same with some blogs. Ugh.

**Comment by ipbabble** [comment]
Not this is also true of redirects. E.g. taking a Dockerfile with the following lines:

RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN echo "nginx on Fedora" > /usr/share/nginx/html/index.html

Changes to the following 

buildah run $newcontainer bash -c 'echo "daemon off;" >> /etc/nginx/nginx.conf'
buildah run $newcontainer bash -c 'echo "nginx on OCI Fedora image, built using Buildah" > /usr/share/nginx/html/index.html'

**Comment by rhatdan** [comment]
That looks correct, in both examples the content should be created in the container not in the host.

**Comment by rhatdan** [comment]
I don't believe this is a bug, this is just bashisms.  Reopen if you don't agree.

**Comment by TomSweeneyRedHat** [comment]
Actually I think #683 did enough to address this.  I don't think  I'll add further documentation unless we get pinged about it.
