### ISSUE TITLE
Consistent tag format?

### ISSUE THREAD

**Issue by alanbchristie** [projectatomic/buildah#672]
It's a super-minor point but could you be consistent with your tags and decide on **V** or **v** as a prefix?

**Comment by pixdrift** [comment]
Hi Alan,

Are you referring to consistency between buildah commands? 

Can you give a specific example?

**Comment by TomSweeneyRedHat** [comment]
@Ace-Tang yes please to a specific example and thanks for raising the issue!

**Comment by alanbchristie** [comment]
Sorry, yes. I was referring to the fact that version 1.0 has the tag **V1.0** (upper-case) but all the previous tags were **v0.8** (lower-case) but it really isn't that important.

It's a really, really, really minor point - and I'm just curious - but it tripped-up some automation code I'd written that checks out releases based on the number and it assumed you'd continue using lower-case "v". It's my fault - I shouldn't make assumptions. From now on I'll track using the entire tag string but just wondered (in my own sad little world) why it was inconsistent.

Loving buildah BTW.

**Comment by pixdrift** [comment]
@alanbchristie, sorry still not quite on the same page. Are you talking about a container tag? The output of `buildah version` looks unchanged.

Can you provide the code block that broke? might give me the insight I need 😄

**Comment by rhatdan** [comment]
@alanbchristie Sorry about that, I will see about changing it to lower case.
