### ISSUE TITLE
util.ResolveName searches through insecure registries

### ISSUE THREAD

**Issue by mtrmac** [projectatomic/buildah#680]
https://github.com/projectatomic/buildah/blob/b9a1041b1823b556b0fd9c14928055726cc473e5/util/util.go#L107 adds the list of insecure registries to the list of registries to search (if insecure Docker registry access is enabled).

Why?

At least https://github.com/containers/image/blob/master/docs/registries.conf.5.md does not say anything about treating the list of insecure registries like this, and projectatomic/docker also searches only through the registries listed in `--add-registry`.

Combining the two configuration options also means that it is impossible to configure a registry as insecure without adding it to the search list. Also, the insecure registries are searched through only when `sc.DockerInsecureSkipTLSVerify` is set—which makes the list of insecure registries, as defined, irrelevant, because all registries are treated as insecure.

I just can’t see what this is supposed to do or not do.

**Comment by rhatdan** [comment]
If we fix this would we end up with the same problem when we move to sysregistriesv2?
Doesn't that version only allow you to specify a list of registries?  And then specify whether it is insecure or blocked. Or is there a flag to indicate a registry is searched?

**Comment by mtrmac** [comment]
V2 has a different API (there is a single list of all registries, each of which may have a “search” and “insecure” boolean), but the overall effect is that the search order and “is insecure” boolean are again orthogonal, so a concept-for-concept port of the existing code to V2 would behave in the same (non-intuitive) way.

**Comment by rhatdan** [comment]
Ok, then I agree the "Search List" and "Block List" should not be merged. that is a bug.
