### ISSUE TITLE
gometalinter error with make install.tools

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#689]
**Description**

When doing `make install.tools` the following error occurs.
```
go get -u -tags "   selinux seccomp" github.com/alecthomas/gometalinter
gometalinter.v1 -i
make: gometalinter.v1: Command not found
make: *** [Makefile:58: install.tools] Error 127

```
**Steps to reproduce the issue:**
1.  Follow GitHub Installlation instructions for Buildah
2.  make install.tools

**Describe the results you received:**

See description.

**Describe the results you expected:**

Successful build.

**Output of `buildah version`:**

```
# buildah version
Version:       1.0
Go Version:    go1.10.2
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    8515867
Built:         Tue May 15 07:14:26 2018
OS/Arch:       linux/amd64
```

**Comment by rhatdan** [comment]
Since this was merged, closing.
