### ISSUE TITLE
ubuntu 18.04 can't add ppa:projectatomic/ppa repository

### ISSUE THREAD

**Issue by q384566678** [projectatomic/buildah#696]
When I created `buildah` in Ubuntu 18.04, I found that I could not add the `ppa:projectatomic/ppa` repository. The details are as follows:
```
➜  ~ sudo -E apt-add-repository -y ppa:projectatomic/ppa
Ign:1 http://dl.google.com/linux/chrome/deb stable InRelease
Get:2 http://dl.google.com/linux/chrome/deb stable Release [1,189 B]           
Hit:4 http://ppa.launchpad.net/git-core/ppa/ubuntu bionic InRelease                                       
Hit:5 https://mirrors.ustc.edu.cn/ubuntu bionic InRelease                                                 
Hit:6 https://mirrors.ustc.edu.cn/ubuntu bionic-updates InRelease              
Hit:7 http://ppa.launchpad.net/noobslab/icons/ubuntu bionic InRelease    
Hit:8 https://mirrors.ustc.edu.cn/ubuntu bionic-backports InRelease      
Hit:9 https://mirrors.ustc.edu.cn/ubuntu bionic-security InRelease       
Hit:10 https://mirrors.ustc.edu.cn/ubuntu bionic-proposed InRelease      
Ign:11 http://ppa.launchpad.net/projectatomic/ppa/ubuntu bionic InRelease
Err:12 http://ppa.launchpad.net/projectatomic/ppa/ubuntu bionic Release
  404  Not Found [IP: *********]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/projectatomic/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Is this repository not yet providing support for 18.04? Is there any good solution?

（I don't know which side to report on this issue. I didn't find any better place, so I can only ask this question in this community. Hope you don't mind.）

**Comment by Conan-Kudo** [comment]
This is a problem with Launchpad, report it to them.

**Comment by TomSweeneyRedHat** [comment]
@lsm5 any further advice/details?

**Comment by lsm5** [comment]
@q384566678 well, the PPA is only enabled for 16.04 (the previous LTS) so far. @fkluknav is working on 18.04 builds right now.

**Comment by q384566678** [comment]
Thank you for your information. Wait for the final result.

**Comment by rhatdan** [comment]
@lsm5 Could you help out @q384566678

**Comment by Tahutipai** [comment]
+1 vote for 18.04 support

**Comment by fernando-redhat** [comment]
+1 another vote for 18.04 support

**Comment by lsm5** [comment]
@fernando-redhat you still seeing issues with 18.04 addition? can you post the logs please?

**Comment by gleroi** [comment]
as of today:
sudo apt update
Hit:1 http://repo.steampowered.com/steam precise InRelease
Hit:2 http://fr.archive.ubuntu.com/ubuntu cosmic InRelease                                                                                                    
Ign:3 http://binaries.erlang-solutions.com/debian cosmic InRelease                                                                                            
Hit:4 http://fr.archive.ubuntu.com/ubuntu cosmic-updates InRelease                                                                                            
Ign:5 http://ppa.launchpad.net/projectatomic/ppa/ubuntu cosmic InRelease                                                                                      
Hit:6 http://security.ubuntu.com/ubuntu cosmic-security InRelease                                                                                             
Hit:7 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                             
Hit:8 http://binaries.erlang-solutions.com/debian cosmic Release                                                                                              
Hit:9 https://download.docker.com/linux/ubuntu bionic InRelease                                                                                               
Err:10 http://ppa.launchpad.net/projectatomic/ppa/ubuntu cosmic Release                                                                                       
  404  Not Found [IP: 91.189.95.83 80]
Hit:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease                                                        
Hit:13 http://fr.archive.ubuntu.com/ubuntu cosmic-backports InRelease                                     
Reading package lists... Done                         
E: The repository 'http://ppa.launchpad.net/projectatomic/ppa/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by lsm5** [comment]
On Sat, Aug 03, 2019 at 10:52:16AM -0700, Guillaume Leroi wrote:
> as of today:
> sudo apt update
> Hit:1 http://repo.steampowered.com/steam precise InRelease
> Hit:2 http://fr.archive.ubuntu.com/ubuntu cosmic InRelease                                                                                                    
> Ign:3 http://binaries.erlang-solutions.com/debian cosmic InRelease                                                                                            
> Hit:4 http://fr.archive.ubuntu.com/ubuntu cosmic-updates InRelease                                                                                            
> Ign:5 http://ppa.launchpad.net/projectatomic/ppa/ubuntu cosmic InRelease                                                                                      
> Hit:6 http://security.ubuntu.com/ubuntu cosmic-security InRelease                                                                                             
> Hit:7 http://packages.microsoft.com/repos/vscode stable InRelease                                                                                             
> Hit:8 http://binaries.erlang-solutions.com/debian cosmic Release                                                                                              
> Hit:9 https://download.docker.com/linux/ubuntu bionic InRelease                                                                                               
> Err:10 http://ppa.launchpad.net/projectatomic/ppa/ubuntu cosmic Release                                                                                       
>   404  Not Found [IP: 91.189.95.83 80]
> Hit:11 https://packages.microsoft.com/ubuntu/18.04/prod bionic InRelease                                                        
> Hit:13 http://fr.archive.ubuntu.com/ubuntu cosmic-backports InRelease                                     
> Reading package lists... Done                         
> E: The repository 'http://ppa.launchpad.net/projectatomic/ppa/ubuntu cosmic Release' does not have a Release file.
> N: Updating from such a repository can't be done securely, and is therefore disabled by default.
> N: See apt-secure(8) manpage for repository creation and user configuration details.
> 

Didn't cosmic get EOL'd last month?


> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/containers/buildah/issues/696#issuecomment-517942863

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by terion-name** [comment]
still actual

**Comment by lsm5** [comment]
> still actual

care to elaborate please?

**Comment by terion-name** [comment]
@lsm5 trying to install on Ubuntu 18 errors the same as topicstarter written

**Comment by lsm5** [comment]
> @lsm5 trying to install on Ubuntu 18 errors the same as topicstarter written

@terion-name is it 18.04 (bionic) or 18.10 (cosmic) ? If it's 18.10 (cosmic), then it's been [officially EOL-ed](https://fridge.ubuntu.com/2019/07/19/ubuntu-18-10-cosmic-cuttlefish-end-of-life-reached-on-july-18-2019/) and there's no point creating packages for it. Please consider upgrading to 19.04 (disco) in that case.

**Comment by terion-name** [comment]
@lsm5 bionic

**Comment by lsm5** [comment]
> @lsm5 bionic

@terion-name that's strange. It's working for me and I haven't heard anyone else complain about that recently. Mind posting the output here when you try to add the ppa please? The original post is more than a year old btw, so I'm not sure whatsup in your case, so the error output would certainly help. Thanks.

**Comment by terion-name** [comment]
@lsm5 
```bash
vagrant@server:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.1 LTS
Release:        18.04
Codename:       bionic
vagrant@server:~$ sudo add-apt-repository ppa:thumbor/ppa
 
 More info: https://launchpad.net/~thumbor/+archive/ubuntu/ppa
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://ppa.launchpad.net/nginx/development/ubuntu bionic InRelease
Hit:2 http://archive.ubuntu.com/ubuntu bionic InRelease                                                                                                                                                                              
Hit:3 http://ppa.launchpad.net/ondrej/php/ubuntu bionic InRelease                                                                                                                                                                    
Get:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]                                                                                                                                                            
Ign:5 http://ppa.launchpad.net/thumbor/ppa/ubuntu bionic InRelease                                                                                                                                                                   
Get:6 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]                                                                                                                                                          
Hit:8 https://deb.nodesource.com/node_8.x bionic InRelease                                                                                                                                                                           
Hit:7 https://cli-assets.heroku.com/apt ./ InRelease                                                                                                                                                                                 
Err:9 http://ppa.launchpad.net/thumbor/ppa/ubuntu bionic Release                                                                                                                                               
  404  Not Found [IP: 91.189.95.83 80]
Get:10 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]                                                                                                        
Hit:11 https://dist.crystal-lang.org/apt crystal InRelease                                                                                   
Get:12 http://archive.ubuntu.com/ubuntu bionic-updates/main i386 Packages [586 kB]                    
Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [740 kB]                   
Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main Translation-en [267 kB]                
Get:13 http://packages.blackfire.io/debian any InRelease [23.2 kB]                                       
Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/universe i386 Packages [980 kB]                   
Err:13 http://packages.blackfire.io/debian any InRelease                                      
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 696DBE66A72D76DA
Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1,007 kB]
Reading package lists... Done                               
E: The repository 'http://ppa.launchpad.net/thumbor/ppa/ubuntu bionic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://packages.blackfire.io/debian any InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 696DBE66A72D76DA
```

**Comment by lsm5** [comment]
On Thu, Sep 26, 2019 at 01:23:19AM -0700, Terion wrote:

> vagrant@server:~$ sudo add-apt-repository ppa:thumbor/ppa


So, you're trying to add `ppa:thumbor/ppa` but the one we provide is
`ppa:projectatomic/ppa`. Can you retry with the correct name please?

-- 
Lokesh
IRC, GitHub: lsm5
GPG: 0xC7C3A0DD
https://keybase.io/lsm5

**Comment by terion-name** [comment]
@lsm5 oh my. so sorry, this is wrong repository. so dumb. I need more to sleep.
