### ISSUE TITLE
Maybe use openshift/imagebuilder

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#7]
Maybe use openshift/imagebuilder to handle parsing a dockerfile and letting it drive a multiple-step build process in the CLI.

**Comment by rhatdan** [comment]
That would work, but we would need to figure out what API that would need.

**Comment by mrunalp** [comment]
openshift/imagebuilder uses vendored docker code to parse the Dockerfile. See https://github.com/openshift/imagebuilder/blob/787a5489b8369bfdc9a7e2325a23999831e4367d/evaluator.go#L9 I think we can create an interface/API for frontends and support Dockerfile as one.

**Comment by nalind** [comment]
I'm working on this.

**Comment by nalind** [comment]
Closing via #59.
