### ISSUE TITLE
buildah bud -f flag not replicating docker build -f behaviour

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#703]
**Description**
Currently the `-f` flag to `buildah bud` behaves differently to `docker build` in that it can be provided with the full path to a Dockerfile. To match the `-f` behaviour of `docker build`, the behaviour needs to be updated to remove this capability and provide an error when the Dockerfile directory isn't supplied.

Additional to this, the current contextual help suggests that `-f` can take a URL for a Dockerfile, which does not behave as expected.

**Steps to reproduce the issue:**
1. The following works with `buildah bud` but shouldn't as the command does not have the Dockerfile directory parameter supplied.
```
buildah bud -f entissue/Dockerfile2
STEP 1: FROM centos:7
STEP 2: ENTRYPOINT /bin/bash
STEP 3: WORKDIR /tmp
...
```
The same command in `docker build` provides the error output we are expecting
```
docker build -f entissue/Dockerfile2
"docker build" requires exactly 1 argument(s).
```

**Describe the results you received:**
1. `buildah bud` working without a supplied Dockerfile directory.
2. Documentation for `-f` suggests you can provide a URL to a Dockerfile

**Describe the results you expected:**
1. An error stating that `buildah bud` is missing an argument, inline with Docker behaviour
2. Documentation to outline that only alternate Dockerfile names are supported with `-f`

**Output of `rpm -q buildah` or `apt list buildah`:**

```
buildah-1.0-201805151537.git3e320b9.el7.x86_64
```

**Output of `buildah version`:**

```
Version:       1.0
Go Version:    go1.9.4
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    3e320b9
Built:         Wed May 16 01:44:18 2018
OS/Arch:       linux/amd64
```

**Comment by TomSweeneyRedHat** [comment]
@pixdrift I'll let @rhatdan and @nalind weigh in on this one, but I like that the -f in `buildah bud` will let you specify a file that's not "Dockerfile" and also not necessarily in the directory.  To me it's like the added --all param fomr rm and rmi, a nice different feature.

Can you expand on the url bit?  Does "not working as expected" mean that the build works but it would not in Docker?  Or does it mean the build doesn't work at all in Buildah?

**Comment by pixdrift** [comment]
Sorry @TomSweeneyRedHat, I had a discussion with @rhatdan on IRC and did a quick summary.

The -f URL issue is that the documentation describes the following:
`--file pathname or URL, -f pathname or URL  pathname or URL of a Dockerfile`

But URL isn't really valid here, as `-f` is specifying the name of the Dockerfile to use in the supplied path (final parameter passed to `buildah bud`).

This behaviour/error condition is correct as no context directory is supplied:
```
# buildah bud -f https://raw.githubusercontent.com/projectatomic/buildah/master/tests/bud/from-scratch/Dockerfile
no context directory specified, and no dockerfile specified
```

When supplying `-f` with `.` it works.. but should it?
```
# buildah bud -f https://raw.githubusercontent.com/projectatomic/buildah/master/tests/bud/from-scratch/Dockerfile .
STEP 1: FROM scratch
```

 I would expect a user to use the `buildah bud <URL>` method which is now working and matches Docker behaviour.

This all came out when writing I tests for the `-f` flag.

**Comment by rhatdan** [comment]
Fixed in master.

**Comment by pixdrift** [comment]
The documentation still states -f takes an http/https URL? What was the decision here?

**Comment by rhatdan** [comment]
Does it work with the http?  I like the idea of being able to grab a Dockerfile outside of the context directory.  If this works I say we keep it.

**Comment by pixdrift** [comment]
@rhatdan if you want to grab an http URL you just use 'buildah bud', why have the same capability re-implemented under the `-f` flag? especially when it doesn't follow Docker behaviour?

The `-f` is essentially so specify an alternate Dockerfile name, not to specify a Dockerfile you want built at random. It breaks the convention that a Dockerfile sits in its own directory.

**Comment by rhatdan** [comment]
Yes, and this has been requested that -f specify a separate location.  Allowing the Dockerfile to exist outside of the context directory is a feature, I believe.
