### ISSUE TITLE
Building an Image using a URL doesn't work

### ISSUE THREAD

**Issue by jdoss** [projectatomic/buildah#717]
**Description**

Following https://github.com/projectatomic/libpod/blob/master/docs/podman-build.1.md#building-an-image-using-a-url running a build with a github repo fails with:

`error prepping temporary context directory: Error processing tar file(exit status 1): archive/tar: invalid tar header`

**Steps to reproduce the issue:**
1. `podman build https://github.com/jdoss/atomic-wireguard/`

**Describe the results you received:**

`error prepping temporary context directory: Error processing tar file(exit status 1): archive/tar: invalid tar header`

**Describe the results you expected:**

A built container without this error.

**Output of `rpm -q buildah` or `apt list buildah`:**

```
# rpm -q buildah
buildah-1.0-1.git1ab80bc.fc28.x86_64
```

**Output of `buildah version`:**

```
buildah -v
buildah version 1.0 (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Output of `cat /etc/*release`:**

```
# cat /etc/*release
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**

```
# uname -a
Linux sts71 4.16.8-300.fc28.x86_64 #1 SMP Wed May 9 20:23:40 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
Dang @pixdrift, photographic memory?  Thanks!

**Comment by jdoss** [comment]
Hey @pixdrift thanks for the response with the precognitive fix. :wink: 

Reading the podman documentation here:

https://github.com/projectatomic/libpod/blob/master/docs/podman-build.1.md#building-an-image-using-a-url

It says:

>This will clone the specified GitHub repository from the URL and use it as context. The Dockerfile at the root of the repository is used as Dockerfile. This only works if the GitHub repository is a dedicated repository.
>
> podman build github.com/scollier/purpletest
>
> Note: You can set an arbitrary Git repository via the git:// scheme.

I was confused by the example above. Running `podman build git://github.com/jdoss/atomic-wireguard` with `git://` specified in the URL actually works without any issues. I just issued a [PR](https://github.com/projectatomic/libpod/pull/822) to the libpod repo to help clarify how to use `podman build` with a URL, Git repo, or archive in hopes to avoid any confusion for others in the future. I based a lot of it's wording on your comments in https://github.com/projectatomic/buildah/commit/5d9d28ba1f754deab2cb80db2c9d48916b655605 as I assume these changes will end up in Podman soon.

Sorry for the confusion folks and thanks for the help!

**Comment by rhatdan** [comment]
@jdoss Yes podman will have this on the Friday release.  The podman release train comes out once per week, as we move towards 1.0.

**Comment by TomSweeneyRedHat** [comment]
No worries at all @jdoss, I just feel bad for having you write up the issue when it was already fixed.
