### ISSUE TITLE
Create Development plan

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#718]
Per a suggestion from Zhou Hao (I think @q384566678) , create a development plan/todo list for Buildah.

**Description**
From Zhou:
 
  I wrote this email to ask some questions about buildah community
development.
   I noticed that the 1.0 version has been released for some time. I
want to know what is the development plan below the community? Or,
after buildah released 1.0, the expected functions have been completed.
The following is just some perfect work. There will not be major
changes.

   Since I didn't see a specific development plan in the community and I
didn't find buildah's mailing list, I just sent this email to ask you.
Hope you do not mind. 

@rhatdan responded:
Hey.  Biggest things we are working on with buildah right now, are:

1.  Integration into OpenShift and potentially other tools. Biggest requirement for this is to be able build OCI Images without running as root on a system, actually no SYS_ADMIN privs. This would allow us to run non priv containers inside of Kubernetes, so you could distribute your container workloads.

2. Integration with User Namespace, Podman has this already, but we want to get buildah bud and buildah run to be able to run its containers in a usernamespace to give the builder bettter security isolation from the host.

3. Caching support.  Currently buildah bud builds just one layer, which is great for building images in a pipeline, but is not so great for developers.  docker build defaults to caching, where each line of the Dockerfile creates an image.  If you don't modify a line in a Dockerfile and re-execute docker build a second time, it will skip all of the lines in the Dockerfile until a line changes.  We want to get similar support in buildah.

We hang out on #buildah and #podman on freenode on IRC. I guess we could create an email list, for people but most of us rely on following github.com/projectatomic/buildah and the IRC.  Some have suggested that we also do something with slack.

Tom's response:

The plan for Buildah is continued development for the foreseeable future
as the community needs.  The functionality that is there now should
remain barring some kind of major bug found within it.  Then as a
community we will fix those as they arise.  We will also be adding to
Buildah over time when and if the OCI specifications changes to keep it
in line with that and as you may note in our issues list, we have a
number of items that still need some polishing.

I can safely say that Red Hat and other companies have big plans for
Buildah and other related container technologies.  In case you have not
stumbled across it yet, please take a look at Podman
(https://github.com/projectatomic/libpod).   Buildah is great for
helping you build containers and Podman will excel in helping you manage
them, especially in a Kubernetes environment.

**Comment by TomSweeneyRedHat** [comment]
@pixdrift suggests adding via irc:

<pixdrift> I think it's worth mentioning docker build (bud) feature parity as a project goal tsweeney
<pixdrift> not there yet, and a bit of work to go
<pixdrift> would also like to see coverage reports in the repo with a high testing coverage.. but that doesn't have to be a define project goal ;)

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Should we add a mark down file with this data and every release go in and update it?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan sounds like a good idea.

**Comment by TomSweeneyRedHat** [comment]
Closing as #841 addresses this.
