### ISSUE TITLE
Commit to private docker registry: connection refused

### ISSUE THREAD

**Issue by stefanand** [projectatomic/buildah#728]
**Description**

```
When buildah push an error occurs in the end, though the image has been pushed to the private registry. Why does it happen? Is anything wrong? No error output from the docker registry.

The certificate for the registry used is not self-signed!
```

**Steps to reproduce the issue:**
1. buildah push --creds=username:passwd $name docker://hub.xxxxx.com:5000/$name
2.
3.

**Describe the results you received:**
I didn't expect any connection refused.

**Describe the results you expected:**
No error.

**Output of `rpm -q buildah` or `apt list buildah`:**
buildah-1.0-1.git1ab80bc.fc28.x86_64

```
Complete!
Getting image source signatures
Copying blob sha256:199dbc3127dde5e6a0e6b30a3bdd008a6ea79ae9b44dbdf8669655be0665f927
 47.78 MiB / 47.78 MiB [====================================================] 2s
Copying config sha256:3d6645f9adcd1e30cb61a96d12a257400e69c0a9e5d47d99dfa960d3ba60067c
 1.04 KiB / 1.04 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
3d6645f9adcd1e30cb61a96d12a257400e69c0a9e5d47d99dfa960d3ba60067c
Getting image source signatures
Get https://hub.xxxxx.com:5000/v2/: dial tcp vv.xx.yy.zz:5000: connect: connection refused
```

**Output of `buildah version`:**

```
Version:       1.0
Go Version:    go1.10.1
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    1ab80bc
Built:         Mon May  7 16:01:02 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
Fedora release 28 (Twenty Eight)
NAME=Fedora
VERSION="28 (Workstation Edition)"
ID=fedora
VERSION_ID=28
PLATFORM_ID="platform:f28"
PRETTY_NAME="Fedora 28 (Workstation Edition)"
ANSI_COLOR="0;34"
CPE_NAME="cpe:/o:fedoraproject:fedora:28"
HOME_URL="https://fedoraproject.org/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=28
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=28
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
Fedora release 28 (Twenty Eight)
Fedora release 28 (Twenty Eight)
```

**Output of `uname -a`:**

```
Linux localhost.localdomain 4.16.11-300.fc28.x86_64 #1 SMP Tue May 22 18:29:09 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
# storage.conf is the configuration file for all tools
# that share the containers/storage libraries
# See man 5 containers-storage.conf for more information

# The "container storage" table contains all of the server options.
[storage]

# Default Storage Driver
driver = "overlay"

# Temporary storage location
runroot = "/var/run/containers/storage"

# Primary Read/Write location of container storage
graphroot = "/var/lib/containers/storage"

[storage.options]
# AdditionalImageStores is used to pass paths to additional Read/Only image stores
# Must be comma separated list.
additionalimagestores = [
]

# Size is used to set a maximum size of the container image.  Only supported by
# certain container storage drivers.
size = ""

# OverrideKernelCheck tells the driver to ignore kernel checks based on kernel version
override_kernel_check = "true"
```

**Comment by TomSweeneyRedHat** [comment]
@stefanand Thanks for the problem report.  Can you share the command(s) that you you used to setup and run the registry?  Are their any related errors in journalctl?

**Comment by stefanand** [comment]
Start of the docker registry:

docker run -dit \
 --name registry \
 -p 5000:5000 \
 -v `pwd`/auth:/auth \
 -e "REGISTRY_AUTH=htpasswd" \
 -e "REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm" \
 -e REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd \
 -v /home/nfs/registry:/var/lib/registry \
 -v /etc/letsencrypt:/certs \
 -e REGISTRY_HTTP_TLS_CERTIFICATE=/certs/live/hub.xxxxx.com/fullchain.pem \
 -e REGISTRY_HTTP_TLS_KEY=/certs/live/hub.xxxxx.com/privkey.pem \
 --restart always \
docker.io/registry



journalctl gives:


systemd[1]: Mounting /home/nfs/registry...

systemd[1]: Mounted /home/nfs/registry.

audit[728]: VIRT_CONTROL pid=728 uid=0 auid=4294967295 ses=4294967295 msg='op=logs vm=docker.io/registry vm-pid=1438 user=root auid=0 exe=/entrypoint.sh hostname=a2bd4d598e70 reason=api  exe="/usr/bin/docker-current" hostname=? addr=? terminal=? res=success'

audit[728]: VIRT_CONTROL pid=728 uid=0 auid=4294967295 ses=4294967295 msg='hostname=a2bd4d598e70 reason=api op=stop vm=docker.io/registry vm-pid=1438 user=root auid=0 exe=/entrypoint.sh  exe="/usr/bin/docker-current" hostname=? addr=? terminal=? res=success'

audit[728]: VIRT_CONTROL pid=728 uid=0 auid=4294967295 ses=4294967295 msg='vm=docker.io/registry vm-pid=0 user=root auid=0 exe=/entrypoint.sh hostname=a2bd4d598e70 reason=api op=remove  exe="/usr/bin/docker-current" hostname=? addr=? terminal=? res=success'

docker-current[728]: time="2018-05-28T12:03:55.122918913+03:00" level=info msg="{Action=start, ID=0118b77644c97b1a209fa82e1da7f72b1440db1554c4cf0d5b2faf2cc31e9911, Username=root, LoginUID=0, PID=24042, Config={Hostname=0118b77644c9, AttachStdin=false, AttachStdout=false, AttachStderr=false, ExposedPorts=map[5000/tcp:{}], Tty=true, OpenStdin=true, StdinOnce=false, Env=[REGISTRY_AUTH=htpasswd REGISTRY_AUTH_HTPASSWD_REALM=Registry Realm REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd REGISTRY_HTTP_TLS_CERTIFICATE=/certs/live/hub.xxxxx.com/fullchain.pem REGISTRY_HTTP_TLS_KEY=/certs/live/hub.xxxxx.com/privkey.pem PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin], Cmd={parts:[/etc/docker/registry/config.yml]}, ArgsEscaped=false, Image=docker.io/registry, Volumes=map[/var/lib/registry:{}], Entrypoint={parts:[/entrypoint.sh]}, NetworkDisabled=false, Labels=map[]}, HostConfig={Binds=[/home/auth:/auth /home/nfs/registry:/var/lib/registry /etc/letsencrypt:/certs], LogConfig={Type:journald Config:map[]}, NetworkMode=default, PortBindings=map[5000/tcp:[{HostIP: HostPort:5000}]], RestartPolicy={Name:always MaximumRetryCount:0}, DNS=[], DNSOptions=[], DNSSearch=[], Privileged=false, PublishAllPorts=false, ReadonlyRootfs=false, ShmSize=67108864, Resources={CPUShares:0 CgroupParent: BlkioWeight:0 BlkioWeightDevice:[] BlkioDeviceReadBps:[] BlkioDeviceWriteBps:[] BlkioDeviceReadIOps:[] BlkioDeviceWriteIOps:[] CPUPeriod:0 CPUQuota:0 CpusetCpus: CpusetMems: Devices:[] KernelMemory:0 Memory:0 MemoryReservation:0 MemorySwap:0 MemorySwappiness:0xc420c55e88 OomKillDisable:0xc420c55e92 PidsLimit:0 Ulimits:[]}}}"

audit[728]: VIRT_CONTROL pid=728 uid=0 auid=4294967295 ses=4294967295 msg='user=root auid=0 exe=/entrypoint.sh hostname=0118b77644c9 reason=api op=start vm=docker.io/registry vm-pid=0  exe="/usr/bin/docker-current" hostname=? addr=? terminal=? res=success'

audit[728]: VIRT_CONTROL pid=728 uid=0 auid=4294967295 ses=4294967295 msg='auid=0 exe=/entrypoint.sh hostname=0118b77644c9 reason=api op=logs vm=docker.io/registry vm-pid=24116 user=root  exe="/usr/bin/docker-current" hostname=? addr=? terminal=? res=success'

audit[728]: VIRT_CONTROL pid=728 uid=0 auid=4294967295 ses=4294967295 msg='exe=/entrypoint.sh hostname=0118b77644c9 reason=api op=logs vm=docker.io/registry vm-pid=24116 user=root auid=0  exe="/usr/bin/docker-current" hostname=? addr=? terminal=? res=success'

docker-current[728]: time="2018-05-28T20:13:34.356550899+03:00" level=warning msg="Error getting v2 registry: Get https://hub.xxxxx.com:5000/v2/: EOF"

docker-current[728]: time="2018-05-28T20:14:33.276700279+03:00" level=warning msg="Error getting v2 registry: Get https://localhost:5000/v2/: read tcp [::1]:35602->[::1]:5000: read: connection reset by peer"

docker-current[728]: time="2018-05-28T20:14:33.284392448+03:00" level=warning msg="Error getting v2 registry: Get http://localhost:5000/v2/: read tcp [::1]:35606->[::1]:5000: read: connection reset by peer"

docker-current[728]: time="2018-05-28T20:14:49.965804694+03:00" level=warning msg="Error getting v2 registry: Get https://hub.xxxxx.com:5000/v2/: read tcp vv.xx.yy.zz:50572->vv.xx.yy.zz:5000: read: connection reset by peer"

docker-current[728]: time="2018-05-28T20:14:55.538936648+03:00" level=warning msg="Error getting v2 registry: Get https://hub.xxxxx.com:5000/v2/: read tcp vv.xx.yy.zz:50586->vv.xx.yy.zz:5000: read: connection reset by peer"

docker-current[728]: time="2018-05-28T20:16:47.899323118+03:00" level=warning msg="Error getting v2 registry: Get https://hub.xxxxx.com:5000/v2/: read tcp vv.xx.yy.zz:50612->vv.xx.yy.zz:5000: read: connection reset by peer"

docker-current[728]: time="2018-05-28T20:16:51.081611941+03:00" level=warning msg="Error getting v2 registry: Get https://hub.xxxxx.com:5000/v2/: read tcp vv.xx.yy.zz:50626->vv.xx.yy.zz:5000: read: connection reset by peer"

systemd[1]: Unmounting /home/nfs/registry...

systemd[1]: Unmounted /home/nfs/registry.

**Comment by stefanand** [comment]
but when I run journalctl again...I get nothing...so it might be that the above is not the error message

**Comment by TomSweeneyRedHat** [comment]
@stefanand thanks for the registry command that you use.  The only thing that jumps out at me is the --restart-always param.  I don't think I've used that myself in my testing yet.  If you've a spare moment and could try removing that and see if you still have the problem, that would be an interesting data point to have.  If not, no worries, I'll try to run it myself in the near future to see if I can replicate.

**Comment by pixdrift** [comment]
@stefanand, you can push to this same registry using docker as the client? it's only when buildah is a client that it's an issue?

Is it a self signed cert running on the repository?

**Comment by stefanand** [comment]
additionally, it worked before the last upgrade...no error message at that time!

**Comment by stefanand** [comment]
@pixdrift I don't seem to get the error when using Docker as a client. Only when buildah is used as a client.

No self-cert! As you can see it is a LetsEncrypt certificate. It worked well before the update of buildah.

**Comment by stefanand** [comment]
@pixdrift I don't seem to get the error when using Docker as a client. Only when buildah is used as a client.

No self-cert! As you can see it is a LetsEncrypt certificate. It worked well before the update of buildah.

**Comment by TomSweeneyRedHat** [comment]
@stefanand Do you recall by chance which version of Buildah you were on prior?  v0.16 perhaps?

**Comment by pixdrift** [comment]
Thanks for the responses @stefanand

+1 to @TomSweeneyRedHat's suggestion here, if you can get the `buildah version` from a previous working version, it would be an excellent help.

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Comment by stefanand** [comment]
Current version:

Name        : buildah
Version     : 1.0
Release     : 1.git1ab80bc.fc28
Architecture: x86_64

Previous version:
buildah-0.16-1.git82529cd.fc28.x86_64

**Comment by TomSweeneyRedHat** [comment]
Thanks for the older version @stefanand !

**Comment by stefanand** [comment]
Wait and I will have to check one more thing and see if it leads me to a clue....before any further work!

**Comment by mtrmac** [comment]
This looks as if the registry server was crashing inside the container.

If you reproduce this without `--restart=always`, and after you get the
```
Get https://hub.xxxxx.com:5000/v2/: dial tcp vv.xx.yy.zz:5000: connect: connection refused
```
can you connect to the registry again (with any client) and use it?

If not, can you collect the logs of the registry server, both as it is serving requests successfully and most importantly when it stops to do so?

**Comment by TomSweeneyRedHat** [comment]
@stefanand as I've not been able to reproduce this and we've not heard anything further for quite a while, I'm going to close this issue.  Please reopen or create a new issue as you see appropriate if you continue to have problems with this.
