### ISSUE TITLE
No way to provide 'exec form' to buildah config --entrypoint

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#732]
The Dockerfile ENTRYPOINT parameter provides two 'forms' of operation, that behave slightly differently. These forms are summarised in the Docker documentation here:
https://docs.docker.com/engine/reference/builder/#entrypoint

If an `array` is used for ENTRYPOINT, the command is interpreted as `exec` form
If a `string` is used for ENTRYPOINT, the command is interpreted as `shell` form

Unfortunately, the `shell` form doesn't take parameters in that are passed to the container.

The problem is, `buildah config --entrypoint` can only take a string parameter, so you can't currently configure a container with `buildah config` to use the `exec` (`array`) preferred form.

The differences in the behaviour can be seen in the following Dockerfile examples:

If `ENTRYPOINT` is declared as an array:
```
FROM centos
ADD showparams.sh /
ENTRYPOINT [ "/showparams.sh" ]
```

Results in:
```
            "Entrypoint": [
                "/showparams.sh"
            ],
```

If `ENTRYPOINT` is declared as a string:
```
FROM centos
ADD showparams.sh /
ENTRYPOINT /showparams.sh
```

Results in:
```
            "Entrypoint": [
                "/bin/sh",
                "-c",
                "/showparams.sh"
            ],
```

**Comment by TomSweeneyRedHat** [comment]
Talking with @pixdrift via IRC:

```
tsweeney> any reason to not just do it the Docker style?  
<tsweeney> [ "/showparams.sh", "myinputdata" ]
<tsweeney> as a for instance.
<pixdrift> complex to parse on command line?
<pixdrift> although possibly not..
<pixdrift> maybe if it was hard quoted?
<pixdrift> --entrypoint '[ "/showparams.sh", "myinputdata" ]'
<tsweeney> yeah, something like that with doc.
<pixdrift> although.. you could check if the first character is '[' and parse accordingly
<tsweeney> yep, that too.
```

**Comment by TomSweeneyRedHat** [comment]
@rhatdan and/or @nalind WDYT?

**Comment by rhatdan** [comment]
Tom can you see if you can get this to work.

**Comment by rhatdan** [comment]
@pixdrift Now that we have the PR Merged can we close this issue?

**Comment by pixdrift** [comment]
Yep.
