### ISSUE TITLE
buildah push can't handle ~ in local path

### ISSUE THREAD

**Issue by kallisti5** [projectatomic/buildah#777]
It's mostly a convenience thing, but buildah push can't handle  ~ in a local path.

```
sudo buildah push 82a6ded730f1 oci:~/glassfish.oci:latest
lstat /home/alex/work-docker/glassfish/~: no such file or directory
```

```
$ sudo buildah push 82a6ded730f1 oci-archive:~/glassfish.oci:latest
lstat /home/alex/work-docker/glassfish/~: no such file or directory
```

```
$ sudo buildah push 82a6ded730f1 docker-archive:~/glassfish.docker:latest
error pushing image "82a6ded730f1" to "docker-archive:~/glassfish.docker:latest": error copying layers and metadata: Error initializing destination docker-archive:~/glassfish.docker:docker.io/library/latest:latest: error opening file "~/glassfish.docker": open ~/glassfish.docker: no such file or directory
```

buildah version 1.0 (image-spec 1.0.0, runtime-spec 1.0.0)

**Comment by TomSweeneyRedHat** [comment]
@kallisti5 Well that's an interesting little bug.  Thanks for reporting it, will take a look.

**Comment by pixdrift** [comment]
@kallisti5, this is expected behaviour for tilde (~) expansion.

It is only expanded by the shell if the tilde is as the start of a word. Documented here:
https://www.gnu.org/software/libc/manual/html_node/Tilde-Expansion.html

Example showing this:
```
ls -l .~
ls: cannot access .~: No such file or directory
```

Alternatively you could use `$HOME`

**Comment by TomSweeneyRedHat** [comment]
@kallisti5 thanks for reporting this.  After a bunch of discussion we've decided to not make any changes in the code, but rather have added a note to or troubleshooting guide.
