### ISSUE TITLE
buildah  build-using-dockerfile URL not work

### ISSUE THREAD

**Issue by gouyang** [projectatomic/buildah#80]
```
$ sudo ./buildah  build-using-dockerfile  -f http://10.66.10.10/pub/Dockerfile
ERRO[0000] no context directory specified, and no dockerfile specified 
$ sudo ./buildah  build-using-dockerfile   http://10.66.10.10/pub/Dockerfile
ERRO[0000] error prepping temporary context directory: Error processing tar file(exit status 1): unexpected EOF 
```

**Comment by nalind** [comment]
If the dockerfile location is a remote URL, we don't do what we would if it was a file, which would be to assume that taking the filename off of the end would produce a useful default for the build context directory if one isn't explicitly specified.  `http` and `https` build contexts need to be a tarball of some kind, and it's unlikely that stripping off the final component of the URL and then attempting to fetch that would produce one, so we don't do that.  If there's an archive of the context directory, or a local filesystem path, you'll need to specify its location, too.  I'll update the card to note that.

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(8) [Buildah] Add "dockah build-using-dockerfile" aka "buildah bud"](https://trello.com/c/AyBXqoRY/443-8-buildah-add-dockah-build-using-dockerfile-aka-buildah-bud)

**Comment by gouyang** [comment]
`sudo ./buildah bud http://10.73.2.5/pub/Dockerfile.tar.gz` works,  but `sudo ./buildah bud  -f http://10.73.2.5/pub/Dockerfile.tar.gz` or `sudo ./buildah bud -f http://10.73.2.5/pub/Dockerfile` does not work.

@nalind Could you show me how `buildah bud -f URL` can work?

**Comment by nalind** [comment]
@gouyang If the dockerfile location is a remote URL (it can't be an archive), a context location has to be explicitly provided.  So your three examples would be
* ./buildah bud http://10.73.2.5/pub/Dockerfile.tar.gz
  Accepted if the context, which in this case is an archive, contains a Dockerfile.
* ./buildah bud -f http://10.73.2.5/pub/Dockerfile.tar.gz
  Rejected: the Dockerfile can't itself be an archive.
* ./buildah bud -f http://10.73.2.5/pub/Dockerfile
  Rejected: no build context was provided, and because the Dockerfile is specified as a remote URL, we don't guess that the directory that it's in was intended to be used as the context.

**Comment by gouyang** [comment]
@nalind I still could not make it work and don't know how it would work, all I want is an example for `buildah bud -f URL`.

**Comment by nalind** [comment]
Using just the `-f` flag with a URL isn't expected to work.  A build context has to be specified if the Dockerfile is a remote URL.

**Comment by rhatdan** [comment]
@nalind Should it?

**Comment by nalind** [comment]
@rhatdan I don't think it can unless we assume that the location that hosts the Dockerfile also supports something like webdav so that we can traverse the location without having to scrape through HTML representations of directory listings.  That's probably not a realistic assumption to make.

**Comment by rhatdan** [comment]
If the directory is not specified then no build context is specified.  Translation COPY/ADD will fail if used.

buildah from -f https://people.redhat.com/Dockerfile
buildah from -f https://people.redhat.com/Dockerfile .

**Comment by gouyang** [comment]
`buildah bud -f URL .` works if the URL specify a Dockerfile.
```
[root@fedora buildah-ansible]# buildah bud -f http://10.73.3.165/pub/Dockerfile .
STEP 1: FROM fedora
STEP 2: RUN dnf -y update 
Fedora 26 - x86_64 - Updates                                                                   16 MB/s |  12 MB     00:00    
...

```

It not work with if the URL specify a tarball. I think it's the right behavior.

```
[root@fedora buildah-ansible]# buildah bud -f http://10.73.3.165/pub/Dockerfile.tar.gz .
ERRO[0000] error building: error determining starting point for build: no FROM statement found 

```

**Comment by gouyang** [comment]
Close the issue now, please re-open it if it's necessary.
