### ISSUE TITLE
Fresh install "buildah from fedora" tries localhost registry

### ISSUE THREAD

**Issue by LemonIceScream** [projectatomic/buildah#810]
**Description**

buildah is unable to pull an image using the examples:

    [pomelo ~] buildah from fedora
    Get https://localhost/v2/: dial tcp 127.0.0.1:443: connect: connection `refused`

I see references in the documentation to /etc/containers but it did not exist. After installing skopeo it appeared but continued to not work.

Running both "skopeo inspect docker://fedora" and "skopeo inspect docker://docker.io/fedora" look like they're working (produce two results from docker.io).

I feel like I am missing something. What do I need to configure? What's the documentation? Where can I find it?

**/etc/containers configuration**
```
[pomelo /etc/containers] find .
.
./registries.d
./registries.d/default.yaml
./policy.json
[pomelo /etc/containers] cat policy.json 
{
    "default": [
        {
            "type": "insecureAcceptAnything"
        }
    ],
    "transports":
        {
            "docker-daemon":
                {
                    "": [{"type":"insecureAcceptAnything"}]
                }
        }
}
[pomelo /etc/containers] cat registries.d/default.yaml 
# This is a default registries.d configuration file.  You may
# add to this file or create additional files in registries.d/.
#
# sigstore: indicates a location that is read and write
# sigstore-staging: indicates a location that is only for write
#
# sigstore and sigstore-staging take a value of the following:
#   sigstore:  {schema}://location
#
# For reading signatures, schema may be http, https, or file.
# For writing signatures, schema may only be file.

# This is the default signature write location for docker registries.
default-docker:
#  sigstore: file:///var/lib/atomic/sigstore
  sigstore-staging: file:///var/lib/atomic/sigstore

# The 'docker' indicator here is the start of the configuration
# for docker registries.
#
# docker:
#
#   privateregistry.com:
#    sigstore: http://privateregistry.com/sigstore/
#    sigstore-staging: /mnt/nfs/privateregistry/sigstore
```

**Output of `rpm -q buildah` or `apt list buildah`:**

```
Installed via Arch: https://www.archlinux.org/packages/community/x86_64/buildah/
skopeo: https://www.archlinux.org/packages/community/x86_64/skopeo/
```

**Output of `buildah version`:**

```
[pomelo ~] buildah version
Version:       1.0
Go Version:    go1.10.2
Image Spec:    1.0.0
Runtime Spec:  1.0.0
Git Commit:    1ab80bcd
Built:         Fri May 11 07:14:04 2018
OS/Arch:       linux/amd64
```

**Output of `cat /etc/*release`:**

```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
ID_LIKE=archlinux
ANSI_COLOR="0;36"
HOME_URL="https://www.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
```

**Output of `uname -a`:**

```
Linux pomelo 4.16.10-1-ARCH #1 SMP PREEMPT Mon May 21 07:57:23 UTC 2018 x86_64 GNU/Linux
```

**Output of `cat /etc/containers/storage.conf`:**

```
cat: /etc/containers/storage.conf: No such file or directory
```
In addition to the above, I have also tried with the current LaunchPad version with the same results:

```
buildah version 1.2-dev (image-spec 1.0.0, runtime-spec 1.0.0)
```

**Comment by rhatdan** [comment]
On Fedora we ship registries.conf which podman/buildah/crio use to identify the container registries they will use.


```
 cat /etc/containers/registries.conf
# This is a system-wide configuration file used to
# keep track of registries for various container backends.
# It adheres to TOML format and does not support recursive
# lists of registries.

# The default location for this configuration file is /etc/containers/registries.conf.

# The only valid categories are: 'registries.search', 'registries.insecure', 
# and 'registries.block'.

[registries.search]
registries = ['docker.io', 'quay.io', 'registry.fedoraproject.org', 'registry.access.redhat.com']
#registries = ['registry.access.redhat.com']

# If you need to access insecure registries, add the registry's fully-qualified name.
# An insecure registry is one that does not have a valid SSL certificate or only does HTTP.
[registries.insecure]
registries = []


# If you need to block pull access from a registry, uncomment the section below
# and add the registries fully-qualified name.
#
# Docker only
[registries.block]
registries = []
```

**Comment by LemonIceScream** [comment]
That registries.conf works great. Thank you for improving the installation notes in #811 too, it has helped greatly!

You asked what manpages I looked at - typically when I try to take in a new program I'll start at the top of what looks like the main manpage and use the Github as a guide. I believe the FILES section could be updated with something similar to what install.md now provides: document where the packages where the file dependencies lie and maybe an example.

**Comment by rhatdan** [comment]
man buildah currently has
```
       storage.conf (/etc/containers/storage.conf)

              storage.conf is the storage configuration file for all tools using containers/storage

              The storage configuration file specifies all of the available container storage options for tools using shared container storage.

       mounts.conf (/usr/share/containers/mounts.conf and optionally /etc/containers/mounts.conf)

              The mounts.conf files specify volume mount directories that are automatically mounted inside containers when executing the `buildah run` or `buildah build-using-dockerfile` commands.  Container process can then use this content.  The volume mount content does not get committed to the final image.

              Usually these directories are used for passing secrets or credentials required by the package software to access remote package repositories.

              For example, a mounts.conf with the line "`/usr/share/rhel/secrets:/run/secrets`", the content of `/usr/share/rhel/secrets` directory is mounted on `/run/secrets` inside the container.  This mountpoint allows Red Hat Enterprise Linux subscriptions from the host to be used within the container.

              Note this is not a volume mount. The content of the volumes is copied into container storage, not bind mounted directly from the host.

       registries.conf (/etc/containers/registries.conf)

              registries.conf is the configuration file which specifies which registries should be consulted when completing image names which do not include a registry or domain portion.
```

I don't want to specify any packages for this, since different distributions, might package them differently.  I can add a reference to registries.conf(5) man page, which is missing.

I guess we could add the example configurations.

**Comment by LemonIceScream** [comment]
Here's how I approached it:

(1) I ran "buildah from fedora" and received an error saying it can't pull from localhost.
(2) I check the manpage "buildah-from" for the format of imageName.
(3) I see that it's broken down into "transport:details" and that the default is "docker://".
(4) I guess that the transport is optional as "scratch" can be used for an empty container but I assume I can still have image names called "scratch" somehow.
(5) So I assume "fedora" relates to docker-reference and that it's falling back to a localhost registry.
(6) I begin looking for registry configuration, unsure of whether it was auto-created or another package was to provide it.
(7) I checked the Arch and then the Ubuntu package and didn't find anything. It looked like the Ubuntu package was set up by the project itself so I assumed it was set up as expected.

From my naive viewpoint this seems like a hidden dependency since I have to be able to know about and write the configuration file to use buildah as expected. A link to the format documentation from the manpages would be good. I agree that specifying it in buildah's documentation wouldn't make sense nor would a full-on dependency since it's only a single, shared configuration file.

The other minor thing might be that the buildah-from manpage only references the registry as "registry name" but doesn't say where registry names are specified. It might be clearer as "If  docker-reference  does  not  include a registry name specified in registries.conf, ...".

Thank you for the quick fix last Friday evening, I hope this helps.

**Comment by pixdrift** [comment]
I had pain with registries.conf just today, so I understand where @LemonIceScream is coming from.

It also loops back to the PR we have discussed in the past regarding containers-common because it's not obvious where registries.conf is coming from (on CentOS the file itself says it comes from atomic-containers, but it actually comes from a skopeo package)
https://github.com/projectatomic/skopeo/pull/497

**Comment by rhatdan** [comment]
Well the errors are much better now.
```
# mv /etc/containers/registries.conf /etc/containers/registries.conf.old
# buildah from centos
image "centos" not found in /etc/containers/registries.conf registries: image not known
```
 Registries.conf is really a distro file, we can't force one file on all distros, which is why it is buried in the skopeo package fedora/RHEL/Centos look aside cash.
containers-common (formarly skopeo-containers0 is still a sub package of skoeo.)  We will be looking to make it a standalone package in github.com/containers/containers-commont.  That might make it easier to ship and find.

**Comment by TomSweeneyRedHat** [comment]
The man pages around registries.conf have been touched up to hopefully make this more clear and we've touched up the docs in a few other spots.  I'm going to close this now.  @LemonIceScream please create a new issue or reopen this one as appropriate if you're still having issues in this space.

**Comment by daurnimator** [comment]
I'm not able to figure out the incantation to run buildah. I installed it on arch (`pacman -S buildah`) and tried to run: `sudo buildah from debian:9` which fails with:

> image "debian:9" not found in /etc/containers/registries.conf registries: image not known

So I added the registries.conf file mentioned above. However I still get the same error.
I also tried

  - `sudo buildah from docker://debian:9`
  - `sudo buildah from docker://_:debian:9`
  - `sudo buildah from docker-daemon:debian:9`
  - `sudo buildah from docker://registry.hub.docker.com/library/debian:9`
  - `sudo buildah from http://registry.hub.docker.com/library/debian:9`
  - `sudo buildah from docker.io:debian:9` (as this is in the registries.conf file)

and more. All fail with a similar error message.

**Comment by rhatdan** [comment]
Works for me on Fedora

```
# buildah from debian:9
Getting image source signatures
Copying blob sha256:05d1a5232b461a4b35424129580054caa878cd56f100e34282510bd4b4082e4d
 43.21 MiB / 43.21 MiB [====================================================] 2s
Copying config sha256:f2aae6ff5d896839bfb8609cb1510bcf36efcb6950683c3bcfb760668b0eefbe
 1.47 KiB / 1.47 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
debian-working-container
# cat /etc/containers/registries.conf
# This is a system-wide configuration file used to
# keep track of registries for various container backends.
# It adheres to TOML format and does not support recursive
# lists of registries.

# The default location for this configuration file is /etc/containers/registries.conf.

# The only valid categories are: 'registries.search', 'registries.insecure', 
# and 'registries.block'.

[registries.search]
registries = ['docker.io', 'quay.io', 'registry.fedoraproject.org', 'registry.access.redhat.com']
#registries = ['registry.access.redhat.com']

# If you need to access insecure registries, add the registry's fully-qualified name.
# An insecure registry is one that does not have a valid SSL certificate or only does HTTP.
[registries.insecure]
registries = []


# If you need to block pull access from a registry, uncomment the section below
# and add the registries fully-qualified name.
#
# Docker only
[registries.block]
registries = []
```

**Comment by rhatdan** [comment]
Does ` buildah from docker.io/debian:9` work for you?

**Comment by daurnimator** [comment]
> @daurnimator the other thing to verify is the existence of an /etc/containers/policy.json file. If it does not exist, copy one from here https://github.com/projectatomic/buildah/blob/master/tests/policy.json. Note this is probably not what you want to use long term in a production environment.

The issue was solved by adding that policy.json file. It appears that on arch, that file is provided by the skopeo package rather than buildah.
However discovering this information was next to impossible: could someone update the docs to make it obvious that policy.json is required?
Should a bug be filed with archlinux (or skopeo) about the home for the policy.json file?

**Comment by JJ** [comment]
I've experienced this same error in Ubuntu 16.04. The registries.conf is in the correct place, however. Similar error in docker was due to a problem with the wifi configuration, solved adding nameservers to a daemon.json file or some such. Could that be the case here too?
