### ISSUE TITLE
BUD Conversion from ARG to ENV failing

### ISSUE THREAD

**Issue by kbaegis** [projectatomic/buildah#813]
**Description**

Dockerfiles can typically convert an ARG (temporary) into an ENV (part of the image) with the following syntax. This is failing with buildah bud 

**Steps to reproduce the issue:**
Dockerfile with:
ARG RSYNCURI="rsync://crucible.mgmt/gentoo-portage"
...
ENV RSYNCURI="$RSYNCURI"

**Describe the results you received:**

On build:
!!! sync-uri is invalid: $RSYNCURI

**Describe the results you expected:**

Expansion of ENV $RSYNCURI from ARG

**Output of `buildah version`:**

buildah version 1.2-dev (image-spec 1.0.0, runtime-spec 1.0.0)

**Output of `uname -a`:**

Linux 2c42111be6e7 4.17.0-gentoo #1 SMP Thu Jun 7 02:49:57 UTC 2018 x86_64 Intel(R) Xeon(R) CPU D-1587 @ 1.70GHz GenuineIntel GNU/Linux

**Comment by TomSweeneyRedHat** [comment]
Closing ast #816 addresses this.  @kbaegis if you find otherswise, please reopen or start a new issue as appropriate.
