### ISSUE TITLE
We should be able to output images in non-OCI formats

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#85]
We've always produced images that included OCI manifests and configuration data.  We should be able to also produce images in a format that can be consumed by dockerd, if only for the sake of being simpler to integrate into other tooling which has historically only produced images in that format.

**Comment by rhatdan** [comment]
Add --format [ oci, dockerv2 ]

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Get buildah to support docker image format](https://trello.com/c/Bu0QQfjd/482-get-buildah-to-support-docker-image-format)

**Comment by rhatdan** [comment]
@nalind Doesn't https://github.com/projectatomic/buildah/pull/118 satisfy this issue?  Can we close?

**Comment by nalind** [comment]
Yes, though for simplicity's sake we also accept `docker` (until we need to be more specific, like if we ever add support for v2s1) as a type.
