### ISSUE TITLE
buildah bud --file, -f regression / change in behaviour

### ISSUE THREAD

**Issue by pixdrift** [projectatomic/buildah#850]
**Description**
From the `buildah bud` documentation, it is suggested that the `--file / -f` switch can take multiple Dockerfiles and the context is optional.

> Specifies a Dockerfile which contains instructions for building the image, either a local file or an http or https URL. If more than one Dockerfile is specified, FROM instructions will only be accepted from the first specified file.
>
> If a build context is not specified, and at least one Dockerfile is a local file, the directory in which it resides will be used as the build context.

It appears that changes to buildah have made context _required_ which in turn has made the multiple Dockerfile feature less intuitive.

One of the benefits of building using multiple Dockerfiles (or slices/shards/snippets) is code re-use, ie. Multiple Dockerfiles can share a subset of code stored in a separate file. As the option currently works, the context is required and all additional files that are provided are relative paths in the provided context.

**Steps to reproduce the issue:**
A use case I was expecting to use this feature for was
```
container1/Dockerfile
container2/Dockerfile
common/Dockerfile
```

In this scenario, I was expecting to be able to execute (from the root) so the conainerX executes first and then the contents of common is appended:
```
buildah bud -f container1/Dockerfile -f common/Dockerfile
buildah bud -f container2/Dockerfile -f common/Dockerfile
```
This results in:
```
# buildah bud -f container1/Dockerfile -f common/Dockerfile
no context directory or URL specified
```

If you provide a context directory as it is now required, it uses this for the base path of images supplied using `-f`:
```
# buildah bud -f common/Dockerfile container1
error reading "/root/multi/container1/common/Dockerfile": open /root/multi/container1/common/Dockerfile: no such file or directory
```

To make this work, it's somewhat counter intuitive. The context needs to be set, and the Dockerfile specified as the first `-f`, then a drop back to the parent directory. It does work, but it would be much cleaner without the context requirement.
```
buildah bud -f Dockerfile -f ../common/Dockerfile container1
```

**Describe the results you received:**
Errors / issues when executing `buildah bud -f` and specifying multiple images without context.

**Describe the results you expected:**
Ability to build containers from Dockerfiles using shared elements/includes as described in the buildah documentation for `buildah bud -f`.

**Output of `rpm -q buildah`:**

```
buildah-1.2-201807041005.gita59fb7a.el7.x86_64
```

**Output of `buildah version`:**

```
Version:         1.2-dev
Go Version:      go1.9.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      a59fb7a
Built:           Wed Jul  4 21:01:24 2018
OS/Arch:         linux/amd64
```

**Output of `cat /etc/*release`:**

```
CentOS Linux release 7.5.1804 (Core)
```

**Comment by pixdrift** [comment]
I also wanted to raise in this thread the possibility of inclusion of an `INCLUDE` feature in the Dockerfile parser (`bud`), to essentially achieve the same as above. This has been raised / rejected several times in Docker/moby issues, but interested to know if there is any precedent in Buildah for support of additional features in the Dockerfile, or if `bud` is purely for compatibility with existing features.

Proposal discussions for include in Docker/Moby:
https://github.com/moby/moby/issues/735
https://github.com/moby/moby/pull/12749

I don't really see this as including a entire existing Dockerfiles (ie. with their own FROM), more to include common code blocks/snippets. I have achieved the same using native `buildah run` and `source` to pull in common code blocks, but would still be interested in comments on the above idea.

**Comment by TomSweeneyRedHat** [comment]
I've created a new issue #851 for the INCLUDE discussion/enhancement.  Let's work through that there.  A good idea me thinks.

**Comment by rhatdan** [comment]
@pixdrift I thought we still had the feature to be able to grab a Dockerfile from anywhere, which I liked.  The only change we were supposed to make was to force the specification of the context dir, matching Docker.  Allowing specification of Multiple Dockerfiles and having them not be relative to the Context dir, seems like a good idea.

**Comment by TomSweeneyRedHat** [comment]
I've poked at this a bit, I'm not sure what (if?) we should adjust here.  I created two directories at root: container1 and container 2.  I put a Dockerfile in each and ran this Buildah command from /root:

```
# buildah bud -f container2/Dockerfile container1
error reading "/root/container1/container2/Dockerfile": open /root/container1/container2/Dockerfile: no such file or directory
```
Then I ran the equivalent Docker command:

```
# docker build -f container2/Dockerfile container1
unable to prepare context: The Dockerfile (/root/container2/Dockerfile) must be within the build context (container1)
```
Further, if you add the '..' to the container2/Dockerfile, Buildah works, but Docker still fails.

```
# buildah bud -f ../container2/Dockerfile container1
STEP 1: FROM busybox
{removed output for brevity}

# docker build -f ../container2/Dockerfile container1
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /container2: no such file or directory
```
Currently we're prepending the context directory onto the Dockerfile in Buildah.  I could stop doing that but that would be a different behavior then Docker.  Happy to stop prepending, but thought I'd double check first.  Rather than that, I could prop up the error a bit to add a reference to the context directory to the verbiage.

Thoughts?

**Comment by TomSweeneyRedHat** [comment]
@rhatdan @nalind thoughts on what should happen here?  In specific what I described in my last comment?  I think it's OK as is, but would like to hear your opinions.

**Comment by rhatdan** [comment]
Well @vrothberg just got support for Dockerfile.in, to allow users to specify a dockerfile with a 
#include PATHTODockefile

buildah executes cpp to preprocess and suck the include file into the Dockerfile. That is half of what this Issue requests.

But I would like the Dockerfile to be pathbased and not require the path to be based on the context directory

buildah bud -f container2/Dockerfile ~
I would expect would look in the subdir of my current dir, and not in ~/container2/Dockerfile.

```
# podman build -f Dockerfile.suse  ~/dwalsh
error reading "/root/dwalsh/Dockerfile.suse": open /root/dwalsh/Dockerfile.suse: no such file or directory
# podman build -f ./Dockerfile.suse  ~/dwalsh
error reading "/root/dwalsh/Dockerfile.suse": open /root/dwalsh/Dockerfile.suse: no such file or directory
# podman build -f ~/Dockerfile.suse  ~/dwalsh
STEP 1: FROM opensuse:tumbleweed
 podman build -f $PWD/Dockerfile.suse  ~/dwalsh
STEP 1: FROM opensuse:tumbleweed
```

So it looks like it is relative if unless the path starts with a /? I just checked buildah bud works the same way.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan Yeah my question was only on the first part of this issue.  The work that @vrotherberg did with the Dockerfile.in files covers the issue that I spun off from this.

Basically `'buildah bud` prepends the context directory to the filename pased in via the '--file' parameter unless the filename either starts with '/' or '~/'.  It looks like Docker uses the context directory as the starting point to do a find of the file passed in and errors if it doesn't find it.  So this works:

buildah bud -f ~/containers2/Dockerfile /root/container1

and this does not:
docker build -f  ~/containers2/Dockerfile /root/container1

So I'll see if I can stop the prepending of the context directory to the value passed in via the --file parameter.  That way the value passed in to the --file parameter will use the current directory if it's a relative directory value, or just the value if it's fully specified.  I like that.  Holler if that doesn't work.

**Comment by rhatdan** [comment]
Perhaps we could do both.  Search relative to the current directory if the path is specified if the file does not exist, then search relative to the context directory.

**Comment by rhatdan** [comment]
Since @TomSweeneyRedHat patch has merged, closing this issue.
