### ISSUE TITLE
ENH: 'buildah pull' Do a pull without creating a container.

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#887]
This is a feature request/enhancement discussion. The below is a IRC chat that I'd with @pixdrift the other night. I wanted to capture the thoughts so we could discuss further here.

**Description**
```
<pixdrift> another one I also wanted to ask, was has 'buildah pull' been discussed?
<pixdrift> When re-tagging, buildah pull <image>:<tag> && buildah push <image>:<newtag> comes up a bit
<pixdrift> at the moment, the only real option is 'buildah from' which creates the temp container, so the work around has been `buildah rm $(buildah from <image>:<tag>)'
<pixdrift> where buildah pull could essentially do the same as 'buildah from' without the temp container 

```

@pixdrift please feel free to add further details or correct me if any of this is incorrect.

My first thought was to do a new param like --nocontainer for `buildah from` that causes the image to just be pulled and saved locally and not create the container.  Haven't delved into it any further than that.

**Comment by rhatdan** [comment]
I would prefer buildah pull since it is much easier to discover and matches up with buildah push.

**Comment by TomSweeneyRedHat** [comment]
OKD, I'll make it so.  ;^)

**Comment by TomSweeneyRedHat** [comment]
Closing as #889 addresses this.
