### ISSUE TITLE
EPERM building as a limited user inside a container

### ISSUE THREAD

**Issue by vbatts** [projectatomic/buildah#912]
**Description**
EPERM on RUN command

**Steps to reproduce the issue:**
1. built a buildah build-image (runc master and buildah master)
2. Tried to build cri-o Dockerfile (master) as a limited user inside a container
3.

**Describe the results you received:**
```
STEP 2: RUN echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/backports.list
error running container: error creating container for [/bin/sh -c echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/backports.list]: container_linux.go:336: starting container process caused "process_linux.go:402: container init caused \"rootfs_linux.go:57: mounting \\\"/proc\\\" to rootfs \\\"/tmp/buildah799604934/mnt/rootfs\\\" at \\\"/proc\\\" caused \\\"operation not permitted\\\"\""
: exit status 1
```

**Describe the results you expected:**
sucessful build

**Output of `buildah version`:**

```
[root@c599e5432945 /]# buildah version
Version:         1.4-dev
Go Version:      go1.9.4
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      308ad3d
Built:           Tue Aug  7 13:32:25 2018
OS/Arch:         linux/amd64
[root@54ea92e38133 /]# runc --version
runc version 1.0.0-rc5+dev
commit: 4056a41f58e35fd428d517de1326bc465aa6a461
spec: 1.0.0
```

**Output of `cat /etc/*release`:**

this is inside the container
```
CentOS Linux release 7.5.1804 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.5.1804 (Core) 
CentOS Linux release 7.5.1804 (Core) 
```

**Output of `uname -a`:**

```
Linux c599e5432945 4.17.3-200.fc28.x86_64 #1 SMP Tue Jun 26 14:17:07 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

Dockerfile of the buildah image:
```dockerfile
FROM centos
ARG REVISION="master"

RUN \
  # Install buildah dependencies.
  yum -y install \
    make \
    golang \
    bats \
    btrfs-progs-devel \
    device-mapper-devel \
    glib2-devel \
    gpgme-devel \
    libassuan-devel \
    libseccomp-devel \
    ostree-devel \
    git \
    bzip2 \
    go-md2man \
    runc \
    skopeo-containers && \
  # Install buildah.
  mkdir ~/buildah && \
  cd ~/buildah && \
  export GOPATH=`pwd` && \
  git clone https://github.com/opencontainers/runc ./src/github.com/opencontainers/runc && \
  cd $GOPATH/src/github.com/opencontainers/runc && \
  make runc && \
  mv runc /usr/bin/runc && \
  cd $GOPATH/ && \
  git clone https://github.com/projectatomic/buildah ./src/github.com/projectatomic/buildah && \
  cd $GOPATH/src/github.com/projectatomic/buildah && \
  git checkout "${REVISION}" && \
  make && \
  make install && \
  buildah --help

ENTRYPOINT ["buildah"]
```

**Comment by vbatts** [comment]
and the cri-o commit of it's build is d724f3d54ad2d95b6de741085d4990190ebfd7ff

**Comment by rhatdan** [comment]
@giuseppe Is the kernel on Centos 7 and RHEL7 new enough to allow mounting of /proc and /sys file systems within a user namespace.

@nalind PTAL

**Comment by vbatts** [comment]
@rhatdan @giuseppe the host is f28, the container is centos7

**Comment by rhatdan** [comment]
SELinux?  Does setenforce 0 fix it?
AVC messages?

**Comment by vbatts** [comment]
selinux is already disabled on this host.

**Comment by vbatts** [comment]
(like, not even permissive. Fully disabled)

**Comment by giuseppe** [comment]
how to reproduce step 2?  I've tried to build both Dockerfile's and it worked for me, but I think I've done something different with "step 2" as I've tried to build directly the cri-o Dockerfile from the host

**Comment by vbatts** [comment]
hrm. The more full example, is that i'm testing https://github.com/knative/build-templates/pull/7
so, this build-image is running as a pod on a kubernetes v1.10.6 + cri-o v1.10.6 instance.
Let me try to reproduce with a more minimal set up.

**Comment by vbatts** [comment]
i'm wondering if it is trying to mount proc on a tmpfs filesystem?

**Comment by vbatts** [comment]
https://pastebin.com/ZPEHzAwc is the config.json that crio was running this pod with

**Comment by giuseppe** [comment]
the issue with running the container inside of the Docker/Podman container is that some `/proc` paths are masked.  This prevents the container spawned by Buildah to create new pid&user NS and mount `/proc` afterwards since that mount would be too "revealing", i.e. make visible paths that weren't visible before in the Docker/Podman context.
There are at least two ways to address it:

- have no readonly/masked paths in the first container
- don't create a PID namespace, so there is no need to mount a new procfs but re-use the already existing one

The second solution can be achieved setting the environment variable `"BUILDAH_ISOLATION=chroot"`

**Comment by vbatts** [comment]
ah, i just found that I reverted changes to the Dockerfile for this buildah builder image.
The EPERM is buildah running as uid=0 inside the container and thinking it has privilege. 
Last week I had
```Dockerfile
RUN adduser limited
USER limited
ENTRYPOINT ["buildah"]
```
Though now with adding that and building buildah from master, it failed with:
```
time="2018-08-10T20:22:49Z" level=error msg="error reading allowed ID mappings: error reading subuid mappings for user \"limited\" and subgid mappings for group \"limited\": No subuid ranges found for user \"limited\" in /etc/subuid"
```

So then I update Dockerfile to:
```Dockerfile
RUN adduser limited && \
  echo "limited:100000:65536" > /etc/subuid && \
  echo "limited:100000:65536" > /etc/subgid
USER limited
ENTRYPOINT ["buildah"]
```

And now it fails with:
```
Error: error running newgidmap: exec: "newgidmap": executable file not found in $PATH:
time="2018-08-10T20:35:00Z" level=error msg="error running newgidmap: : exec: \"newgidmap\": executable file not found in $PATH"
time="2018-08-10T20:35:00Z" level=error msg="(unable to determine exit status)"
```

**Comment by vbatts** [comment]
not enough testing of buildah is done on centos .... 
centos is now stuck due to less-than-latest shadow ...

**Comment by vbatts** [comment]
even if switching this to "FROM fedora" _works_, it would just defer the headache of considering that many folks will expect this to work the same on RHEL and centos

**Comment by vbatts** [comment]
switching to fedora yields a different error, and increased the image size by 500Mb. So I'm not going to add that as a stop-gap for now.

**Comment by vbatts** [comment]
closing this, as I've fixed the EPERM (and on to new issues with buildah support on Centos ... https://github.com/projectatomic/buildah/issues/926)

Dockerfile that got past EPERM inside container was to actually create and use a limited user while inside the container:
```Dockerfile
FROM centos
ARG REVISION="master"

RUN \
  # Install buildah dependencies.
  yum -y install \
    make \
    golang \
    bats \
    btrfs-progs-devel \
    device-mapper-devel \
    glib2-devel \
    gpgme-devel \
    libassuan-devel \
    libseccomp-devel \
    ostree-devel \
    git \
    bzip2 \
    go-md2man \
    runc \
    skopeo-containers && \
  # Install buildah.
  mkdir ~/buildah && \
  cd ~/buildah && \
  export GOPATH=`pwd` && \
  git clone https://github.com/opencontainers/runc ./src/github.com/opencontainers/runc && \
  cd $GOPATH/src/github.com/opencontainers/runc && \
  make runc && \
  mv runc /usr/bin/runc && \
  cd $GOPATH/ && \
  git clone https://github.com/projectatomic/buildah ./src/github.com/projectatomic/buildah && \
  cd $GOPATH/src/github.com/projectatomic/buildah && \
  git checkout "${REVISION}" && \
  make && \
  make install && \
  buildah --help

RUN adduser limited
USER limited
ENTRYPOINT ["buildah"]
```
