### ISSUE TITLE
Container envvar expansion issues

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#929]
**Description**

The  -- command for `buildah run` and echo doesn't seem to be working, further I can't figure out how to get an envvar passed into `buildah config` that will be expanded in the container rather than when the command is issued on the command line.  Something like:

```
buildah config --env 'GOPATH=$GOPATH/bin:$PATH' alpine-working-container
```
Where the value in the $GOPATH and $PATH envvar should have the values from the container rather than the host.

**Steps to reproduce the issue:**
1. export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/neverfoundpath
2. buildah from alpine
3. bulidah run alpine-working-container -- echo $PATH

**Describe the results you received:**
The path from the host rather than the container:

```
# buildah from alpine
alpine-working-container

# buildah run alpine-working-container -- echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/neverfoundpath

# buildah run alpine-working-container /bin/sh
/ # echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

**Describe the results you expected:**
The echo should show the value of the $PATH envvar from the container.

**Output of `buildah version`:**

```
buildah version
Version:         1.4-dev
Go Version:      go1.9.7
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      0a7389cb
Built:           Sun Aug 12 11:26:35 2018
OS/Arch:         linux/amd64

Originally reported by @vbatts

**Comment by TomSweeneyRedHat** [comment]
@vbatts fyi

**Comment by TomSweeneyRedHat** [comment]
@ipbabble if you've any sneaky bash tricks to help here, happy to use them!

**Comment by vbatts** [comment]
this is less than ideal since it'll create two layers that are no-op, but a work around is
```shell
buildah config --env PATH="$(buildah run -t ${from} sh -c 'echo -n $GOPATH')/bin:$(buildah run -t ${from} sh -c 'echo -n $PATH')" ${from}
```

**Comment by TomSweeneyRedHat** [comment]
Good thought, I'd completely forgotten about the echo -n trick.  But yeah, still not ideal.

**Comment by rhatdan** [comment]
Is this something that currently works in Docker?

**Comment by TomSweeneyRedHat** [comment]
I'm not sure that this is something that works in Docker.  I took a quick look this morning, but couldn't confirm or deny.

**Comment by vbatts** [comment]
@rhatdan this works as expected in Dockerfile `ENV` command with buildah and docker. But not in `buildah config --env ..`

**Comment by rhatdan** [comment]
Strange I can not see how this is happening in buildah bud, But we should be able to fix it.
@nalind Any ideas?

**Comment by TomSweeneyRedHat** [comment]
I'm pretty sure it's a bash completing thing.  I think we'll need to somehow recognize that certain variables that are in the command line for buildah should be expanded based on definitions on the host and at the same time allow others to not be expanded until they get in play on the container. I'm just puzzling on how to delineate them.

**Comment by giuseppe** [comment]
shouldn't the third command be something like:
`buildah run alpine-working-container -- sh -c 'echo $PATH'`?

As it is typed in the issue, the shell does the replacement before it is passed to buildah.  Similarly, `echo` alone is not enough and it prints literally `$PATH`.

**Comment by TomSweeneyRedHat** [comment]
@giuseppe That turns the trick for getting the path from the contain via a buildah run command, thx!  Think I'll add that as an example to the run man page.
