### ISSUE TITLE
buildah does not report progress when pulling images

### ISSUE THREAD

**Issue by jawnsy** [projectatomic/buildah#94]
I thought `skopeo` needed to copy images from, e.g. DockerHub, and make them available before `buildah` runs, but it turns out that you can just: `buildah from centos` and it'll pull the image from DockerHub if needed. That's really great from a UX perspective, but it's hard to tell that's what is happening, since there's no progress indication.

Can we add some sort of status information (e.g. pulling image, pulling layers, etc) similar to how `docker` does it with its build/run commands?

**Comment by nalind** [comment]
Are we talking about logging the pulling of an image as a single log entry, or a full-blown progress bar?

**Comment by rhatdan** [comment]
I think some code was added to container/image to make this work with skopeo?  @runcom

**Comment by runcom** [comment]
Yes, just pass an `io.Writer` to the `copy.Image` call

**Comment by TomSweeneyRedHat** [comment]
We probably want to document the io.Writer trick as an example somewhere.  Perhaps as part of the examples for the manpages?  I know today buildah took a 10+ minute nap on me before it finally responded and having some kind of progress indicator would have been nice.

**Comment by rhatdan** [comment]
I think we should turn it on by default and than add a --quiet option to buildah from.

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[buildah] Report progress when pulling or committing images, like skopeo does](https://trello.com/c/vVLoq3On/479-buildah-report-progress-when-pulling-or-committing-images-like-skopeo-does)
