### ISSUE TITLE
'buildah from' error on image argument placing is unclear

### ISSUE THREAD

**Issue by TomSweeneyRedHat** [projectatomic/buildah#940]
**Description**
Doing ` buildah from scratch --name builder` yields:
```
too many arguments specified
ERRO[0000] exit status 1
```
The error being raised is fine, but the message should instead be something like "image name is not the last argument provided".

**Steps to reproduce the issue:**
1. See description

**Describe the results you received:**
See description.

**Describe the results you expected:**

An error pointing out that the image needs to be the last argument.

**Output of `buildah version`:**

```
# buildah version
Version:         1.4-dev
Go Version:      go1.9.7
Image Spec:      1.0.0
Runtime Spec:    1.0.0
CNI Spec:        0.3.1
libcni Version:  v0.6.0
Git Commit:      00dd72aa
Built:           Thu Aug 16 13:35:08 2018
OS/Arch:         linux/amd64
```

**Comment by TomSweeneyRedHat** [comment]
Reported by "fatpointer" on IRC.

**Comment by boaz1337** [comment]
we can close this.
