### ISSUE TITLE
About the addition of some features in buildah

### ISSUE THREAD

**Issue by q384566678** [projectatomic/buildah#945]
I recently combined the docker command with some of my own ideas, and I thought the following commands might be added to buildah.

## Command
- [x] rename
Rename a local container.

- [ ] history
Displays the history of an image

- [ ] load
Load some images.(or containers?)

**Comment by q384566678** [comment]
Some of the above functions have been completed, and some are still in progress. I write this issue mainly to see everyone's views, so as to avoid doing something wrong. I will update it if I want to hit something new in the future. If you're interested, we can do these commands together.

Any ideas for adding features, or community tasks, can be updated, and this can be discussed together to improve efficiency.

**Comment by rhatdan** [comment]
The only issue I see is the slow merging of podman and buildah.  Podman has load and history already.

**Comment by q384566678** [comment]
>The only issue I see is the slow merging of podman and buildah. Podman has load and history already.

So we don't need these commands? I don't know much about podman yet, not sure about the relationship between the two. It seems to me that these are two separate tools.

**Comment by rhatdan** [comment]
@q384566678 There is a great deal of overlay.  podman and buildah use the same storage and can interact well at the image level.

podman build == buildah bud

podman verndors in buildah to do the building.

podman CLI implements 95% of the Docker CLI.  So most of the features that buildah is missing are implemented in podman.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat We should probably reference podman more heavily in the buildah man pages to point users to it for some activities.

**Comment by TomSweeneyRedHat** [comment]
@rhatdan I'll noodle on that, I think it might be nice to put together a faq like document that for both projects that could be shared somehow.  I'd like it to live in one of the two projects just so we don't have to do a double update.  Will get something together.

**Comment by q384566678** [comment]
@rhatdan @TomSweeneyRedHat Recently I downloaded and used podman and got a new understanding of buildah. In my understanding, buildah is just a simple tool for creating images and containers, and doesn't need many other commands (you can use podman if you need).Is this my understanding correct?

**Comment by vrothberg** [comment]
@q384566678 I may answer the question.

That's correct, Podman is for container execution and management, Buildah is for image building, and [Skopeo](https://github.com/containers/skopeo) is for image distribution. In my opinion it makes a lot of sense to have separate tools for that (with some overlap), as it allows to cover more use-cases while still keeping the CLI comparatively small and well structured.

**Comment by q384566678** [comment]
@vrothberg I got it, thanks for your explanation.
It seems that buildah already has enough commands. I will close this issuse because the features in these plans are not needed.
