### ISSUE TITLE
Should buildah-created containers be visible to runc or other tools?

### ISSUE THREAD

**Issue by jawnsy** [projectatomic/buildah#95]
After starting a build container, I can see container info in `buildah containers`:

```
$ buildah containers
CONTAINER ID IMAGE ID     IMAGE NAME CONTAINER NAME
979899ca9bdd 420ed202baa9 centos:7   centos-working-container
04c1c262f3c3 198b6e31178e debian:sid debian-working-container
```

I wanted to inspect container metadata, so I tried using `skopeo inspect` and `runc list`, but the containers aren't visible to those tools, even after playing with `--root` parameters. I guess those tools aren't appropriate anyway, as these are containers, not images (yet).

```
$ sudo runc --root /var/lib/containers/storage list
load container mounts: container "mounts" does not exist
load container overlay2: container "overlay2" does not exist
load container overlay2-containers: container "overlay2-containers" does not exist
load container overlay2-images: container "overlay2-images" does not exist
load container overlay2-layers: container "overlay2-layers" does not exist
load container tmp: container "tmp" does not exist
ID          PID         STATUS      BUNDLE      CREATED
$ sudo runc --root /var/run/containers/storage list
load container overlay2-containers: container "overlay2-containers" does not exist
load container overlay2-layers: container "overlay2-layers" does not exist
ID          PID         STATUS      BUNDLE      CREATED
```

Maybe some sort of `buildah describe` command that can dump out current config state of a build container would be useful? Additionally, some way to read configuration info using `buildah config` could be useful (e.g. if the user runs `buildah config ctr1234 --user`, it should print the "current" user?)

Jonathan

**Comment by nalind** [comment]
`runc` only knows about containers that are running, and is oblivious to management of their filesystems.  `skopeo` only cares about images, so until we commit an image, it won't see anything.  The container's storage is visible to _ocid_, but since the container's metadata doesn't look like the metadata of a container that `ocid` would have created, it ignores it.

Adding an option to `config` that outputs some or all of the configuration info after applying any changes which have been specified would be useful.

**Comment by jawnsy** [comment]
How about:

```
buildah config ctr1234 set label io.k8s.description="i'm cool because buildah built me" io.openshift.tags="mongodb"
buildah config ctr1234 get labels # return all label/value pairs
buildah config ctr1234 get label io.k8s.description
```

(kind of modeled after `oc get pods` etc. If there's config that supports multiple values, then create/delete commands might be useful too)

Also, should `buildah` have push/pull commands like Docker, or should we encourage the use of skopeo to do that? It seems reasonable to me that buildah support `pull` given that `buildah from` will implicitly pull images if needed, and if we support that then the converse operation `push` seems reasonable to have as well (though that might be a whole other can-o-worms best left to `skopeo`)

**Comment by nalind** [comment]
I'm not entirely sold on changing how the `config` command's argument parsing works again, but @rhatdan probably has stronger opinions on that.  The image name for `commit` is parsed as an image location, though at the moment I don't think it knows how to authenticate to a registry, if the specified location is in a registry.

**Comment by rhatdan** [comment]
How about 
buildah inspect ctr1234

Which would output a json encoded structure, then we can add a --format command to allow someone to pick out which fields they want.

**Comment by nalind** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[buildah] Fix build-using-dockerfile's handling of image configurations](https://trello.com/c/nYY2wUAF/478-buildah-fix-build-using-dockerfile-s-handling-of-image-configurations)

**Comment by rhatdan** [comment]
Buildah inspect now exists, so I am closing.
