### ISSUE TITLE
Need to figure out how to authenticate to registries

### ISSUE THREAD

**Issue by nalind** [projectatomic/buildah#96]
We need to be able to set the `DockerAuthConfig` in the `DestinationCtx` in the structure returned by the internal `getCopyOptions()` function, to support authenticating to registries.  We also need to be able to retrieve values to set there, presumably from the same locations that `skopeo` supports.

**Comment by TomSweeneyRedHat** [comment]
Wrapped up my BZ's, going to start in on this.  If someone else has already, let me know and I'll grab something else.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat Do you think you could get back to this one?

**Comment by TomSweeneyRedHat** [comment]
I think this maybe completed, but have created a Trello card to track any remaining pieces at: https://trello.com/c/5SZW0H29/553-3-buildah-authenticate-to-registries-demo.  Closing this here.
